// Code generated by skgo. DO NOT EDIT.
import { building } from "$app/env";
import { error, redirect } from "@sveltejs/kit";
import type { Profile } from "../../../../lib/skgo/actiondemo/types";

// Go answers this load at runtime. Kit calls it during prerendering,
// when the adapter's build-only Go process supplies its result.
const unimplemented = (route: string): never => {
  throw new Error("skgo: implemented in Go");
};

const buildLoad = async (
  module: string,
  event: import("@sveltejs/kit").RequestEvent,
): Promise<any> => {
  const bridge = (
    event.platform as
      | {
          skgoPrerenderLoad?: (
            module: string,
            event: import("@sveltejs/kit").RequestEvent,
          ) => Promise<any>;
        }
      | undefined
  )?.skgoPrerenderLoad;
  if (!bridge) throw new Error("skgo: prerender Go load bridge unavailable");
  const answer = await bridge(module, event);
  if (answer.redirect) redirect(answer.redirect.status, answer.redirect.location);
  if (answer.error) error(answer.error.status, answer.error.message);
  if (answer.data === undefined) throw new Error("skgo: prerender Go load returned no data");
  return answer.data;
};

export const load = async (
  event: import("@sveltejs/kit").RequestEvent,
): Promise<{ selected: string; ada: Profile; grace: Profile }> =>
  building
    ? buildLoad("src/routes/actions/profiles/[profile]/+page.server.ts", event)
    : unimplemented(event.url.pathname);

// Kit reads these exports for action typing; Go answers every submission.
export const actions = {
  save: async (_event: { request: Request }): Promise<{ receipt: string }> => {
    throw new Error("skgo: action implemented in Go");
  },
};
