// Code generated by skgo. DO NOT EDIT.
import type { RequestEvent } from "@sveltejs/kit";
import type { Profile } from "../../../../lib/skgo/actiondemo/types";

export const load = async (
  event: RequestEvent,
): Promise<{ selected: string; ada: Profile; grace: Profile }> => {
  throw new Error("skgo: implemented in Go");
};

// Kit reads these exports for action typing; Go answers every submission.
export const actions = {
  save: async (_event: { request: Request }): Promise<{ receipt: string }> => {
    throw new Error("skgo: action implemented in Go");
  },
};
