// Code generated by skgo. DO NOT EDIT.

package profileeditor

import skgo "github.com/tylergannon/skgo"

import (
	hooks "github.com/tylergannon/skgo/example/web/src"
)

// RouteParams stores converted values. Only accessor reads record dependencies
// on the load invocation that constructed these params.
type RouteParams struct {
	event        *skgo.Event
	valueProfile string
}

func (p RouteParams) Profile() string { skgo.TrackLoadParam(p.event, "profile"); return p.valueProfile }

type RequestEvent = skgo.RequestEvent[RouteParams]

func SkgoRequestEvent(event *skgo.Event) RequestEvent {
	return RequestEvent{Event: event, Params: RouteParams{event: event,
		valueProfile: skgo.LoadParamValue[string](event, "profile"),
	}}
}

func SkgoParamMatchers() map[string]skgo.ParamMatcher {
	return map[string]skgo.ParamMatcher{
		"Order": func(value string) (any, bool) { return hooks.Order(value) },
	}
}
