// Code generated by skgo. DO NOT EDIT.

package requestfetch

// The functions this package declares, published under names the generated
// bindings package can spell. Each is the function itself and not a wrapper:
// skgo.Refresh finds a query by the code pointer of the function it names.
var (
	// Skgo_pageLoad is pageLoad, published as the server load of src/routes/request-fetch/+page.server.ts.
	Skgo_pageLoad = pageLoad
)
