// Code generated by skgo. DO NOT EDIT.

package params

import (
	fmt "fmt"
	skgo "github.com/tylergannon/skgo"
	appstate "github.com/tylergannon/skgo/example/internal/app"
	hooks "github.com/tylergannon/skgo/example/web/src"
	http "net/http"
	reflect "reflect"
)

type Params struct {
	value_61             Key_A
	value_62             Key_B
	value_67726f7570     Key_Group
	value_6964           Key_ID
	value_69676e6f726564 Key_Ignored
	value_6974656d       Key_Item
	value_6b696e64       Key_Kind
	value_6d6f6465       Key_Mode
	value_6e756d626572   Key_Number
	value_70726f66696c65 Key_Profile
	value_72657374       Key_Rest
	value_73656374696f6e Key_Section
	value_736c7567       Key_Slug
}

type RequestEvent = skgo.RequestEvent[Params, appstate.Locals]
type Resolve = skgo.RequestResolve[Params, appstate.Locals]
type Middleware skgo.RequestMiddleware[Params, appstate.Locals]
type Handle skgo.RequestHandle[Params, appstate.Locals]

func (h Handle) Middleware() Middleware {
	return Middleware(skgo.RequestHandle[Params, appstate.Locals](h).Middleware())
}
func Sequence(hooks ...Middleware) Middleware {
	values := make([]skgo.RequestMiddleware[Params, appstate.Locals], len(hooks))
	for i, h := range hooks {
		values[i] = skgo.RequestMiddleware[Params, appstate.Locals](h)
	}
	return Middleware(skgo.RequestSequence(values...))
}
func (h Handle) Intercept(cfg skgo.HandleConfig, next http.Handler) http.Handler {
	return h.Middleware().Intercept(cfg, next)
}
func (h Middleware) Intercept(cfg skgo.HandleConfig, next http.Handler) http.Handler {
	return skgo.RequestMiddleware[Params, appstate.Locals](h).Intercept(cfg, func(event *skgo.Event) (Params, error) {
		id, values := skgo.HookValues(event)
		p, err := SkgoParams(id, values)
		if err != nil {
			return p, skgo.Errorf(503, "skgo: callerManifestDrift: %v", err)
		}
		return p, nil
	}, next)
}

type Key_A interface{ skgoParam_61() }

func (p Params) A() Key_A { return p.value_61 }

type AParam_OrderNumber struct{ Value hooks.OrderNumber }

func (AParam_OrderNumber) skgoParam_61() {}

type Key_B interface{ skgoParam_62() }

func (p Params) B() Key_B { return p.value_62 }

type BParam_OrderNumber struct{ Value hooks.OrderNumber }

func (BParam_OrderNumber) skgoParam_62() {}

type Key_Group interface{ skgoParam_67726f7570() }

func (p Params) Group() Key_Group { return p.value_67726f7570 }

type GroupParam_String struct{ Value string }

func (GroupParam_String) skgoParam_67726f7570() {}

type Key_ID interface{ skgoParam_6964() }

func (p Params) ID() Key_ID { return p.value_6964 }

type IDParam_String struct{ Value string }

func (IDParam_String) skgoParam_6964() {}

type Key_Ignored interface{ skgoParam_69676e6f726564() }

func (p Params) Ignored() Key_Ignored { return p.value_69676e6f726564 }

type IgnoredParam_String struct{ Value string }

func (IgnoredParam_String) skgoParam_69676e6f726564() {}

type Key_Item interface{ skgoParam_6974656d() }

func (p Params) Item() Key_Item { return p.value_6974656d }

type ItemParam_String struct{ Value string }

func (ItemParam_String) skgoParam_6974656d() {}

type Key_Kind interface{ skgoParam_6b696e64() }

func (p Params) Kind() Key_Kind { return p.value_6b696e64 }

type KindParam_String struct{ Value string }

func (KindParam_String) skgoParam_6b696e64() {}

type Key_Mode interface{ skgoParam_6d6f6465() }

func (p Params) Mode() Key_Mode { return p.value_6d6f6465 }

type ModeParam_String struct{ Value string }

func (ModeParam_String) skgoParam_6d6f6465() {}

type Key_Number interface{ skgoParam_6e756d626572() }

func (p Params) Number() Key_Number { return p.value_6e756d626572 }

type NumberParam_OrderNumber struct{ Value hooks.OrderNumber }

func (NumberParam_OrderNumber) skgoParam_6e756d626572() {}

type Key_Profile interface{ skgoParam_70726f66696c65() }

func (p Params) Profile() Key_Profile { return p.value_70726f66696c65 }

type ProfileParam_String struct{ Value string }

func (ProfileParam_String) skgoParam_70726f66696c65() {}

type Key_Rest interface{ skgoParam_72657374() }

func (p Params) Rest() Key_Rest { return p.value_72657374 }

type RestParam_String struct{ Value string }

func (RestParam_String) skgoParam_72657374() {}

type Key_Section interface{ skgoParam_73656374696f6e() }

func (p Params) Section() Key_Section { return p.value_73656374696f6e }

type SectionParam_String struct{ Value string }

func (SectionParam_String) skgoParam_73656374696f6e() {}

type Key_Slug interface{ skgoParam_736c7567() }

func (p Params) Slug() Key_Slug { return p.value_736c7567 }

type SlugParam_String struct{ Value string }

func (SlugParam_String) skgoParam_736c7567() {}

// SkgoCallerRoutes describes every constructor generated from Kit's route metadata.
func SkgoCallerRoutes() skgo.CallerRoutes {
	return skgo.CallerRoutes{
		"/":                              {Params: []skgo.ManifestParam{}, NewParams: func(values map[string]any) (any, error) { return SkgoParams("/", values) }},
		"/(marketing)":                   {Params: []skgo.ManifestParam{}, NewParams: func(values map[string]any) (any, error) { return SkgoParams("/(marketing)", values) }},
		"/(marketing)/pricing":           {Params: []skgo.ManifestParam{}, NewParams: func(values map[string]any) (any, error) { return SkgoParams("/(marketing)/pricing", values) }},
		"/about":                         {Params: []skgo.ManifestParam{}, NewParams: func(values map[string]any) (any, error) { return SkgoParams("/about", values) }},
		"/account":                       {Params: []skgo.ManifestParam{}, NewParams: func(values map[string]any) (any, error) { return SkgoParams("/account", values) }},
		"/account/orders":                {Params: []skgo.ManifestParam{}, NewParams: func(values map[string]any) (any, error) { return SkgoParams("/account/orders", values) }},
		"/account/reruns":                {Params: []skgo.ManifestParam{}, NewParams: func(values map[string]any) (any, error) { return SkgoParams("/account/reruns", values) }},
		"/account/reruns/[slug]":         {Params: []skgo.ManifestParam{{Name: "slug", Matcher: "", Optional: false, Rest: false, Chained: false}}, NewParams: func(values map[string]any) (any, error) { return SkgoParams("/account/reruns/[slug]", values) }},
		"/account/statement":             {Params: []skgo.ManifestParam{}, NewParams: func(values map[string]any) (any, error) { return SkgoParams("/account/statement", values) }},
		"/actions":                       {Params: []skgo.ManifestParam{}, NewParams: func(values map[string]any) (any, error) { return SkgoParams("/actions", values) }},
		"/actions/cross":                 {Params: []skgo.ManifestParam{}, NewParams: func(values map[string]any) (any, error) { return SkgoParams("/actions/cross", values) }},
		"/actions/cross/receive":         {Params: []skgo.ManifestParam{}, NewParams: func(values map[string]any) (any, error) { return SkgoParams("/actions/cross/receive", values) }},
		"/actions/cross/send":            {Params: []skgo.ManifestParam{}, NewParams: func(values map[string]any) (any, error) { return SkgoParams("/actions/cross/send", values) }},
		"/actions/default":               {Params: []skgo.ManifestParam{}, NewParams: func(values map[string]any) (any, error) { return SkgoParams("/actions/default", values) }},
		"/actions/default/saved":         {Params: []skgo.ManifestParam{}, NewParams: func(values map[string]any) (any, error) { return SkgoParams("/actions/default/saved", values) }},
		"/actions/options":               {Params: []skgo.ManifestParam{}, NewParams: func(values map[string]any) (any, error) { return SkgoParams("/actions/options", values) }},
		"/actions/options/no-client":     {Params: []skgo.ManifestParam{}, NewParams: func(values map[string]any) (any, error) { return SkgoParams("/actions/options/no-client", values) }},
		"/actions/options/no-ssr":        {Params: []skgo.ManifestParam{}, NewParams: func(values map[string]any) (any, error) { return SkgoParams("/actions/options/no-ssr", values) }},
		"/actions/profiles":              {Params: []skgo.ManifestParam{}, NewParams: func(values map[string]any) (any, error) { return SkgoParams("/actions/profiles", values) }},
		"/actions/profiles/[profile]":    {Params: []skgo.ManifestParam{{Name: "profile", Matcher: "", Optional: false, Rest: false, Chained: false}}, NewParams: func(values map[string]any) (any, error) { return SkgoParams("/actions/profiles/[profile]", values) }},
		"/actions/signed-in":             {Params: []skgo.ManifestParam{}, NewParams: func(values map[string]any) (any, error) { return SkgoParams("/actions/signed-in", values) }},
		"/api":                           {Params: []skgo.ManifestParam{}, NewParams: func(values map[string]any) (any, error) { return SkgoParams("/api", values) }},
		"/api/fatal":                     {Params: []skgo.ManifestParam{}, NewParams: func(values map[string]any) (any, error) { return SkgoParams("/api/fatal", values) }},
		"/api/replay":                    {Params: []skgo.ManifestParam{}, NewParams: func(values map[string]any) (any, error) { return SkgoParams("/api/replay", values) }},
		"/api/replay-count":              {Params: []skgo.ManifestParam{}, NewParams: func(values map[string]any) (any, error) { return SkgoParams("/api/replay-count", values) }},
		"/api/replay/[kind]":             {Params: []skgo.ManifestParam{{Name: "kind", Matcher: "", Optional: false, Rest: false, Chained: false}}, NewParams: func(values map[string]any) (any, error) { return SkgoParams("/api/replay/[kind]", values) }},
		"/api/request-fetch":             {Params: []skgo.ManifestParam{}, NewParams: func(values map[string]any) (any, error) { return SkgoParams("/api/request-fetch", values) }},
		"/api/todos":                     {Params: []skgo.ManifestParam{}, NewParams: func(values map[string]any) (any, error) { return SkgoParams("/api/todos", values) }},
		"/async-ssr":                     {Params: []skgo.ManifestParam{}, NewParams: func(values map[string]any) (any, error) { return SkgoParams("/async-ssr", values) }},
		"/async-ssr/[mode]":              {Params: []skgo.ManifestParam{{Name: "mode", Matcher: "", Optional: false, Rest: false, Chained: false}}, NewParams: func(values map[string]any) (any, error) { return SkgoParams("/async-ssr/[mode]", values) }},
		"/async-ssr/[mode]/[group]":      {Params: []skgo.ManifestParam{{Name: "mode", Matcher: "", Optional: false, Rest: false, Chained: false}, {Name: "group", Matcher: "", Optional: false, Rest: false, Chained: false}}, NewParams: func(values map[string]any) (any, error) { return SkgoParams("/async-ssr/[mode]/[group]", values) }},
		"/async-ssr/control":             {Params: []skgo.ManifestParam{}, NewParams: func(values map[string]any) (any, error) { return SkgoParams("/async-ssr/control", values) }},
		"/async-ssr/control/[group]":     {Params: []skgo.ManifestParam{{Name: "group", Matcher: "", Optional: false, Rest: false, Chained: false}}, NewParams: func(values map[string]any) (any, error) { return SkgoParams("/async-ssr/control/[group]", values) }},
		"/batch":                         {Params: []skgo.ManifestParam{}, NewParams: func(values map[string]any) (any, error) { return SkgoParams("/batch", values) }},
		"/console":                       {Params: []skgo.ManifestParam{}, NewParams: func(values map[string]any) (any, error) { return SkgoParams("/console", values) }},
		"/contact":                       {Params: []skgo.ManifestParam{}, NewParams: func(values map[string]any) (any, error) { return SkgoParams("/contact", values) }},
		"/destinations":                  {Params: []skgo.ManifestParam{}, NewParams: func(values map[string]any) (any, error) { return SkgoParams("/destinations", values) }},
		"/docs":                          {Params: []skgo.ManifestParam{}, NewParams: func(values map[string]any) (any, error) { return SkgoParams("/docs", values) }},
		"/docs/[...rest]":                {Params: []skgo.ManifestParam{{Name: "rest", Matcher: "", Optional: false, Rest: true, Chained: true}}, NewParams: func(values map[string]any) (any, error) { return SkgoParams("/docs/[...rest]", values) }},
		"/empty":                         {Params: []skgo.ManifestParam{}, NewParams: func(values map[string]any) (any, error) { return SkgoParams("/empty", values) }},
		"/error":                         {Params: []skgo.ManifestParam{}, NewParams: func(values map[string]any) (any, error) { return SkgoParams("/error", values) }},
		"/error/boundary":                {Params: []skgo.ManifestParam{}, NewParams: func(values map[string]any) (any, error) { return SkgoParams("/error/boundary", values) }},
		"/error/command":                 {Params: []skgo.ManifestParam{}, NewParams: func(values map[string]any) (any, error) { return SkgoParams("/error/command", values) }},
		"/error/expected":                {Params: []skgo.ManifestParam{}, NewParams: func(values map[string]any) (any, error) { return SkgoParams("/error/expected", values) }},
		"/error/redirect":                {Params: []skgo.ManifestParam{}, NewParams: func(values map[string]any) (any, error) { return SkgoParams("/error/redirect", values) }},
		"/error/render":                  {Params: []skgo.ManifestParam{}, NewParams: func(values map[string]any) (any, error) { return SkgoParams("/error/render", values) }},
		"/error/server-only":             {Params: []skgo.ManifestParam{}, NewParams: func(values map[string]any) (any, error) { return SkgoParams("/error/server-only", values) }},
		"/error/unexpected":              {Params: []skgo.ManifestParam{}, NewParams: func(values map[string]any) (any, error) { return SkgoParams("/error/unexpected", values) }},
		"/event-layout":                  {Params: []skgo.ManifestParam{}, NewParams: func(values map[string]any) (any, error) { return SkgoParams("/event-layout", values) }},
		"/event-layout/[section]":        {Params: []skgo.ManifestParam{{Name: "section", Matcher: "", Optional: false, Rest: false, Chained: false}}, NewParams: func(values map[string]any) (any, error) { return SkgoParams("/event-layout/[section]", values) }},
		"/event-layout/[section]/[item]": {Params: []skgo.ManifestParam{{Name: "section", Matcher: "", Optional: false, Rest: false, Chained: false}, {Name: "item", Matcher: "", Optional: false, Rest: false, Chained: false}}, NewParams: func(values map[string]any) (any, error) { return SkgoParams("/event-layout/[section]/[item]", values) }},
		"/event-layout/[section]/[item]/one": {Params: []skgo.ManifestParam{{Name: "section", Matcher: "", Optional: false, Rest: false, Chained: false}, {Name: "item", Matcher: "", Optional: false, Rest: false, Chained: false}}, NewParams: func(values map[string]any) (any, error) {
			return SkgoParams("/event-layout/[section]/[item]/one", values)
		}},
		"/event-layout/[section]/[item]/two": {Params: []skgo.ManifestParam{{Name: "section", Matcher: "", Optional: false, Rest: false, Chained: false}, {Name: "item", Matcher: "", Optional: false, Rest: false, Chained: false}}, NewParams: func(values map[string]any) (any, error) {
			return SkgoParams("/event-layout/[section]/[item]/two", values)
		}},
		"/fetch":                        {Params: []skgo.ManifestParam{}, NewParams: func(values map[string]any) (any, error) { return SkgoParams("/fetch", values) }},
		"/go-dev":                       {Params: []skgo.ManifestParam{}, NewParams: func(values map[string]any) (any, error) { return SkgoParams("/go-dev", values) }},
		"/go-dev/endpoint":              {Params: []skgo.ManifestParam{}, NewParams: func(values map[string]any) (any, error) { return SkgoParams("/go-dev/endpoint", values) }},
		"/invoices":                     {Params: []skgo.ManifestParam{}, NewParams: func(values map[string]any) (any, error) { return SkgoParams("/invoices", values) }},
		"/items":                        {Params: []skgo.ManifestParam{}, NewParams: func(values map[string]any) (any, error) { return SkgoParams("/items", values) }},
		"/items/[id]":                   {Params: []skgo.ManifestParam{{Name: "id", Matcher: "", Optional: false, Rest: false, Chained: false}}, NewParams: func(values map[string]any) (any, error) { return SkgoParams("/items/[id]", values) }},
		"/live":                         {Params: []skgo.ManifestParam{}, NewParams: func(values map[string]any) (any, error) { return SkgoParams("/live", values) }},
		"/middleware":                   {Params: []skgo.ManifestParam{}, NewParams: func(values map[string]any) (any, error) { return SkgoParams("/middleware", values) }},
		"/middleware/[slug]":            {Params: []skgo.ManifestParam{{Name: "slug", Matcher: "", Optional: false, Rest: false, Chained: false}}, NewParams: func(values map[string]any) (any, error) { return SkgoParams("/middleware/[slug]", values) }},
		"/nested-universal":             {Params: []skgo.ManifestParam{}, NewParams: func(values map[string]any) (any, error) { return SkgoParams("/nested-universal", values) }},
		"/optional":                     {Params: []skgo.ManifestParam{}, NewParams: func(values map[string]any) (any, error) { return SkgoParams("/optional", values) }},
		"/plain":                        {Params: []skgo.ManifestParam{}, NewParams: func(values map[string]any) (any, error) { return SkgoParams("/plain", values) }},
		"/prerender":                    {Params: []skgo.ManifestParam{}, NewParams: func(values map[string]any) (any, error) { return SkgoParams("/prerender", values) }},
		"/prerender-consumer":           {Params: []skgo.ManifestParam{}, NewParams: func(values map[string]any) (any, error) { return SkgoParams("/prerender-consumer", values) }},
		"/prerender/[slug]":             {Params: []skgo.ManifestParam{{Name: "slug", Matcher: "", Optional: false, Rest: false, Chained: false}}, NewParams: func(values map[string]any) (any, error) { return SkgoParams("/prerender/[slug]", values) }},
		"/render-paths":                 {Params: []skgo.ManifestParam{}, NewParams: func(values map[string]any) (any, error) { return SkgoParams("/render-paths", values) }},
		"/request-fetch":                {Params: []skgo.ManifestParam{}, NewParams: func(values map[string]any) (any, error) { return SkgoParams("/request-fetch", values) }},
		"/runes-class":                  {Params: []skgo.ManifestParam{}, NewParams: func(values map[string]any) (any, error) { return SkgoParams("/runes-class", values) }},
		"/shadow":                       {Params: []skgo.ManifestParam{}, NewParams: func(values map[string]any) (any, error) { return SkgoParams("/shadow", values) }},
		"/shadow/[...rest]":             {Params: []skgo.ManifestParam{{Name: "rest", Matcher: "", Optional: false, Rest: true, Chained: true}}, NewParams: func(values map[string]any) (any, error) { return SkgoParams("/shadow/[...rest]", values) }},
		"/shadow/[slug]":                {Params: []skgo.ManifestParam{{Name: "slug", Matcher: "", Optional: false, Rest: false, Chained: false}}, NewParams: func(values map[string]any) (any, error) { return SkgoParams("/shadow/[slug]", values) }},
		"/spa":                          {Params: []skgo.ManifestParam{}, NewParams: func(values map[string]any) (any, error) { return SkgoParams("/spa", values) }},
		"/stream":                       {Params: []skgo.ManifestParam{}, NewParams: func(values map[string]any) (any, error) { return SkgoParams("/stream", values) }},
		"/todos":                        {Params: []skgo.ManifestParam{}, NewParams: func(values map[string]any) (any, error) { return SkgoParams("/todos", values) }},
		"/todos/[id]":                   {Params: []skgo.ManifestParam{{Name: "id", Matcher: "", Optional: false, Rest: false, Chained: false}}, NewParams: func(values map[string]any) (any, error) { return SkgoParams("/todos/[id]", values) }},
		"/todos/gate":                   {Params: []skgo.ManifestParam{}, NewParams: func(values map[string]any) (any, error) { return SkgoParams("/todos/gate", values) }},
		"/todos/pair":                   {Params: []skgo.ManifestParam{}, NewParams: func(values map[string]any) (any, error) { return SkgoParams("/todos/pair", values) }},
		"/typed-dependencies":           {Params: []skgo.ManifestParam{}, NewParams: func(values map[string]any) (any, error) { return SkgoParams("/typed-dependencies", values) }},
		"/typed-dependencies/[a=Order]": {Params: []skgo.ManifestParam{{Name: "a", Matcher: "Order", Optional: false, Rest: false, Chained: false}}, NewParams: func(values map[string]any) (any, error) { return SkgoParams("/typed-dependencies/[a=Order]", values) }},
		"/typed-dependencies/[a=Order]/[b=Order]": {Params: []skgo.ManifestParam{{Name: "a", Matcher: "Order", Optional: false, Rest: false, Chained: false}, {Name: "b", Matcher: "Order", Optional: false, Rest: false, Chained: false}}, NewParams: func(values map[string]any) (any, error) {
			return SkgoParams("/typed-dependencies/[a=Order]/[b=Order]", values)
		}},
		"/typed-dependencies/[a=Order]/[b=Order]/[ignored]": {Params: []skgo.ManifestParam{{Name: "a", Matcher: "Order", Optional: false, Rest: false, Chained: false}, {Name: "b", Matcher: "Order", Optional: false, Rest: false, Chained: false}, {Name: "ignored", Matcher: "", Optional: false, Rest: false, Chained: false}}, NewParams: func(values map[string]any) (any, error) {
			return SkgoParams("/typed-dependencies/[a=Order]/[b=Order]/[ignored]", values)
		}},
		"/typed-load":                {Params: []skgo.ManifestParam{}, NewParams: func(values map[string]any) (any, error) { return SkgoParams("/typed-load", values) }},
		"/typed-load/[number=Order]": {Params: []skgo.ManifestParam{{Name: "number", Matcher: "Order", Optional: false, Rest: false, Chained: false}}, NewParams: func(values map[string]any) (any, error) { return SkgoParams("/typed-load/[number=Order]", values) }},
		"/universal-fetch":           {Params: []skgo.ManifestParam{}, NewParams: func(values map[string]any) (any, error) { return SkgoParams("/universal-fetch", values) }},
		"/universal-fetch/no-script": {Params: []skgo.ManifestParam{}, NewParams: func(values map[string]any) (any, error) { return SkgoParams("/universal-fetch/no-script", values) }},
	}
}

// SkgoRequestEvent constructs the explicit event for a command or form.
func SkgoRequestEvent(event *skgo.Event) (RequestEvent, error) {
	routeID, values := skgo.RemoteCallerValues(event)
	p, err := SkgoParams(routeID, values)
	return RequestEvent{Event: event, Params: p, Locals: appstate.LocalsFrom(event.Request().Context())}, err
}

// SkgoParams constructs values for an already matched caller route.
func SkgoParams(routeID string, values map[string]any) (Params, error) {
	var p Params
	switch routeID {
	case "/":
	case "/(marketing)":
	case "/(marketing)/pricing":
	case "/about":
	case "/account":
	case "/account/orders":
	case "/account/reruns":
	case "/account/reruns/[slug]":
		if raw, present := values["slug"]; present {
			value, err := skgoSharedValue[string](raw)
			if err != nil {
				return Params{}, fmt.Errorf("skgo: caller /account/reruns/[slug] param slug: %w", err)
			}
			p.value_736c7567 = SlugParam_String{Value: value}
		}
	case "/account/statement":
	case "/actions":
	case "/actions/cross":
	case "/actions/cross/receive":
	case "/actions/cross/send":
	case "/actions/default":
	case "/actions/default/saved":
	case "/actions/options":
	case "/actions/options/no-client":
	case "/actions/options/no-ssr":
	case "/actions/profiles":
	case "/actions/profiles/[profile]":
		if raw, present := values["profile"]; present {
			value, err := skgoSharedValue[string](raw)
			if err != nil {
				return Params{}, fmt.Errorf("skgo: caller /actions/profiles/[profile] param profile: %w", err)
			}
			p.value_70726f66696c65 = ProfileParam_String{Value: value}
		}
	case "/actions/signed-in":
	case "/api":
	case "/api/fatal":
	case "/api/replay":
	case "/api/replay-count":
	case "/api/replay/[kind]":
		if raw, present := values["kind"]; present {
			value, err := skgoSharedValue[string](raw)
			if err != nil {
				return Params{}, fmt.Errorf("skgo: caller /api/replay/[kind] param kind: %w", err)
			}
			p.value_6b696e64 = KindParam_String{Value: value}
		}
	case "/api/request-fetch":
	case "/api/todos":
	case "/async-ssr":
	case "/async-ssr/[mode]":
		if raw, present := values["mode"]; present {
			value, err := skgoSharedValue[string](raw)
			if err != nil {
				return Params{}, fmt.Errorf("skgo: caller /async-ssr/[mode] param mode: %w", err)
			}
			p.value_6d6f6465 = ModeParam_String{Value: value}
		}
	case "/async-ssr/[mode]/[group]":
		if raw, present := values["mode"]; present {
			value, err := skgoSharedValue[string](raw)
			if err != nil {
				return Params{}, fmt.Errorf("skgo: caller /async-ssr/[mode]/[group] param mode: %w", err)
			}
			p.value_6d6f6465 = ModeParam_String{Value: value}
		}
		if raw, present := values["group"]; present {
			value, err := skgoSharedValue[string](raw)
			if err != nil {
				return Params{}, fmt.Errorf("skgo: caller /async-ssr/[mode]/[group] param group: %w", err)
			}
			p.value_67726f7570 = GroupParam_String{Value: value}
		}
	case "/async-ssr/control":
	case "/async-ssr/control/[group]":
		if raw, present := values["group"]; present {
			value, err := skgoSharedValue[string](raw)
			if err != nil {
				return Params{}, fmt.Errorf("skgo: caller /async-ssr/control/[group] param group: %w", err)
			}
			p.value_67726f7570 = GroupParam_String{Value: value}
		}
	case "/batch":
	case "/console":
	case "/contact":
	case "/destinations":
	case "/docs":
	case "/docs/[...rest]":
		if raw, present := values["rest"]; present {
			value, err := skgoSharedValue[string](raw)
			if err != nil {
				return Params{}, fmt.Errorf("skgo: caller /docs/[...rest] param rest: %w", err)
			}
			p.value_72657374 = RestParam_String{Value: value}
		}
	case "/empty":
	case "/error":
	case "/error/boundary":
	case "/error/command":
	case "/error/expected":
	case "/error/redirect":
	case "/error/render":
	case "/error/server-only":
	case "/error/unexpected":
	case "/event-layout":
	case "/event-layout/[section]":
		if raw, present := values["section"]; present {
			value, err := skgoSharedValue[string](raw)
			if err != nil {
				return Params{}, fmt.Errorf("skgo: caller /event-layout/[section] param section: %w", err)
			}
			p.value_73656374696f6e = SectionParam_String{Value: value}
		}
	case "/event-layout/[section]/[item]":
		if raw, present := values["section"]; present {
			value, err := skgoSharedValue[string](raw)
			if err != nil {
				return Params{}, fmt.Errorf("skgo: caller /event-layout/[section]/[item] param section: %w", err)
			}
			p.value_73656374696f6e = SectionParam_String{Value: value}
		}
		if raw, present := values["item"]; present {
			value, err := skgoSharedValue[string](raw)
			if err != nil {
				return Params{}, fmt.Errorf("skgo: caller /event-layout/[section]/[item] param item: %w", err)
			}
			p.value_6974656d = ItemParam_String{Value: value}
		}
	case "/event-layout/[section]/[item]/one":
		if raw, present := values["section"]; present {
			value, err := skgoSharedValue[string](raw)
			if err != nil {
				return Params{}, fmt.Errorf("skgo: caller /event-layout/[section]/[item]/one param section: %w", err)
			}
			p.value_73656374696f6e = SectionParam_String{Value: value}
		}
		if raw, present := values["item"]; present {
			value, err := skgoSharedValue[string](raw)
			if err != nil {
				return Params{}, fmt.Errorf("skgo: caller /event-layout/[section]/[item]/one param item: %w", err)
			}
			p.value_6974656d = ItemParam_String{Value: value}
		}
	case "/event-layout/[section]/[item]/two":
		if raw, present := values["section"]; present {
			value, err := skgoSharedValue[string](raw)
			if err != nil {
				return Params{}, fmt.Errorf("skgo: caller /event-layout/[section]/[item]/two param section: %w", err)
			}
			p.value_73656374696f6e = SectionParam_String{Value: value}
		}
		if raw, present := values["item"]; present {
			value, err := skgoSharedValue[string](raw)
			if err != nil {
				return Params{}, fmt.Errorf("skgo: caller /event-layout/[section]/[item]/two param item: %w", err)
			}
			p.value_6974656d = ItemParam_String{Value: value}
		}
	case "/fetch":
	case "/go-dev":
	case "/go-dev/endpoint":
	case "/invoices":
	case "/items":
	case "/items/[id]":
		if raw, present := values["id"]; present {
			value, err := skgoSharedValue[string](raw)
			if err != nil {
				return Params{}, fmt.Errorf("skgo: caller /items/[id] param id: %w", err)
			}
			p.value_6964 = IDParam_String{Value: value}
		}
	case "/live":
	case "/middleware":
	case "/middleware/[slug]":
		if raw, present := values["slug"]; present {
			value, err := skgoSharedValue[string](raw)
			if err != nil {
				return Params{}, fmt.Errorf("skgo: caller /middleware/[slug] param slug: %w", err)
			}
			p.value_736c7567 = SlugParam_String{Value: value}
		}
	case "/nested-universal":
	case "/optional":
	case "/plain":
	case "/prerender":
	case "/prerender-consumer":
	case "/prerender/[slug]":
		if raw, present := values["slug"]; present {
			value, err := skgoSharedValue[string](raw)
			if err != nil {
				return Params{}, fmt.Errorf("skgo: caller /prerender/[slug] param slug: %w", err)
			}
			p.value_736c7567 = SlugParam_String{Value: value}
		}
	case "/render-paths":
	case "/request-fetch":
	case "/runes-class":
	case "/shadow":
	case "/shadow/[...rest]":
		if raw, present := values["rest"]; present {
			value, err := skgoSharedValue[string](raw)
			if err != nil {
				return Params{}, fmt.Errorf("skgo: caller /shadow/[...rest] param rest: %w", err)
			}
			p.value_72657374 = RestParam_String{Value: value}
		}
	case "/shadow/[slug]":
		if raw, present := values["slug"]; present {
			value, err := skgoSharedValue[string](raw)
			if err != nil {
				return Params{}, fmt.Errorf("skgo: caller /shadow/[slug] param slug: %w", err)
			}
			p.value_736c7567 = SlugParam_String{Value: value}
		}
	case "/spa":
	case "/stream":
	case "/todos":
	case "/todos/[id]":
		if raw, present := values["id"]; present {
			value, err := skgoSharedValue[string](raw)
			if err != nil {
				return Params{}, fmt.Errorf("skgo: caller /todos/[id] param id: %w", err)
			}
			p.value_6964 = IDParam_String{Value: value}
		}
	case "/todos/gate":
	case "/todos/pair":
	case "/typed-dependencies":
	case "/typed-dependencies/[a=Order]":
		if raw, present := values["a"]; present {
			value, err := skgoSharedValue[hooks.OrderNumber](raw)
			if err != nil {
				return Params{}, fmt.Errorf("skgo: caller /typed-dependencies/[a=Order] param a: %w", err)
			}
			p.value_61 = AParam_OrderNumber{Value: value}
		}
	case "/typed-dependencies/[a=Order]/[b=Order]":
		if raw, present := values["a"]; present {
			value, err := skgoSharedValue[hooks.OrderNumber](raw)
			if err != nil {
				return Params{}, fmt.Errorf("skgo: caller /typed-dependencies/[a=Order]/[b=Order] param a: %w", err)
			}
			p.value_61 = AParam_OrderNumber{Value: value}
		}
		if raw, present := values["b"]; present {
			value, err := skgoSharedValue[hooks.OrderNumber](raw)
			if err != nil {
				return Params{}, fmt.Errorf("skgo: caller /typed-dependencies/[a=Order]/[b=Order] param b: %w", err)
			}
			p.value_62 = BParam_OrderNumber{Value: value}
		}
	case "/typed-dependencies/[a=Order]/[b=Order]/[ignored]":
		if raw, present := values["a"]; present {
			value, err := skgoSharedValue[hooks.OrderNumber](raw)
			if err != nil {
				return Params{}, fmt.Errorf("skgo: caller /typed-dependencies/[a=Order]/[b=Order]/[ignored] param a: %w", err)
			}
			p.value_61 = AParam_OrderNumber{Value: value}
		}
		if raw, present := values["b"]; present {
			value, err := skgoSharedValue[hooks.OrderNumber](raw)
			if err != nil {
				return Params{}, fmt.Errorf("skgo: caller /typed-dependencies/[a=Order]/[b=Order]/[ignored] param b: %w", err)
			}
			p.value_62 = BParam_OrderNumber{Value: value}
		}
		if raw, present := values["ignored"]; present {
			value, err := skgoSharedValue[string](raw)
			if err != nil {
				return Params{}, fmt.Errorf("skgo: caller /typed-dependencies/[a=Order]/[b=Order]/[ignored] param ignored: %w", err)
			}
			p.value_69676e6f726564 = IgnoredParam_String{Value: value}
		}
	case "/typed-load":
	case "/typed-load/[number=Order]":
		if raw, present := values["number"]; present {
			value, err := skgoSharedValue[hooks.OrderNumber](raw)
			if err != nil {
				return Params{}, fmt.Errorf("skgo: caller /typed-load/[number=Order] param number: %w", err)
			}
			p.value_6e756d626572 = NumberParam_OrderNumber{Value: value}
		}
	case "/universal-fetch":
	case "/universal-fetch/no-script":
	default:
		if routeID != "" {
			return Params{}, fmt.Errorf("skgo: unknown caller route %q; regenerate params", routeID)
		}
	}
	return p, nil
}

func skgoSharedValue[T any](raw any) (T, error) {
	var zero T
	if raw == nil && reflect.TypeFor[T]().Kind() == reflect.Interface {
		return zero, nil
	}
	value, ok := raw.(T)
	if !ok {
		return zero, fmt.Errorf("converted value %T does not fit %v", raw, reflect.TypeFor[T]())
	}
	return value, nil
}
