// Code generated by skgo. DO NOT EDIT.


// Kit reads these exports for action typing; Go answers every submission.
export const actions = {
	default: async (_event: { request: Request }): Promise<{ receipt: string; name: string; email: string; biography: string; state: string }> => { throw new Error('skgo: action implemented in Go'); },
};
