// Code generated by skgo. DO NOT EDIT.
import { building } from "$app/env";
// Runtime bodies throw. Kit build callbacks forward to Go.
// Every response is produced by the Go handler rather than
// this module. Kit reads the export names to learn which methods the route
// answers.
const unimplemented = (): never => {
  throw new Error("skgo: implemented in Go");
};
const fromGo = (event: import("@sveltejs/kit").RequestEvent): Promise<Response> => {
  const platform = event.platform as
    | { skgoPrerenderEndpoint?: (event: import("@sveltejs/kit").RequestEvent) => Promise<Response> }
    | undefined;
  return building ? (platform?.skgoPrerenderEndpoint?.(event) ?? unimplemented()) : unimplemented();
};

export const GET = fromGo;
