// Code generated by skgo. DO NOT EDIT.
import { building } from "$app/env";
import { requestHandle, requestFetch } from "@skgo/sveltekit-adapter/prerender";

export const handle: import("@sveltejs/kit/hooks").Handle = ({ event, resolve }) =>
  building ? requestHandle(event, resolve) : resolve(event);
export const handleFetch: import("@sveltejs/kit/hooks").HandleFetch = (input) =>
  building ? requestFetch(input) : input.fetch(input.request);
