// Code generated by skgo. DO NOT EDIT.

package typedload

import skgo "github.com/tylergannon/skgo"

import (
	hooks "github.com/tylergannon/skgo/example/web/src"
)

// RouteParams stores converted values. Only accessor reads record dependencies
// on the load invocation that constructed these params.
type RouteParams struct {
	event       *skgo.Event
	valueNumber hooks.OrderNumber
}

func (p RouteParams) Number() hooks.OrderNumber {
	skgo.TrackLoadParam(p.event, "number")
	return p.valueNumber
}

type RequestEvent = skgo.RequestEvent[RouteParams]

func SkgoRequestEvent(event *skgo.Event) RequestEvent {
	return RequestEvent{Event: event, Params: RouteParams{event: event,
		valueNumber: skgo.LoadParamValue[hooks.OrderNumber](event, "number"),
	}}
}

func SkgoParamMatchers() map[string]skgo.ParamMatcher {
	return map[string]skgo.ParamMatcher{
		"Order": func(value string) (any, bool) { return hooks.Order(value) },
	}
}
