// Code generated by skgo. DO NOT EDIT.
import { command, query } from '$app/server';
import type { Message } from '../../lib/skgo/store/types';
import type { Banner } from './types';

export type { Banner, Message };

// Every body throws. These functions are implemented in Go, and skgo
// answers their endpoints itself, so anything that renders in the browser
// is proof the Go handler replied rather than this module.
const unimplemented = (): never => {
	throw new Error('skgo: implemented in Go');
};

export const getBanner = query((): Banner => unimplemented());

export const getMessage = query('unchecked', (_arg: string): Message => unimplemented());

export const getMessageCount = query.live((): AsyncIterable<number> => unimplemented());

export const getMessages = query((): Array<Message> => unimplemented());

export const postMessage = command('unchecked', (_arg: string): number => unimplemented());
