//go:build jsonschema

// Code generated by skgo. DO NOT EDIT.

package messages

import (
	"encoding/json"

	"github.com/tylergannon/polytype"
)

// Stubs so the package compiles before polytype has run.
func (Banner) Schema() json.RawMessage { panic("not implemented") }

var (
	_ = polytype.Declare(Banner.Schema)
)
