// Code generated by skgo. DO NOT EDIT.

package messages

import "github.com/tylergannon/skgo"

// SkgoRemotes returns the remote functions declared in this package.
func SkgoRemotes() []*skgo.Remote {
	return []*skgo.Remote{
		skgo.NewQuery("src/routes/messages/messages.remote.ts", "getBanner", getBanner),
		skgo.NewQuery("src/routes/messages/messages.remote.ts", "getMessage", getMessage),
		skgo.NewLiveQuery("src/routes/messages/messages.remote.ts", "getMessageCount", getMessageCount),
		skgo.NewQuery("src/routes/messages/messages.remote.ts", "getMessages", getMessages),
		skgo.NewCommand("src/routes/messages/messages.remote.ts", "postMessage", postMessage),
	}
}
