package example_test

import (
	"bytes"
	"fmt"
	"io"
	"io/fs"
	"os"
	"os/exec"
	"path/filepath"
	"strings"
	"testing"
)

// TestChangingAGoTypeBreaksTheComponentThatUsesIt is the end-to-end types
// claim, checked rather than asserted.
//
// It renames one field on the wire — the json tag of businesslogic.Todo.Text —
// regenerates, and requires the SvelteKit type check to fail naming the
// component that reads the old field. Without generated TypeScript coming from
// the Go type, the change would sail through to the browser and show up as an
// empty todo.
//
// Everything happens in a throwaway copy of this module. The test used to edit
// the developer's own source and put it back in t.Cleanup, which meant a
// SIGKILL, a `-timeout` abort or a panic in the restore path left the checkout
// holding a type nobody wrote.
func TestChangingAGoTypeBreaksTheComponentThatUsesIt(t *testing.T) {
	app := sandbox(t)

	source := filepath.Join(app, "businesslogic", "store.go")
	original, err := os.ReadFile(source)
	if err != nil {
		t.Fatalf("reading %s: %v", source, err)
	}

	// The check has to be able to fail, so start from a passing state.
	if out, err := svelteCheck(app); err != nil {
		t.Fatalf("the app does not type-check before the change: %v\n%s", err, out)
	}

	const tag = "`json:\"text\"`"
	if !bytes.Contains(original, []byte(tag)) {
		t.Fatalf("%s no longer contains %s; update this test", source, tag)
	}
	changed := bytes.Replace(original, []byte(tag), []byte("`json:\"label\"`"), 1)
	if err := os.WriteFile(source, changed, 0o644); err != nil {
		t.Fatalf("writing %s: %v", source, err)
	}

	if out, err := generate(app); err != nil {
		t.Fatalf("regenerating after the change: %v\n%s", err, out)
	}

	types, err := os.ReadFile(filepath.Join(app, "web", "src", "lib", "skgo", "businesslogic", "types.ts"))
	if err != nil {
		t.Fatalf("reading the generated types: %v", err)
	}
	if !bytes.Contains(types, []byte(`"label": string`)) {
		t.Fatalf("the generated TypeScript did not follow the Go type:\n%s", types)
	}

	out, err := svelteCheck(app)
	if err == nil {
		t.Fatal("the app still type-checks after the Go type changed; the components are not typed by Go")
	}
	if !strings.Contains(out, "TodoList.svelte") || !strings.Contains(out, "'text'") {
		t.Fatalf("the type check failed, but not on the component that reads the renamed field:\n%s", out)
	}
	t.Logf("caught before the browser:\n%s", out)
}

// generate runs the app's own `go generate` inside a sandbox.
//
// GOWORK is off because the sandbox is not part of the workspace; the copied
// go.mod carries an absolute replace back to the real skgo module instead.
func generate(app string) (string, error) {
	cmd := exec.Command("go", "generate", "./...")
	cmd.Dir = filepath.Join(app, "generated")
	cmd.Env = append(os.Environ(), "GOWORK=off")
	out, err := cmd.CombinedOutput()
	return string(out), err
}

// svelteCheck runs the app's own type check, which is what `svelte-check`
// exists for: TypeScript alone cannot read a `.svelte` file.
func svelteCheck(app string) (string, error) {
	cmd := exec.Command("mise", "x", "--",
		"node", filepath.Join("node_modules", "svelte-check", "bin", "svelte-check"),
		"--tsconfig", "./tsconfig.json", "--output", "human")
	cmd.Dir = filepath.Join(app, "web")
	out, err := cmd.CombinedOutput()
	return string(out), err
}

// sandbox copies this module into t.TempDir() and returns the copy, so a test
// that has to mutate application source can do so without touching the tree
// the developer is working in. Nothing it writes survives the test, whatever
// kills it.
//
// A missing frontend toolchain is a broken environment, not a reason to pass:
// this fails rather than skipping, because in a summary a skip and a pass look
// the same and the guarantee this file exists to make would go unmade.
func sandbox(t *testing.T) string {
	t.Helper()
	requireFrontendToolchain(t)

	root, err := filepath.Abs("..")
	if err != nil {
		t.Fatalf("locating the repository root: %v", err)
	}
	app := filepath.Join(t.TempDir(), "example")

	// node_modules is 166MB of pnpm store links and e2e is a second browser
	// install; neither is an input to what this test changes. .svelte-kit's
	// build output is regenerated by vite, not read by svelte-check.
	skip := map[string]bool{
		filepath.Join("web", "node_modules"):          true,
		filepath.Join("web", ".svelte-kit", "output"): true,
		"e2e": true,
		"tmp": true,
	}
	if err := copyTree(".", app, skip); err != nil {
		t.Fatalf("copying the module into %s: %v", app, err)
	}
	if err := linkNodeModules(filepath.Join("web", "node_modules"), filepath.Join(app, "web", "node_modules")); err != nil {
		t.Fatalf("linking node_modules into the sandbox: %v", err)
	}
	if err := absoluteReplace(filepath.Join(app, "go.mod"), root); err != nil {
		t.Fatalf("rewriting the sandbox go.mod: %v", err)
	}
	return app
}

// copyTree copies src to dst, skipping the src-relative paths in skip.
func copyTree(src, dst string, skip map[string]bool) error {
	return filepath.WalkDir(src, func(path string, d fs.DirEntry, err error) error {
		if err != nil {
			return err
		}
		rel, err := filepath.Rel(src, path)
		if err != nil {
			return err
		}
		if skip[rel] {
			if d.IsDir() {
				return filepath.SkipDir
			}
			return nil
		}
		target := filepath.Join(dst, rel)
		if d.IsDir() {
			return os.MkdirAll(target, 0o755)
		}
		if !d.Type().IsRegular() {
			return nil
		}
		return copyFile(path, target)
	})
}

func copyFile(src, dst string) error {
	info, err := os.Stat(src)
	if err != nil {
		return err
	}
	in, err := os.Open(src)
	if err != nil {
		return err
	}
	defer in.Close()
	if err := os.MkdirAll(filepath.Dir(dst), 0o755); err != nil {
		return err
	}
	out, err := os.OpenFile(dst, os.O_WRONLY|os.O_CREATE|os.O_TRUNC, info.Mode().Perm())
	if err != nil {
		return err
	}
	if _, err := io.Copy(out, in); err != nil {
		out.Close()
		return err
	}
	return out.Close()
}

// linkNodeModules gives the sandbox its own node_modules whose entries point
// at the installed ones.
//
// It cannot be a single symlink to the whole directory. `node_modules/$app` is
// written by kit and holds the tsconfig every `.svelte` file inherits, whose
// `rootDirs` are relative — resolved through a symlink they name the original
// checkout, and svelte-check then type-checks the sandbox's components against
// the original's generated types. So $app is copied and everything else,
// which is position-independent, is linked.
func linkNodeModules(src, dst string) error {
	absSrc, err := filepath.Abs(src)
	if err != nil {
		return err
	}
	entries, err := os.ReadDir(absSrc)
	if err != nil {
		return err
	}
	if err := os.MkdirAll(dst, 0o755); err != nil {
		return err
	}
	for _, entry := range entries {
		if entry.Name() == "$app" {
			if err := copyTree(filepath.Join(absSrc, "$app"), filepath.Join(dst, "$app"), nil); err != nil {
				return err
			}
			continue
		}
		if err := os.Symlink(filepath.Join(absSrc, entry.Name()), filepath.Join(dst, entry.Name())); err != nil {
			return err
		}
	}
	return nil
}

// absoluteReplace points the sandbox's `replace` directive back at the real
// skgo module, which is no longer one directory up.
func absoluteReplace(gomod, root string) error {
	raw, err := os.ReadFile(gomod)
	if err != nil {
		return err
	}
	const relative = "replace github.com/tylergannon/skgo => ../"
	if !bytes.Contains(raw, []byte(relative)) {
		return fmt.Errorf("%s no longer contains %q; update this test", gomod, relative)
	}
	rewritten := bytes.Replace(raw, []byte(relative), []byte("replace github.com/tylergannon/skgo => "+root), 1)
	return os.WriteFile(gomod, rewritten, 0o644)
}

// requireFrontendToolchain fails when the JavaScript side is not installed.
//
// It used to skip. `go test ./...` then printed ok on CI and on every fresh
// clone while the only check that a Go type reaches TypeScript did not run at
// all, and nothing in the output said so.
func requireFrontendToolchain(t *testing.T) {
	t.Helper()
	for _, path := range []string{
		filepath.Join("web", "node_modules", "svelte-check"),
		filepath.Join("web", "node_modules", "$app", "tsconfig.json"),
		filepath.Join("web", ".svelte-kit", "types"),
	} {
		if _, err := os.Stat(path); err != nil {
			t.Fatalf("%s is missing, so the Go-to-TypeScript check cannot run. Run `mise x -- vp install` and `mise x -- vp build` in example/web.", path)
		}
	}
	if _, err := exec.LookPath("mise"); err != nil {
		t.Fatal("mise is not installed, so the Go-to-TypeScript check cannot run")
	}
}
