// Code generated by skgo. DO NOT EDIT.

package redirect

import "github.com/tylergannon/skgo"

// SkgoRemotes returns the remote functions declared in this package.
func SkgoRemotes() []*skgo.Remote {
	return []*skgo.Remote{
		skgo.NewQuery("src/routes/redirect/redirect.remote.ts", "goSomewhereElse", goSomewhereElse),
	}
}
