// Code generated by skgo. DO NOT EDIT.

package live

// The functions this package declares, published under names the generated
// bindings package can spell. Each is the function itself and not a wrapper:
// skgo.Refresh finds a query by the code pointer of the function it names.
var (
	// Skgo_watchBoard is watchBoard, published as src/routes/live/board.remote.ts#watchBoard.
	Skgo_watchBoard = watchBoard
)

type (
	// SkgoOut_watchBoard is the type watchBoard yields.
	SkgoOut_watchBoard = Board
)
