// Code generated by skgo. DO NOT EDIT.
import type { RequestEvent } from "@sveltejs/kit";

export const load = async (
  event: RequestEvent,
): Promise<{
  headline: string;
  digest: Promise<Array<string>>;
  ticker: Promise<string>;
  weather: { heading: string; forecast: Promise<string> };
}> => {
  throw new Error("skgo: implemented in Go");
};
