// Code generated by skgo. DO NOT EDIT.
import { building } from "$app/env";
import { error, redirect } from "@sveltejs/kit";
import type { Order } from "./types";

// Go answers this load at runtime. Kit calls it during prerendering,
// when the adapter's build-only Go process supplies its result.
const unimplemented = (route: string): never => {
  throw new Error("skgo: implemented in Go");
};

const buildLoad = async (
  module: string,
  event: import("@sveltejs/kit").RequestEvent,
): Promise<any> => {
  const bridge = (
    event.platform as
      | {
          skgoPrerenderLoad?: (
            module: string,
            event: import("@sveltejs/kit").RequestEvent,
          ) => Promise<any>;
        }
      | undefined
  )?.skgoPrerenderLoad;
  if (!bridge) throw new Error("skgo: prerender Go load bridge unavailable");
  const answer = await bridge(module, event);
  if (answer.redirect) redirect(answer.redirect.status, answer.redirect.location);
  if (answer.error) error(answer.error.status, answer.error.message);
  if (answer.data === undefined) throw new Error("skgo: prerender Go load returned no data");
  return answer.data;
};

export const load = async (
  event: import("@sveltejs/kit").RequestEvent,
): Promise<{ orderTotal: number; orders: Promise<Array<Order>> }> =>
  building
    ? buildLoad("src/routes/account/orders/+page.server.ts", event)
    : unimplemented(event.url.pathname);
