// Code generated by skgo. DO NOT EDIT.
import type { RequestEvent } from "@sveltejs/kit";
import type { Order } from "./types";

export const load = async (
  event: RequestEvent,
): Promise<{ orderTotal: number; orders: Promise<Array<Order>> }> => {
  throw new Error("skgo: implemented in Go");
};
