// Code generated by polytype. DO NOT EDIT.

/**
 * Order is one line of the visitor's order history.
 */
export type Order = {
  /**
   * Item is what was bought.
   */
  "item": string;
  /**
   * Cents is what it cost.
   */
  "cents": number;
};
