// Code generated by skgo. DO NOT EDIT.

package replaycount

// The functions this package declares, published under names the generated
// bindings package can spell. Each is the function itself and not a wrapper:
// skgo.Refresh finds a query by the code pointer of the function it names.
var (
	// Skgo_counts is counts, published as GET /api/replay-count.
	Skgo_counts = counts
)
