// Code generated by skgo. DO NOT EDIT.
import { form } from '$app/server';
import type { Input, Result } from './types';

export type { Input, Result };

// Every body throws. These functions are implemented in Go, and skgo
// answers their endpoints itself, so anything that renders in the browser
// is proof the Go handler replied rather than this module.
const unimplemented = (): never => {
	throw new Error('skgo: implemented in Go');
};

export const submit = form('unchecked', (_arg: Input): Result => unimplemented());
