// Code generated by skgo. DO NOT EDIT.

package optional

// The functions this package declares, published under names the generated
// bindings package can spell. Each is the function itself and not a wrapper:
// skgo.Refresh finds a query by the code pointer of the function it names.
var (
	// Skgo_submit is submit, published as src/routes/optional/optional.remote.ts#submit.
	Skgo_submit = submit
)

type (
	// SkgoArg_submit is the type submit takes.
	SkgoArg_submit = Input
)
