// Code generated by polytype. DO NOT EDIT.

export type Input = {
  "name": string;
  "count"?: number;
  "enabled"?: boolean;
  "label"?: string;
};

export type Result = {
  "name": string;
  "count": string;
  "enabled": string;
  "label": string;
  "operations": number;
};
