// Code generated by skgo. DO NOT EDIT.
import Foundation
import CoreFoundation
import SKGoNative

public enum NativeModelError: Error, Sendable {
    case invalid(String)
}
fileprivate enum _SKGoWire {
    static func depth(_ value: Int) throws {
        guard value < 256 else { throw NativeModelError.invalid("Model depth exceeds 255") }
    }
    static func object(_ value: Any, keys: Set<String>) throws -> [String: Any] {
        guard let object = value as? [String: Any], Set(object.keys).isSubset(of: keys) else {
            throw NativeModelError.invalid("Expected a closed model object")
        }
        return object
    }
    static func required(_ object: [String: Any], _ key: String) throws -> Any {
        guard let value = object[key] else { throw NativeModelError.invalid("Missing required field: \(key)") }
        return value
    }
    static func optional<T>(_ value: Any?, decode: (Any) throws -> T) throws -> T? {
        guard let value else { return nil }
        return try decode(value)
    }
    static func nullable<T>(_ value: Any, decode: (Any) throws -> T) throws -> T? {
        if value is NSNull { return nil }
        return try decode(value)
    }
    static func string(_ value: Any) throws -> String {
        guard let string = value as? String else { throw NativeModelError.invalid("Expected a string") }
        return string
    }
    static func boolean(_ value: Any) throws -> Bool {
        guard let number = value as? NSNumber, CFGetTypeID(number) == CFBooleanGetTypeID() else {
            throw NativeModelError.invalid("Expected a boolean")
        }
        return number.boolValue
    }
    static func numeric(_ value: Any) throws -> Double {
        guard let number = value as? NSNumber, CFGetTypeID(number) != CFBooleanGetTypeID(), number.doubleValue.isFinite else {
            throw NativeModelError.invalid("Expected a finite number")
        }
        return number.doubleValue
    }
    static func integer<T: FixedWidthInteger>(_ value: Any, as type: T.Type) throws -> T {
        let number = try numeric(value)
        guard number.rounded(.towardZero) == number, abs(number) <= 9_007_199_254_740_991, let result = T(exactly: number) else {
            throw NativeModelError.invalid("Integer is outside its native/wire domain")
        }
        return result
    }
    static func number<T: BinaryFloatingPoint>(_ value: Any, as type: T.Type) throws -> T {
        let result = T(try numeric(value))
        guard result.isFinite else { throw NativeModelError.invalid("Number is outside its native domain") }
        return result
    }
    static func encodeInteger<T: BinaryInteger>(_ value: T) throws -> Any {
        guard let number = Int64(exactly: value), number >= -9_007_199_254_740_991, number <= 9_007_199_254_740_991 else {
            throw NativeModelError.invalid("Integer is outside the JavaScript number domain")
        }
        return NSNumber(value: number)
    }
    static func encodeNumber<T: BinaryFloatingPoint>(_ value: T) throws -> Any {
        let number = Double(value)
        guard number.isFinite else { throw NativeModelError.invalid("Expected a finite number") }
        return NSNumber(value: number)
    }
    static func array(_ value: Any, length: Int? = nil) throws -> [Any] {
        guard let array = value as? [Any], length == nil || array.count == length else {
            throw NativeModelError.invalid("Expected an array with the declared length")
        }
        return array
    }
    static func encodeArray<T>(_ values: [T], length: Int? = nil, encode: (T) throws -> Any) throws -> Any {
        guard length == nil || values.count == length else { throw NativeModelError.invalid("Incorrect fixed array length") }
        return try values.map(encode)
    }
}


public final class Session: Sendable {
public let user: String
public init(user: String) {
self.user = user
}
}
fileprivate func _skgoEncodeType_Session(_ value: Session, _ depth: Int) throws -> Any {
try _SKGoWire.depth(depth)
var object: [String: Any] = [:]
object["user"] = value.user
return object
}
fileprivate func _skgoDecodeType_Session(_ value: Any, _ depth: Int) throws -> Session {
try _SKGoWire.depth(depth)
let object = try _SKGoWire.object(value, keys: ["user"])
let field0: String = try _SKGoWire.string(try _SKGoWire.required(object, "user"))
return Session(user: field0)
}

fileprivate func _skgoEncodeRoot_0(_ value: String, _ depth: Int) throws -> Any {
try _SKGoWire.depth(depth)
return value
}
fileprivate func _skgoDecodeRoot_0(_ value: Any, _ depth: Int) throws -> String {
try _SKGoWire.depth(depth)
return try _SKGoWire.string(value)
}

fileprivate func _skgoEncodeRoot_1(_ value: Session, _ depth: Int) throws -> Any {
try _SKGoWire.depth(depth)
return try _skgoEncodeType_Session(value, depth)
}
fileprivate func _skgoDecodeRoot_1(_ value: Any, _ depth: Int) throws -> Session {
try _SKGoWire.depth(depth)
return try _skgoDecodeType_Session(value, depth)
}

public struct NativeAPI: Sendable {
private let core: RemoteClient
public init(core: RemoteClient) { self.core = core }
/// Kit remote 4cga8b/signIn
public func signIn(_ argument: String, updates: [QueryUpdate] = []) async throws -> Session {
let argument = try JSONSerialization.data(withJSONObject: _skgoEncodeRoot_0(argument, 0), options: [.fragmentsAllowed])
guard let data = try await core.call("4cga8b/signIn", kind: .command, argument: argument, updates: updates) else { throw NativeModelError.invalid("Expected a result") }
return try _skgoDecodeRoot_1(JSONSerialization.jsonObject(with: data, options: [.fragmentsAllowed]), 0)
}
/// Kit remote 4cga8b/whoami
public func whoami() async throws -> Session {
guard let data = try await core.call("4cga8b/whoami", kind: .query, argument: nil) else { throw NativeModelError.invalid("Expected a result") }
return try _skgoDecodeRoot_1(JSONSerialization.jsonObject(with: data, options: [.fragmentsAllowed]), 0)
}
public func retainWhoami() async throws -> RemoteQuery<Session> {
return try await core.query("4cga8b/whoami", argument: nil) { data in
guard let data else { throw NativeModelError.invalid("Expected a result") }
return try _skgoDecodeRoot_1(JSONSerialization.jsonObject(with: data, options: [.fragmentsAllowed]), 0)
}
}
}
