// Code generated by skgo. DO NOT EDIT.

package errorroutes

import "github.com/tylergannon/skgo"

// SkgoRemotes returns the remote functions declared in this package.
func SkgoRemotes() []*skgo.Remote {
	return []*skgo.Remote{
		skgo.NewQuery("src/routes/error/error.remote.ts", "expectedError", expectedError),
		skgo.NewQuery("src/routes/error/error.remote.ts", "unexpectedError", unexpectedError),
	}
}
