// Code generated by skgo. DO NOT EDIT.

package todos

import "github.com/tylergannon/skgo"

// SkgoRemotes returns the remote functions declared in this package.
func SkgoRemotes() []*skgo.Remote {
	return []*skgo.Remote{
		skgo.NewCommand("src/routes/todos/todos.remote.ts", "addTodo", addTodo),
		skgo.NewQuery("src/routes/todos/todos.remote.ts", "getTodo", getTodo),
		skgo.NewQuery("src/routes/todos/todos.remote.ts", "getTodos", getTodos),
		skgo.NewCommand("src/routes/todos/todos.remote.ts", "renameTodo", renameTodo),
		skgo.NewLiveQuery("src/routes/todos/todos.remote.ts", "watchCount", watchCount),
	}
}
