//go:build jsonschema

// Code generated by skgo. DO NOT EDIT.

package todos

import (
	"encoding/json"

	"github.com/tylergannon/polytype"
)

// Stubs so the package compiles before polytype has run.
func (Rename) Schema() json.RawMessage  { panic("not implemented") }
func (Retitle) Schema() json.RawMessage { panic("not implemented") }

var (
	_ = polytype.Declare(Rename.Schema)
	_ = polytype.Declare(Retitle.Schema)
)
