// Code generated by skgo. DO NOT EDIT.
import { command, query } from '$app/server';
import type { Todo } from '../../lib/skgo/businesslogic/types';
import type { Rename, Retitle } from './types';

export type { Rename, Retitle, Todo };

// Every body throws. These functions are implemented in Go, and skgo
// answers their endpoints itself, so anything that renders in the browser
// is proof the Go handler replied rather than this module.
const unimplemented = (): never => {
	throw new Error('skgo: implemented in Go');
};

export const addTodo = command('unchecked', (_arg: string): Todo => unimplemented());

export const getTodo = query('unchecked', (_arg: string): Todo => unimplemented());

export const getTodos = query((): Array<Todo> => unimplemented());

export const renameTodo = command('unchecked', (_arg: Rename): Todo => unimplemented());

export const retitleTodo = command('unchecked', (_arg: Retitle): Todo => unimplemented());

export const watchCount = query.live((): AsyncIterable<number> => unimplemented());
