// Code generated by polytype. DO NOT EDIT.

/**
 * Rename is the argument of the renameTodo command.
 */
export type Rename = {
  /**
   * ID names the todo to change.
   */
  "id": string;
  /**
   * Text is its new text.
   */
  "text": string;
};
