// Code generated by skgo. DO NOT EDIT.
import { query } from '$app/server';
import type { Board } from './types';

export type { Board };

// Every body throws. These functions are implemented in Go, and skgo
// answers their endpoints itself, so anything that renders in the browser
// is proof the Go handler replied rather than this module.
const unimplemented = (): never => {
	throw new Error('skgo: implemented in Go');
};

export const watchBoard = query.live((): AsyncIterable<Board> => unimplemented());
