// Code generated by skgo. DO NOT EDIT.

package nossr

// The functions this package declares, published under names the generated
// bindings package can spell. Each is the function itself and not a wrapper:
// skgo.Refresh finds a query by the code pointer of the function it names.
var (
	// Skgo_pageLoad is pageLoad, published as the server load of src/routes/actions/options/no-ssr/+page.server.ts.
	Skgo_pageLoad    = pageLoad
	Skgo_forbidden   = forbidden
	Skgo_save        = save
	Skgo_signIn      = signIn
	Skgo_unavailable = unavailable
)
