// Code generated by skgo. DO NOT EDIT.
import type { RequestEvent } from "@sveltejs/kit";
import type { Profile } from "../../../../lib/skgo/actiondemo/types";

export const load = async (event: RequestEvent): Promise<{ saved: boolean; profile: Profile }> => {
  throw new Error("skgo: implemented in Go");
};
