// Code generated by skgo. DO NOT EDIT.

package redirect

// The functions this package declares, published under names the generated
// bindings package can spell. Each is the function itself and not a wrapper:
// skgo.Refresh finds a query by the code pointer of the function it names.
var (
	// Skgo_whereTo is whereTo, published as src/routes/error/redirect/redirect.remote.ts#whereTo.
	Skgo_whereTo = whereTo
)
