// Code generated by polytype. DO NOT EDIT.

/**
 * Destination is what this query would have answered with.
 */
export type Destination = {
  /**
   * Where is the path the visitor is sent to.
   */
  "where": string;
};
