// Code generated by skgo. DO NOT EDIT.
import type { RequestEvent } from "@sveltejs/kit";

export const load = async (
  event: RequestEvent,
): Promise<{
  eventSection: string;
  eventItem: string;
  eventRoute: string;
  eventUser: string;
  eventSerial: number;
}> => {
  throw new Error("skgo: implemented in Go");
};
