// Code generated by polytype. DO NOT EDIT.

/**
 * Message is one guestbook entry.
 */
export type Message = {
  "id": number;
  "author": string;
  "text": string;
  "attachment": Attachment;
  "postedAt": string;
};

/**
 * Attachment mirrors the { name, size } shape the app renders.
 */
export type Attachment = {
  "name": string;
  "size": number;
};
