//go:build jsonschema

// Code generated by skgo. DO NOT EDIT.

package boundary

import (
	"encoding/json"

	"github.com/tylergannon/polytype"
)

// Stubs so the package compiles before polytype has run.
func (Reading) Schema() json.RawMessage { panic("not implemented") }

var (
	_ = polytype.Declare(Reading.Schema)
)
