// Code generated by skgo. DO NOT EDIT.

package boundary

// The functions this package declares, published under names the generated
// bindings package can spell. Each is the function itself and not a wrapper:
// skgo.Refresh finds a query by the code pointer of the function it names.
var (
	// Skgo_readSensor is readSensor, published as src/routes/error/boundary/boundary.remote.ts#readSensor.
	Skgo_readSensor = readSensor
)
