// Code generated by polytype. DO NOT EDIT.

/**
 * Reading is the value this query never produces.
 */
export type Reading = {
  /**
   * Celsius is the temperature that would have been read.
   */
  "celsius": number;
};
