// Code generated by skgo. DO NOT EDIT.
import type { RequestEvent } from "@sveltejs/kit";
import type { Money } from "../../../hooks";

export const load = async (
  event: RequestEvent,
): Promise<{ featured: { name: string; price: Money } }> => {
  throw new Error("skgo: implemented in Go");
};
