// Code generated by skgo. DO NOT EDIT.
import { command, query } from '$app/server';
import type { Money } from '../../../hooks';
import type { Quote } from './types';

export type { Quote };

// Every body throws. These functions are implemented in Go, and skgo
// answers their endpoints itself, so anything that renders in the browser
// is proof the Go handler replied rather than this module.
const unimplemented = (): never => {
	throw new Error('skgo: implemented in Go');
};

export const getPlans = query((): Array<{ name: string; price: Money }> => unimplemented());

export const getSpotlight = query((): { name: string; price: Money } => unimplemented());

export const quoteFor = command('unchecked', (_arg: Money): Quote => unimplemented());
