// Code generated by skgo. DO NOT EDIT.

package pricing

import "github.com/tylergannon/skgo"

// SkgoRemotes returns the remote functions declared in this package.
func SkgoRemotes() []*skgo.Remote {
	return []*skgo.Remote{
		skgo.NewQueryNoArg("src/routes/(marketing)/pricing/pricing.remote.ts", "getPlans", getPlans),
		skgo.NewQueryNoArg("src/routes/(marketing)/pricing/pricing.remote.ts", "getSpotlight", getSpotlight),
		skgo.NewCommand("src/routes/(marketing)/pricing/pricing.remote.ts", "quoteFor", quoteFor),
	}
}

// SkgoLoads returns the server loads declared in this package.
func SkgoLoads() []*skgo.ServerLoad {
	return []*skgo.ServerLoad{
		skgo.NewLoad("src/routes/(marketing)/pricing/+page.server.ts", pageLoad),
	}
}

// SkgoEndpoints returns the server routes declared in this package.
func SkgoEndpoints() []*skgo.Endpoint {
	return []*skgo.Endpoint{}
}
