// Code generated by skgo. DO NOT EDIT.

package pricing

import (
	skgo "github.com/tylergannon/skgo"
	appstate "github.com/tylergannon/skgo/example/internal/app"
	hooks "github.com/tylergannon/skgo/example/web/src"
)

// RouteParams stores converted values; only accessors record load dependencies.
type RouteParams struct {
	event *skgo.Event
}
type PageRequestEvent = skgo.RequestEvent[RouteParams, appstate.Locals]

func SkgoPageRequestEvent(event *skgo.Event) PageRequestEvent {
	return PageRequestEvent{Event: event, Locals: appstate.LocalsFrom(event.Request().Context()), Params: skgoRouteParams(event)}
}
func skgoRouteParams(event *skgo.Event) RouteParams {
	p := RouteParams{event: event}

	return p
}
func SkgoParamMatchers() map[string]skgo.ParamMatcher {
	return map[string]skgo.ParamMatcher{
		"Order": func(value string) (any, bool) { return hooks.Order(value) },
	}
}

// The functions this package declares, published under names the generated
// bindings package can spell. Each is the function itself and not a wrapper:
// skgo.Refresh finds a query by the code pointer of the function it names.
var (
	// Skgo_getPlans is getPlans, published as src/routes/(marketing)/pricing/pricing.remote.ts#getPlans.
	Skgo_getPlans = getPlans
	// Skgo_getSpotlight is getSpotlight, published as src/routes/(marketing)/pricing/pricing.remote.ts#getSpotlight.
	Skgo_getSpotlight = getSpotlight
	// Skgo_quoteFor is quoteFor, published as src/routes/(marketing)/pricing/pricing.remote.ts#quoteFor.
	Skgo_quoteFor = quoteFor
	// Skgo_pageLoad is pageLoad, published as the server load of src/routes/(marketing)/pricing/+page.server.ts.
	Skgo_pageLoad = pageLoad
)
