// Code generated by polytype. DO NOT EDIT.

/**
 * Plan is one row of the pricing table.
 */
export type Plan = {
  /**
   * Name is the plan's name.
   */
  "name": string;
  /**
   * Price is what it costs per month, in whole dollars.
   */
  "price": number;
};
