import { readFileSync } from 'node:fs';
import { createRequire } from 'node:module';
import { join, relative } from 'node:path';
import { pathToFileURL } from 'node:url';
import { validateGenerated } from './generated.js';

// Use the parser shipped with the application's Vite, as the goja environment
// does. Parsing the original TS/JS declarations preserves Kit's native wrappers,
// actions, types and module identities; only build callback bodies change.
const app = createRequire(join(process.cwd(), 'package.json'));
const { parseSync } = await import(pathToFileURL(app.resolve('vite/rolldown/experimental')).href);
const header = '// Code generated by skgo. DO NOT EDIT.';
const helper = '@skgo/sveltekit-adapter/prerender';

export function prerenderModules() {
	let root;
	let generated;
	return {
		name: 'skgo-prerender-modules',
		apply: 'build',
		applyToEnvironment: (environment) => environment.name === 'ssr',
		configResolved(config) { root = config.root; },
		buildStart() {
			generated = validateGenerated(JSON.parse(readFileSync(join(root, 'skgo.remotes.json'), 'utf8')));
			if (!generated.build || typeof generated.build !== 'object' || Array.isArray(generated.build)) {
				throw new Error('skgo: missing build declarations; run `go generate ./...`.');
			}
			for (const [module, declaration] of Object.entries(generated.build)) {
				if (!module.startsWith('src/') || module.split('/').some((part) => part === '.' || part === '..') || !/\.(ts|js)$/.test(module) || !declaration || typeof declaration !== 'object' || Array.isArray(declaration)) {
					throw new Error(`skgo: malformed build declaration for ${module}; run \`go generate ./...\`.`);
				}
				const fields = Object.keys(declaration);
				if (fields.length !== 1 || !['source', 'remotes', 'endpoint', 'hook'].includes(fields[0]) ||
					('source' in declaration && (typeof declaration.source !== 'string' || !declaration.source)) ||
					('remotes' in declaration && (!Array.isArray(declaration.remotes) || !declaration.remotes.length)) ||
					('endpoint' in declaration && declaration.endpoint !== true) ||
					('hook' in declaration && declaration.hook !== true)) {
					throw new Error(`skgo: malformed build declaration for ${module}; run \`go generate ./...\`.`);
				}
			}
			for (const module of generated.loads) {
				if (typeof generated.build[module]?.source !== 'string' || !generated.build[module].source) {
					throw new Error(`skgo: missing Go load source for ${module}; run \`go generate ./...\`.`);
				}
			}
		},
		load(id) {
			const module = relative(root, id).split('\\').join('/');
			if (!/\.(ts|js)$/.test(module)) return;
			const declaration = generated.build[module];
			// Inspect server declarations even without metadata, so a missing
			// entry cannot quietly execute a generated throwing stub at build time.
			if (!declaration && !/(\.remote|\/\+(page|layout)\.server|\/\+server|\/hooks\.server)\.(ts|js)$/.test(module)) return;
			const code = readFileSync(id, 'utf8');
			if (!code.startsWith(header)) {
				if (declaration) throw new Error(`skgo: build declaration for authored module ${module}`);
				return;
			}
			const parsed = parseSync(id, code);
			if (parsed.errors.length) throw new Error(`skgo: cannot parse generated module ${module}`);
			const exports = new Map();
			for (const node of parsed.program.body) {
				if (node.type !== 'ExportNamedDeclaration' || node.exportKind === 'type') continue;
				for (const item of node.declaration?.declarations ?? []) exports.set(item.id.name, item.init);
			}
			const fail = () => { throw new Error(`skgo: build declarations disagree with ${module}; run \`go generate ./...\`.`); };
			const edits = [];
			let imports = '';
			if (exports.has('load')) {
				if (!declaration?.source || !generated.loads.includes(module)) fail();
				const fn = exports.get('load');
				if (fn?.type !== 'ArrowFunctionExpression' || fn.params.length !== 1) fail();
				const event = fn.params[0].name;
				imports += "import { error as $skgoError, redirect as $skgoRedirect } from '@sveltejs/kit';\n";
				edits.push([fn.body.start, fn.body.end, `{
	const bridge = ${event}.platform?.skgoPrerenderLoad;
	if (!bridge) throw new Error('skgo: prerender Go load bridge unavailable');
	const answer = await bridge(${JSON.stringify(module)}, ${JSON.stringify(declaration.source)}, ${event});
	if (answer.redirect) $skgoRedirect(answer.redirect.status, answer.redirect.location);
	if (answer.error) $skgoError(answer.error.status, answer.error.message);
	if (answer.data === undefined) throw new Error('skgo: prerender Go load returned no data');
	return answer.data;
}`]);
			} else if (declaration?.source) fail();
			if (/\/\+server\.(ts|js)$/.test(module)) {
				if (declaration?.endpoint !== true) fail();
				for (const fn of exports.values()) {
					if (!fn) fail();
					edits.push([fn.start, fn.end, `(event) => {
	const bridge = event.platform?.skgoPrerenderEndpoint;
	if (!bridge) throw new Error('skgo: prerender Go endpoint bridge unavailable');
	return bridge(event);
}`]);
				}
			}
			const remotes = declaration?.remotes ?? [];
			if (!Array.isArray(remotes)) fail();
			const prerenders = [...exports].filter(([, fn]) => fn?.type === 'CallExpression' && fn.callee.name === 'prerender');
			if (prerenders.length !== remotes.length) fail();
			if (remotes.length) imports += "import { getRequestEvent as $skgoEvent } from '$app/server';\n";
			if (remotes.some((fn) => fn.inputs)) imports += `import { remoteInputs as $skgoInputs } from '${helper}';\n`;
			const seen = new Set();
			for (const remote of remotes) {
				const call = exports.get(remote.name);
				if (seen.has(remote.name) || typeof remote.argument !== 'boolean' || typeof remote.inputs !== 'boolean' || call?.callee.name !== 'prerender') fail();
				seen.add(remote.name);
				const callback = call.arguments[remote.argument ? 1 : 0];
				if (call.arguments.length !== (remote.argument ? 2 : 1) || callback?.type !== 'ArrowFunctionExpression' || callback.params.length !== (remote.argument ? 1 : 0)) fail();
				const arg = remote.argument ? callback.params[0].name : 'undefined';
				edits.push([callback.body.start, callback.body.end, `{
	const event = $skgoEvent();
	const bridge = event.platform?.skgoPrerenderRemote;
	if (!bridge) throw new Error('skgo: prerender Go remote bridge unavailable');
	return bridge(${JSON.stringify(module)}, ${JSON.stringify(remote.name)}, ${arg}, event);
}`]);
				if (remote.inputs) edits.push([callback.end, callback.end, `, { inputs: () => $skgoInputs(${JSON.stringify(module)}, ${JSON.stringify(remote.name)}) }`]);
			}
			if (/\/hooks\.server\.(ts|js)$/.test(module)) {
				if (declaration?.hook !== true || exports.has('handle') || exports.has('handleFetch')) fail();
				return `import { requestHandle, requestFetch } from '${helper}';
${code}
export const handle = ({ event, resolve }) => requestHandle(event, resolve);
export const handleFetch = (input) => requestFetch(input);
`;
			}
			if (!edits.length) return;
			let result = code;
			for (const [start, end, replacement] of edits.sort((a, b) => b[0] - a[0])) {
				result = result.slice(0, start) + replacement + result.slice(end);
			}
			return imports + result;
		}
	};
}
