// Code generated by skgo. DO NOT EDIT.

package stream

import skgo "github.com/tylergannon/skgo"

import (
	hooks "github.com/tylergannon/skgo/example/web/src"
)

// RouteParams stores converted values. Only accessor reads record dependencies
// on the load invocation that constructed these params.
type RouteParams struct {
	event *skgo.Event
}

type RequestEvent = skgo.RequestEvent[RouteParams]

func SkgoRequestEvent(event *skgo.Event) RequestEvent {
	return RequestEvent{Event: event, Params: RouteParams{event: event}}
}

func SkgoParamMatchers() map[string]skgo.ParamMatcher {
	return map[string]skgo.ParamMatcher{
		"Order": func(value string) (any, bool) { return hooks.Order(value) },
	}
}
