// Code generated by polytype. DO NOT EDIT.

/**
 * Session says who is signed in. An empty User means nobody.
 */
export type Session = {
  /**
   * User is the signed-in visitor's name, or "" when signed out.
   */
  "user": string;
};

/**
 * Todo is one item in the list.
 */
export type Todo = {
  /**
   * ID is the stable identifier the todo is addressed by.
   */
  "id": string;
  /**
   * Text is what the visitor typed.
   */
  "text": string;
  /**
   * Private reports that only a signed-in visitor may see this todo.
   */
  "private": boolean;
};
