//go:build jsonschema

// Code generated by skgo. DO NOT EDIT.

package businesslogic

import (
	"encoding/json"

	"github.com/tylergannon/polytype"
)

// Stubs so the package compiles before polytype has run.
func (Session) Schema() json.RawMessage { panic("not implemented") }
func (Todo) Schema() json.RawMessage    { panic("not implemented") }

var (
	_ = polytype.Declare(Session.Schema)
	_ = polytype.Declare(Todo.Schema)
)
