// Code generated by skgo. DO NOT EDIT.
import { command, query } from '$app/server';
import type { Report } from './types';

export type { Report };

// Every body throws. These functions are implemented in Go, and skgo
// answers their endpoints itself, so anything that renders in the browser
// is proof the Go handler replied rather than this module.
const unimplemented = (): never => {
	throw new Error('skgo: implemented in Go');
};

export const getKnownReport = query((): Report => unimplemented());

export const getModels = query((): Array<string> => unimplemented());

export const getReport = query((): Report => unimplemented());

export const reparse = command((): Report => unimplemented());
