// Code generated by skgo. DO NOT EDIT.

package empty

// The functions this package declares, published under names the generated
// bindings package can spell. Each is the function itself and not a wrapper:
// skgo.Refresh finds a query by the code pointer of the function it names.
var (
	// Skgo_getKnownReport is getKnownReport, published as src/routes/empty/empty.remote.ts#getKnownReport.
	Skgo_getKnownReport = getKnownReport
	// Skgo_getModels is getModels, published as src/routes/empty/empty.remote.ts#getModels.
	Skgo_getModels = getModels
	// Skgo_getReport is getReport, published as src/routes/empty/empty.remote.ts#getReport.
	Skgo_getReport = getReport
	// Skgo_reparse is reparse, published as src/routes/empty/empty.remote.ts#reparse.
	Skgo_reparse = reparse
	// Skgo_pageLoad is pageLoad, published as the server load of src/routes/empty/+page.server.ts.
	Skgo_pageLoad = pageLoad
)
