// Code generated by skgo. DO NOT EDIT.

package empty

import "github.com/tylergannon/skgo"

// SkgoRemotes returns the remote functions declared in this package.
func SkgoRemotes() []*skgo.Remote {
	return []*skgo.Remote{
		skgo.NewQueryNoArg("src/routes/empty/empty.remote.ts", "getKnownReport", getKnownReport),
		skgo.NewQueryNoArg("src/routes/empty/empty.remote.ts", "getModels", getModels),
		skgo.NewQueryNoArg("src/routes/empty/empty.remote.ts", "getReport", getReport),
		skgo.NewCommandNoArg("src/routes/empty/empty.remote.ts", "reparse", reparse),
	}
}

// SkgoLoads returns the server loads declared in this package.
func SkgoLoads() []*skgo.ServerLoad {
	return []*skgo.ServerLoad{
		skgo.NewLoad("src/routes/empty/+page.server.ts", pageLoad),
	}
}

// SkgoEndpoints returns the server routes declared in this package.
func SkgoEndpoints() []*skgo.Endpoint {
	return []*skgo.Endpoint{}
}
