// Code generated by skgo. DO NOT EDIT.

package empty

import (
	skgo "github.com/tylergannon/skgo"
	appstate "github.com/tylergannon/skgo/example/internal/app"
	hooks "github.com/tylergannon/skgo/example/web/src"
)

// RouteParams stores converted values. Only accessor reads record dependencies
// on the load invocation that constructed these params.
type RouteParams struct {
	event *skgo.Event
}

type RequestEvent = skgo.RequestEvent[RouteParams, appstate.Locals]

func SkgoRequestEvent(event *skgo.Event) RequestEvent {
	return RequestEvent{Event: event, Locals: appstate.LocalsFrom(event.Request().Context()), Params: RouteParams{event: event}}
}

func SkgoParamMatchers() map[string]skgo.ParamMatcher {
	return map[string]skgo.ParamMatcher{
		"Order": func(value string) (any, bool) { return hooks.Order(value) },
	}
}

// The functions this package declares, published under names the generated
// bindings package can spell. Each is the function itself and not a wrapper:
// skgo.Refresh finds a query by the code pointer of the function it names.
var (
	// Skgo_getKnownReport is getKnownReport, published as src/routes/empty/empty.remote.ts#getKnownReport.
	Skgo_getKnownReport = getKnownReport
	// Skgo_getModels is getModels, published as src/routes/empty/empty.remote.ts#getModels.
	Skgo_getModels = getModels
	// Skgo_getReport is getReport, published as src/routes/empty/empty.remote.ts#getReport.
	Skgo_getReport = getReport
	// Skgo_reparse is reparse, published as src/routes/empty/empty.remote.ts#reparse.
	Skgo_reparse = reparse
	// Skgo_pageLoad is pageLoad, published as the server load of src/routes/empty/+page.server.ts.
	Skgo_pageLoad = pageLoad
)
