// Code generated by polytype. DO NOT EDIT.

/**
 * Report is what a parse produced. Both slices are `Array<...>` in the generated TypeScript and neither is optional, so neither may be null on the wire.
 */
export type Report = {
  /**
   * Title says what happened.
   */
  "title": string;
  /**
   * Diagnostics is what the parser complained about.
   */
  "diagnostics": Array<Diagnostic>;
  /**
   * Models is what it resolved.
   */
  "models": Array<string>;
};

/**
 * Diagnostic is one thing the parser had to say.
 */
export type Diagnostic = {
  /**
   * Message is the complaint, in the parser's own words.
   */
  "message": string;
};
