// Code generated by skgo. DO NOT EDIT.

package typeddependencies

import skgo "github.com/tylergannon/skgo"

import (
	hooks "github.com/tylergannon/skgo/example/web/src"
)

// RouteParams stores converted values. Only accessor reads record dependencies
// on the load invocation that constructed these params.
type RouteParams struct {
	event        *skgo.Event
	valueA       hooks.OrderNumber
	valueB       hooks.OrderNumber
	valueIgnored string
}

func (p RouteParams) A() hooks.OrderNumber { skgo.TrackLoadParam(p.event, "a"); return p.valueA }

func (p RouteParams) B() hooks.OrderNumber { skgo.TrackLoadParam(p.event, "b"); return p.valueB }

func (p RouteParams) Ignored() string { skgo.TrackLoadParam(p.event, "ignored"); return p.valueIgnored }

type RequestEvent = skgo.RequestEvent[RouteParams]

func SkgoRequestEvent(event *skgo.Event) RequestEvent {
	return RequestEvent{Event: event, Params: RouteParams{event: event,
		valueA:       skgo.LoadParamValue[hooks.OrderNumber](event, "a"),
		valueB:       skgo.LoadParamValue[hooks.OrderNumber](event, "b"),
		valueIgnored: skgo.LoadParamValue[string](event, "ignored"),
	}}
}

func SkgoParamMatchers() map[string]skgo.ParamMatcher {
	return map[string]skgo.ParamMatcher{
		"Order": func(value string) (any, bool) { return hooks.Order(value) },
	}
}
