// Code generated by skgo. DO NOT EDIT.
import type { RequestEvent } from "@sveltejs/kit";
import type { Answer } from "./types";

export const load = async (event: RequestEvent): Promise<{ answers: Array<Answer> }> => {
  throw new Error("skgo: implemented in Go");
};
