// Code generated by polytype. DO NOT EDIT.

/**
 * Answer is what one fetch came back with, untouched.
 */
export type Answer = {
  path: string;
  status: number;
  contentType: string;
  body: string;
};
