// Code generated by skgo. DO NOT EDIT.

package ssrcontrol

// The functions this package declares, published under names the generated
// bindings package can spell. Each is the function itself and not a wrapper:
// skgo.Refresh finds a query by the code pointer of the function it names.
var (
	// Skgo_status is status, published as GET /async-ssr/control/[group].
	Skgo_status = status
	// Skgo_release is release, published as POST /async-ssr/control/[group].
	Skgo_release = release
)
