// Code generated by skgo. DO NOT EDIT.

package replayapi

// The functions this package declares, published under names the generated
// bindings package can spell. Each is the function itself and not a wrapper:
// skgo.Refresh finds a query by the code pointer of the function it names.
var (
	// Skgo_get is get, published as GET /api/replay/[kind].
	Skgo_get = get
	// Skgo_post is post, published as POST /api/replay/[kind].
	Skgo_post = post
)
