// Code generated by skgo. DO NOT EDIT.
import { command, query } from '$app/server';
import type { Session } from './skgo/businesslogic/types';

export type { Session };

// Every body throws. These functions are implemented in Go, and skgo
// answers their endpoints itself, so anything that renders in the browser
// is proof the Go handler replied rather than this module.
const unimplemented = (): never => {
	throw new Error('skgo: implemented in Go');
};

export const signIn = command('unchecked', (_arg: string): Session => unimplemented());

export const signOut = command((): Session => unimplemented());

export const whoami = query((): Session => unimplemented());
