// Code generated by skgo. DO NOT EDIT.

package lib

import "github.com/tylergannon/skgo"

// SkgoRemotes returns the remote functions declared in this package.
func SkgoRemotes() []*skgo.Remote {
	return []*skgo.Remote{
		skgo.NewCommand("src/lib/auth.remote.ts", "signIn", signIn),
		skgo.NewCommand("src/lib/auth.remote.ts", "signOut", signOut),
		skgo.NewQuery("src/lib/auth.remote.ts", "whoami", whoami),
	}
}
