// Code generated by skgo. DO NOT EDIT.

package lib

// The functions this package declares, published under names the generated
// bindings package can spell. Each is the function itself and not a wrapper:
// skgo.Refresh finds a query by the code pointer of the function it names.
var (
	// Skgo_signIn is signIn, published as src/lib/auth.remote.ts#signIn.
	Skgo_signIn = signIn
	// Skgo_signOut is signOut, published as src/lib/auth.remote.ts#signOut.
	Skgo_signOut = signOut
	// Skgo_whoami is whoami, published as src/lib/auth.remote.ts#whoami.
	Skgo_whoami = whoami
)
