const std = @import("std");
const core = @import("root.zig");
const d = core.devalue;
const a = std.testing.allocator;

// Recorded from installed Kit 3.0.0 runtime/shared.js and devalue 5.9.4,
// with native JS views and empty transport hooks. Never generated by this core.
// JS input: Uint8Array.from(the literal bytes in binaryGraph).buffer; view and
// again reference one Uint8Array(buffer, 1, 3); equal is a distinct such view.
// data is DataView(buffer, 2, 4); empty/emptyView share an empty ArrayBuffer;
// separateEmpty is distinct; kinds contains new T(buffer, T.BYTES_PER_ELEMENT, 1)
// for each of the twelve constructors below; self references the root object.
// The reply uses the same shape with the literal response bytes asserted below.
const Fixture = struct { kit: []const u8, devalue: []const u8, input: []const u8, query: []const u8, command: []const u8, result: []const u8, envelope: []const u8 };
const kinds = [_]d.TypedArrayKind{ .Int8Array, .Uint8Array, .Uint8ClampedArray, .Int16Array, .Uint16Array, .Float16Array, .Int32Array, .Uint32Array, .Float32Array, .Float64Array, .BigInt64Array, .BigUint64Array };

fn binaryGraph(graph: *d.Graph) !d.Value {
    const buffer = try graph.arrayBuffer(&.{ 0, 255, 1, 128, 254, 127, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11 });
    const view = try graph.typedArray(.Uint8Array, buffer, 1, 3);
    const empty = try graph.arrayBuffer(&.{});
    const root = try graph.object(false);
    try graph.put(root, "view", view);
    try graph.put(root, "again", view);
    try graph.put(root, "equal", try graph.typedArray(.Uint8Array, buffer, 1, 3));
    try graph.put(root, "data", try graph.dataView(buffer, 2, 4));
    try graph.put(root, "buffer", buffer);
    try graph.put(root, "empty", empty);
    try graph.put(root, "emptyView", try graph.typedArray(.Uint8Array, empty, 0, 0));
    try graph.put(root, "separateEmpty", try graph.arrayBuffer(&.{}));
    const all = try graph.array(12);
    for (kinds, 0..) |kind, i| try graph.arrayPut(all, @intCast(i), try graph.typedArray(kind, buffer, kind.bytesPerElement(), 1));
    try graph.put(root, "kinds", all);
    try graph.put(root, "self", root);
    return root;
}

test "binary query and command arguments match pinned Kit bytes" {
    const fixture = try std.json.parseFromSlice(Fixture, a, @embedFile("kit-binary.json"), .{});
    defer fixture.deinit();
    try std.testing.expectEqualStrings("3.0.0", fixture.value.kit);
    try std.testing.expectEqualStrings(d.upstream_version, fixture.value.devalue);
    for ([_]core.Kind{ .query, .command }) |kind| {
        var graph = d.Graph.init(a);
        defer graph.deinit();
        const arg = try binaryGraph(&graph);
        const input = try d.stringify(a, &graph, arg, &.{});
        defer a.free(input);
        try std.testing.expectEqualStrings(fixture.value.input, input);
        var request = try core.prepare(a, .{ .origin = "http://127.0.0.1:8080", .base = "/native" }, "hash/exchange", kind, &graph, arg, &.{});
        defer request.deinit();
        try std.testing.expectEqualStrings(if (kind == .query) fixture.value.query else fixture.value.command, request.payload);
    }
}

test "binary remote response owns bytes, views, shared identity and cycles" {
    const fixture = try std.json.parseFromSlice(Fixture, a, @embedFile("kit-binary.json"), .{});
    defer fixture.deinit();
    const bytes = try a.dupe(u8, fixture.value.envelope);
    var response = try core.receive(a, 200, bytes);
    a.free(bytes);
    defer response.deinit();
    try std.testing.expectEqual(.result, response.kind);
    const graph = &response.parsed.?.graph;
    const root = response.value;
    const buffer = (try graph.get(root, "buffer")).?;
    try std.testing.expectEqualSlices(u8, &.{ 11, 10, 9, 8, 7, 6, 5, 4, 3, 2, 1, 0, 128, 254, 255, 0 }, (try graph.node(buffer)).array_buffer);
    const view = (try graph.get(root, "view")).?;
    try std.testing.expect(d.equal(view, (try graph.get(root, "again")).?));
    const equal = (try graph.get(root, "equal")).?;
    try std.testing.expect(!d.equal(view, equal));
    for ([_]d.Value{ view, equal }) |v| {
        const node = (try graph.node(v)).typed_array;
        try std.testing.expectEqual(.Uint8Array, node.kind);
        try std.testing.expectEqual(@as(usize, 1), node.byte_offset);
        try std.testing.expectEqual(@as(usize, 3), node.length);
        try std.testing.expect(d.equal(buffer, node.buffer));
        try std.testing.expectEqualSlices(u8, &.{ 10, 9, 8 }, try graph.viewBytes(v));
    }
    const data = (try graph.get(root, "data")).?;
    const data_node = (try graph.node(data)).data_view;
    try std.testing.expectEqual(@as(usize, 2), data_node.byte_offset);
    try std.testing.expectEqual(@as(usize, 4), data_node.byte_length);
    try std.testing.expect(d.equal(buffer, data_node.buffer));
    try std.testing.expectEqualSlices(u8, &.{ 9, 8, 7, 6 }, try graph.viewBytes(data));
    const empty = (try graph.get(root, "empty")).?;
    const separate = (try graph.get(root, "separateEmpty")).?;
    try std.testing.expect(!d.equal(empty, separate));
    try std.testing.expectEqual(@as(usize, 0), (try graph.node(empty)).array_buffer.len);
    try std.testing.expectEqual(@as(usize, 0), (try graph.node(separate)).array_buffer.len);
    const empty_view = (try graph.get(root, "emptyView")).?;
    const empty_node = (try graph.node(empty_view)).typed_array;
    try std.testing.expect(d.equal(empty, empty_node.buffer));
    try std.testing.expectEqual(.Uint8Array, empty_node.kind);
    try std.testing.expectEqual(@as(usize, 0), empty_node.byte_offset);
    try std.testing.expectEqual(@as(usize, 0), empty_node.length);
    try std.testing.expect(d.equal(root, (try graph.get(root, "self")).?));
    const all = (try graph.get(root, "kinds")).?;
    try std.testing.expectEqual(@as(u32, 12), (try graph.node(all)).array.length);
    for (kinds, 0..) |kind, i| {
        const v = (try graph.arrayGet(all, @intCast(i))).?;
        const node = (try graph.node(v)).typed_array;
        try std.testing.expectEqual(kind, node.kind);
        try std.testing.expectEqual(kind.bytesPerElement(), node.byte_offset);
        try std.testing.expectEqual(@as(usize, 1), node.length);
        try std.testing.expect(d.equal(buffer, node.buffer));
    }
}

fn allocationCase(allocator: std.mem.Allocator, envelope: []const u8) !void {
    var graph = d.Graph.init(allocator);
    defer graph.deinit();
    const arg = try binaryGraph(&graph);
    for ([_]core.Kind{ .query, .command }) |kind| {
        var request = try core.prepare(allocator, .{ .origin = "http://127.0.0.1:8080" }, "hash/exchange", kind, &graph, arg, &.{});
        defer request.deinit();
    }
    var response = try core.receive(allocator, 200, envelope);
    defer response.deinit();
}

test "binary request and response allocation failures release ownership" {
    const fixture = try std.json.parseFromSlice(Fixture, a, @embedFile("kit-binary.json"), .{});
    defer fixture.deinit();
    var no_growth = std.testing.FailingAllocator.init(a, .{ .resize_fail_index = 0 });
    try std.testing.checkAllAllocationFailures(no_growth.allocator(), allocationCase, .{fixture.value.envelope});
}
