// Code generated by skgo. DO NOT EDIT.

package actions

// The functions this package declares, published under names the generated
// bindings package can spell. Each is the function itself and not a wrapper:
// skgo.Refresh finds a query by the code pointer of the function it names.
var (
	// Skgo_sendRemoteNote is sendRemoteNote, published as src/routes/actions/coexist.remote.ts#sendRemoteNote.
	Skgo_sendRemoteNote = sendRemoteNote
	// Skgo_pageLoad is pageLoad, published as the server load of src/routes/actions/+page.server.ts.
	Skgo_pageLoad    = pageLoad
	Skgo_archive     = archive
	Skgo_forbidden   = forbidden
	Skgo_inspect     = inspect
	Skgo_remember    = remember
	Skgo_remote      = remote
	Skgo_save        = save
	Skgo_signIn      = signIn
	Skgo_unavailable = unavailable
	Skgo_upload      = upload
	// Skgo_endpointPost is endpointPost, published as POST /actions.
	Skgo_endpointPost = endpointPost
)

type (
	// SkgoArg_sendRemoteNote is the type sendRemoteNote takes.
	SkgoArg_sendRemoteNote = RemoteNote
	// SkgoOut_sendRemoteNote is the type sendRemoteNote returns.
	SkgoOut_sendRemoteNote = RemoteReceipt
)
