// Code generated by skgo. DO NOT EDIT.

package batch

// The functions this package declares, published under names the generated
// bindings package can spell. Each is the function itself and not a wrapper:
// skgo.Refresh finds a query by the code pointer of the function it names.
var (
	// Skgo_getQuotes is getQuotes, published as src/routes/batch/quotes.remote.ts#getQuotes.
	Skgo_getQuotes = getQuotes
)

type (
	// SkgoArg_getQuotes is the type getQuotes takes.
	SkgoArg_getQuotes = string
)
