// Code generated by skgo. DO NOT EDIT.
import { form, query } from '$app/server';
import type { Message, Receipt } from './types';

export type { Message, Receipt };

// Every body throws. These functions are implemented in Go, and skgo
// answers their endpoints itself, so anything that renders in the browser
// is proof the Go handler replied rather than this module.
const unimplemented = (): never => {
	throw new Error('skgo: implemented in Go');
};

export const getMessages = query((): Array<Message> => unimplemented());

export const sendMessage = form('unchecked', (_arg: { from: string; email: string; body: string; attachment?: File }): Receipt => unimplemented());
