//go:build jsonschema

// Code generated by skgo. DO NOT EDIT.

package contact

import (
	"encoding/json"

	"github.com/tylergannon/polytype"
)

// Stubs so the package compiles before polytype has run.
func (Message) Schema() json.RawMessage { panic("not implemented") }
func (Receipt) Schema() json.RawMessage { panic("not implemented") }

var (
	_ = polytype.Declare(Message.Schema)
	_ = polytype.Declare(Receipt.Schema)
)
