// Code generated by skgo. DO NOT EDIT.

package contact

import "github.com/tylergannon/skgo"

// SkgoRemotes returns the remote functions declared in this package.
func SkgoRemotes() []*skgo.Remote {
	return []*skgo.Remote{
		skgo.NewQuery("src/routes/contact/contact.remote.ts", "getMessages", getMessages),
		skgo.NewForm("src/routes/contact/contact.remote.ts", "sendMessage", sendMessage),
	}
}

// SkgoLoads returns the server loads declared in this package.
func SkgoLoads() []*skgo.ServerLoad {
	return []*skgo.ServerLoad{}
}
