// Code generated by skgo. DO NOT EDIT.

package contact

// The functions this package declares, published under names the generated
// bindings package can spell. Each is the function itself and not a wrapper:
// skgo.Refresh finds a query by the code pointer of the function it names.
var (
	// Skgo_getMessages is getMessages, published as src/routes/contact/contact.remote.ts#getMessages.
	Skgo_getMessages = getMessages
	// Skgo_sendMessage is sendMessage, published as src/routes/contact/contact.remote.ts#sendMessage.
	Skgo_sendMessage = sendMessage
)

type (
	// SkgoArg_sendMessage is the type sendMessage takes.
	SkgoArg_sendMessage = Draft
)
