// Code generated by polytype. DO NOT EDIT.

/**
 * Message is one message the visitor has sent, as the page lists it.
 */
export type Message = {
  /**
   * ID is the message's number in the order it arrived.
   */
  "id": string;
  /**
   * From is the sender's name.
   */
  "from": string;
  /**
   * Email is the address they gave.
   */
  "email": string;
  /**
   * Body is what they wrote.
   */
  "body": string;
  /**
   * Attachment is the uploaded file's name, or empty when there was none.
   */
  "attachment": string;
  /**
   * AttachmentBytes is how many bytes of it reached Go.
   */
  "attachmentBytes": number;
  /**
   * AttachmentDigest is the first twelve hex digits of the SHA-256 of those bytes. It is on the page because a byte count alone cannot tell an upload that arrived from one that arrived scrambled — the digest changes if a single byte moved, which is exactly the failure kit's smallest-file-first body ordering invites.
   */
  "attachmentDigest": string;
};

/**
 * Receipt is what a successful submission returns, which kit's client puts on `sendMessage.result`.
 */
export type Receipt = {
  /**
   * ID is the new message's id.
   */
  "id": string;
  /**
   * Summary is a sentence the page can show without re-reading the list.
   */
  "summary": string;
};
