// Code generated by polytype. DO NOT EDIT.

package client

import (
	"encoding/json"
	"fmt"
	"math"
	"slices"
	"strconv"
	"time"

	devalue "github.com/tylergannon/polytype/devalue"
	pkg_onzggl3sn52xizltf5qwg5djn5xhg "github.com/tylergannon/skgo/example/internal/skgo/links/onzggl3sn52xizltf5qwg5djn5xhg"
	pkg_onzggl3sn52xizltf5xxa5djn5xgc3a "github.com/tylergannon/skgo/example/internal/skgo/links/onzggl3sn52xizltf5xxa5djn5xgc3a"
)

// dvAt renders a JSON-pointer-style path for a diagnostic. The root value has
// the empty path, which is spelled "/" so a message never starts with ": ".
func dvAt(at string) string {
	if at == "" {
		return "/"
	}
	return at
}

func dvErr(at string, format string, args ...any) error {
	return fmt.Errorf("%s: %s", dvAt(at), fmt.Sprintf(format, args...))
}

// dvKind names the devalue value model kind of v for wrong-kind diagnostics.
// Every tagged form is named so a rejected Date or Map says which one it was.
func dvKind(v any) string {
	switch v.(type) {
	case nil:
		return "null"
	case devalue.UndefinedValue:
		return "undefined"
	case devalue.HoleValue:
		return "a sparse-array hole"
	case bool:
		return "a boolean"
	case float64:
		return "a number"
	case string:
		return "a string"
	case []any:
		return "an array"
	case *devalue.Object:
		return "an object"
	case devalue.Date:
		return "a Date"
	case *devalue.Map:
		return "a Map"
	case *devalue.Set:
		return "a Set"
	case devalue.BigInt:
		return "a BigInt"
	case devalue.RegExp:
		return "a RegExp"
	case devalue.ArrayBuffer:
		return "an ArrayBuffer"
	case *devalue.Boxed:
		return "a boxed primitive"
	default:
		return fmt.Sprintf("a value of type %T", v)
	}
}

func dvBool(raw any, at string) (bool, error) {
	v, ok := raw.(bool)
	if !ok {
		return false, dvErr(at, "expected a boolean, got %s", dvKind(raw))
	}
	return v, nil
}

func dvString(raw any, at string) (string, error) {
	v, ok := raw.(string)
	if !ok {
		return "", dvErr(at, "expected a string, got %s", dvKind(raw))
	}
	return v, nil
}

func dvNumber(raw any, at string) (float64, error) {
	v, ok := raw.(float64)
	if !ok {
		return 0, dvErr(at, "expected a number, got %s", dvKind(raw))
	}
	return v, nil
}

// dvFloat32 narrows a wire number, refusing values outside float32's range so
// a decode never silently yields an infinity.
func dvFloat32(raw any, at string) (float32, error) {
	v, err := dvNumber(raw, at)
	if err != nil {
		return 0, err
	}
	if !math.IsInf(v, 0) && !math.IsNaN(v) && math.Abs(v) > math.MaxFloat32 {
		return 0, dvErr(at, "number %v is out of range for float32", v)
	}
	return float32(v), nil
}

// dvInteger admits only integral numbers inside [min, max]. The bounds are
// float64 because every wire number is one; kinds wider than 2^53 are checked
// against the rounded bound, which is the same precision the encoder has.
func dvInteger(raw any, at string, min, max float64) (float64, error) {
	v, err := dvNumber(raw, at)
	if err != nil {
		return 0, err
	}
	if math.IsInf(v, 0) || math.IsNaN(v) || v != math.Trunc(v) {
		return 0, dvErr(at, "expected an integer, got %v", v)
	}
	if v < min || v > max {
		return 0, dvErr(at, "number %v is out of range", v)
	}
	return v, nil
}

func dvArray(raw any, at string) ([]any, error) {
	v, ok := raw.([]any)
	if !ok {
		return nil, dvErr(at, "expected an array, got %s", dvKind(raw))
	}
	for i, item := range v {
		if _, hole := item.(devalue.HoleValue); hole {
			return nil, dvErr(at+"/"+strconv.Itoa(i), "array element is a hole")
		}
	}
	return v, nil
}

func dvObject(raw any, at string) (*devalue.Object, error) {
	v, ok := raw.(*devalue.Object)
	if !ok {
		return nil, dvErr(at, "expected an object, got %s", dvKind(raw))
	}
	return v, nil
}

func dvKnown(o *devalue.Object, at string, known ...string) error {
	for _, key := range o.Keys() {
		if !slices.Contains(known, key) {
			return dvErr(at, "unknown property %q", key)
		}
	}
	return nil
}

// dvRequired reads a property that must be present and must not be undefined.
// at is the property's own path, so the diagnostic points at the value.
func dvRequired(o *devalue.Object, key string, at string) (any, error) {
	v, ok := o.Get(key)
	if !ok {
		return nil, dvErr(at, "missing required property %q", key)
	}
	if _, undefined := v.(devalue.UndefinedValue); undefined {
		return nil, dvErr(at, "value is undefined")
	}
	return v, nil
}

// dvPresent reads an optional property. It reports absence, and rejects an
// explicit undefined, which is not the same thing on this wire.
func dvPresent(o *devalue.Object, key string, at string) (any, bool, error) {
	v, ok := o.Get(key)
	if !ok {
		return nil, false, nil
	}
	if _, undefined := v.(devalue.UndefinedValue); undefined {
		return nil, false, dvErr(at, "value is undefined")
	}
	return v, true, nil
}

// dvWithout copies o omitting key, so a union payload decoder does not see the
// discriminator it never declared as a field.
func dvWithout(o *devalue.Object, key string) *devalue.Object {
	out := devalue.NewObject()
	for _, k := range o.Keys() {
		if k == key {
			continue
		}
		v, _ := o.Get(k)
		out.Set(k, v)
	}
	return out
}

// dvTagged rebuilds a union payload with the discriminator first, leaving any
// discriminator the payload itself carried out of the result.
func dvTagged(payload any, discriminator string, tag string, at string) (any, error) {
	o, err := dvObject(payload, at)
	if err != nil {
		return nil, err
	}
	out := devalue.NewObject()
	out.Set(discriminator, tag)
	for _, k := range o.Keys() {
		if k == discriminator {
			continue
		}
		v, _ := o.Get(k)
		out.Set(k, v)
	}
	return out, nil
}

// dvEncodeTime and dvDecodeTime use time.Time's own JSON methods, so the wire
// string is exactly the one encoding/json would produce and accept.
func dvEncodeTime(v time.Time, at string) (any, error) {
	encoded, err := v.MarshalJSON()
	if err != nil {
		return nil, dvErr(at, "%v", err)
	}
	var s string
	if err := json.Unmarshal(encoded, &s); err != nil {
		return nil, dvErr(at, "%v", err)
	}
	return s, nil
}

func dvDecodeTime(raw any, at string) (time.Time, error) {
	s, err := dvString(raw, at)
	if err != nil {
		return time.Time{}, err
	}
	quoted, err := json.Marshal(s)
	if err != nil {
		return time.Time{}, dvErr(at, "%v", err)
	}
	var v time.Time
	if err := v.UnmarshalJSON(quoted); err != nil {
		return time.Time{}, dvErr(at, "%v", err)
	}
	return v, nil
}

func encRemoteReceipt(v pkg_onzggl3sn52xizltf5qwg5djn5xhg.RemoteReceipt, at string) (any, error) {
	enc1 := devalue.NewObject()
	var enc2 any = string(v.Message)
	enc1.Set("message", enc2)
	return enc1, nil
}

func decRemoteReceipt(raw any, at string) (pkg_onzggl3sn52xizltf5qwg5djn5xhg.RemoteReceipt, error) {
	var dvZero pkg_onzggl3sn52xizltf5qwg5djn5xhg.RemoteReceipt
	var dec1 pkg_onzggl3sn52xizltf5qwg5djn5xhg.RemoteReceipt
	obj2, err := dvObject(raw, at)
	if err != nil {
		return dvZero, err
	}
	if err := dvKnown(obj2, at, "message"); err != nil {
		return dvZero, err
	}
	raw3, err := dvRequired(obj2, "message", at+"/message")
	if err != nil {
		return dvZero, err
	}
	dec4, err := dvString(raw3, at+"/message")
	if err != nil {
		return dvZero, err
	}
	dec1.Message = dec4
	return dec1, nil
}

// EncodeRemoteReceipt converts v into the devalue value model.
func EncodeRemoteReceipt(v pkg_onzggl3sn52xizltf5qwg5djn5xhg.RemoteReceipt) (any, error) {
	return encRemoteReceipt(v, "")
}

// DecodeRemoteReceipt converts a devalue value model tree into a pkg_onzggl3sn52xizltf5qwg5djn5xhg.RemoteReceipt, rejecting any
// shape the type grammar does not admit.
func DecodeRemoteReceipt(raw any) (pkg_onzggl3sn52xizltf5qwg5djn5xhg.RemoteReceipt, error) {
	return decRemoteReceipt(raw, "")
}

// StringifyRemoteReceipt encodes v and serializes it with devalue.
func StringifyRemoteReceipt(v pkg_onzggl3sn52xizltf5qwg5djn5xhg.RemoteReceipt) (string, error) {
	encoded, err := encRemoteReceipt(v, "")
	if err != nil {
		return "", err
	}
	return devalue.Stringify(encoded)
}

// ParseRemoteReceipt parses a devalue document and decodes it into a pkg_onzggl3sn52xizltf5qwg5djn5xhg.RemoteReceipt.
func ParseRemoteReceipt(s string) (pkg_onzggl3sn52xizltf5qwg5djn5xhg.RemoteReceipt, error) {
	var zero pkg_onzggl3sn52xizltf5qwg5djn5xhg.RemoteReceipt
	parsed, err := devalue.Parse(s, nil)
	if err != nil {
		return zero, err
	}
	return decRemoteReceipt(parsed, "")
}

func encResult(v pkg_onzggl3sn52xizltf5xxa5djn5xgc3a.Result, at string) (any, error) {
	enc1 := devalue.NewObject()
	var enc2 any = string(v.Name)
	enc1.Set("name", enc2)
	var enc3 any = string(v.Count)
	enc1.Set("count", enc3)
	var enc4 any = string(v.Enabled)
	enc1.Set("enabled", enc4)
	var enc5 any = string(v.Label)
	enc1.Set("label", enc5)
	var enc6 any = float64(v.Operations)
	enc1.Set("operations", enc6)
	return enc1, nil
}

func decResult(raw any, at string) (pkg_onzggl3sn52xizltf5xxa5djn5xgc3a.Result, error) {
	var dvZero pkg_onzggl3sn52xizltf5xxa5djn5xgc3a.Result
	var dec1 pkg_onzggl3sn52xizltf5xxa5djn5xgc3a.Result
	obj2, err := dvObject(raw, at)
	if err != nil {
		return dvZero, err
	}
	if err := dvKnown(obj2, at, "name", "count", "enabled", "label", "operations"); err != nil {
		return dvZero, err
	}
	raw3, err := dvRequired(obj2, "name", at+"/name")
	if err != nil {
		return dvZero, err
	}
	dec4, err := dvString(raw3, at+"/name")
	if err != nil {
		return dvZero, err
	}
	dec1.Name = dec4
	raw5, err := dvRequired(obj2, "count", at+"/count")
	if err != nil {
		return dvZero, err
	}
	dec6, err := dvString(raw5, at+"/count")
	if err != nil {
		return dvZero, err
	}
	dec1.Count = dec6
	raw7, err := dvRequired(obj2, "enabled", at+"/enabled")
	if err != nil {
		return dvZero, err
	}
	dec8, err := dvString(raw7, at+"/enabled")
	if err != nil {
		return dvZero, err
	}
	dec1.Enabled = dec8
	raw9, err := dvRequired(obj2, "label", at+"/label")
	if err != nil {
		return dvZero, err
	}
	dec10, err := dvString(raw9, at+"/label")
	if err != nil {
		return dvZero, err
	}
	dec1.Label = dec10
	raw11, err := dvRequired(obj2, "operations", at+"/operations")
	if err != nil {
		return dvZero, err
	}
	num13, err := dvInteger(raw11, at+"/operations", math.MinInt, math.MaxInt)
	if err != nil {
		return dvZero, err
	}
	dec12 := int(num13)
	dec1.Operations = dec12
	return dec1, nil
}

// EncodeResult converts v into the devalue value model.
func EncodeResult(v pkg_onzggl3sn52xizltf5xxa5djn5xgc3a.Result) (any, error) { return encResult(v, "") }

// DecodeResult converts a devalue value model tree into a pkg_onzggl3sn52xizltf5xxa5djn5xgc3a.Result, rejecting any
// shape the type grammar does not admit.
func DecodeResult(raw any) (pkg_onzggl3sn52xizltf5xxa5djn5xgc3a.Result, error) {
	return decResult(raw, "")
}

// StringifyResult encodes v and serializes it with devalue.
func StringifyResult(v pkg_onzggl3sn52xizltf5xxa5djn5xgc3a.Result) (string, error) {
	encoded, err := encResult(v, "")
	if err != nil {
		return "", err
	}
	return devalue.Stringify(encoded)
}

// ParseResult parses a devalue document and decodes it into a pkg_onzggl3sn52xizltf5xxa5djn5xgc3a.Result.
func ParseResult(s string) (pkg_onzggl3sn52xizltf5xxa5djn5xgc3a.Result, error) {
	var zero pkg_onzggl3sn52xizltf5xxa5djn5xgc3a.Result
	parsed, err := devalue.Parse(s, nil)
	if err != nil {
		return zero, err
	}
	return decResult(parsed, "")
}

func encRoot0(v pkg_onzggl3sn52xizltf5qwg5djn5xhg.RemoteReceipt, at string) (any, error) {
	enc1, err := encRemoteReceipt(v, at)
	if err != nil {
		return nil, err
	}
	return enc1, nil
}

func decRoot0(raw any, at string) (pkg_onzggl3sn52xizltf5qwg5djn5xhg.RemoteReceipt, error) {
	var dvZero pkg_onzggl3sn52xizltf5qwg5djn5xhg.RemoteReceipt
	dec1, err := decRemoteReceipt(raw, at)
	if err != nil {
		return dvZero, err
	}
	return dec1, nil
}

// EncodeRoot0 converts v into the devalue value model.
func EncodeRoot0(v pkg_onzggl3sn52xizltf5qwg5djn5xhg.RemoteReceipt) (any, error) {
	return encRoot0(v, "")
}

// DecodeRoot0 converts a devalue value model tree into a pkg_onzggl3sn52xizltf5qwg5djn5xhg.RemoteReceipt, rejecting any
// shape the type grammar does not admit.
func DecodeRoot0(raw any) (pkg_onzggl3sn52xizltf5qwg5djn5xhg.RemoteReceipt, error) {
	return decRoot0(raw, "")
}

// StringifyRoot0 encodes v and serializes it with devalue.
func StringifyRoot0(v pkg_onzggl3sn52xizltf5qwg5djn5xhg.RemoteReceipt) (string, error) {
	encoded, err := encRoot0(v, "")
	if err != nil {
		return "", err
	}
	return devalue.Stringify(encoded)
}

// ParseRoot0 parses a devalue document and decodes it into a pkg_onzggl3sn52xizltf5qwg5djn5xhg.RemoteReceipt.
func ParseRoot0(s string) (pkg_onzggl3sn52xizltf5qwg5djn5xhg.RemoteReceipt, error) {
	var zero pkg_onzggl3sn52xizltf5qwg5djn5xhg.RemoteReceipt
	parsed, err := devalue.Parse(s, nil)
	if err != nil {
		return zero, err
	}
	return decRoot0(parsed, "")
}

func encRoot1(v pkg_onzggl3sn52xizltf5xxa5djn5xgc3a.Result, at string) (any, error) {
	enc1, err := encResult(v, at)
	if err != nil {
		return nil, err
	}
	return enc1, nil
}

func decRoot1(raw any, at string) (pkg_onzggl3sn52xizltf5xxa5djn5xgc3a.Result, error) {
	var dvZero pkg_onzggl3sn52xizltf5xxa5djn5xgc3a.Result
	dec1, err := decResult(raw, at)
	if err != nil {
		return dvZero, err
	}
	return dec1, nil
}

// EncodeRoot1 converts v into the devalue value model.
func EncodeRoot1(v pkg_onzggl3sn52xizltf5xxa5djn5xgc3a.Result) (any, error) { return encRoot1(v, "") }

// DecodeRoot1 converts a devalue value model tree into a pkg_onzggl3sn52xizltf5xxa5djn5xgc3a.Result, rejecting any
// shape the type grammar does not admit.
func DecodeRoot1(raw any) (pkg_onzggl3sn52xizltf5xxa5djn5xgc3a.Result, error) {
	return decRoot1(raw, "")
}

// StringifyRoot1 encodes v and serializes it with devalue.
func StringifyRoot1(v pkg_onzggl3sn52xizltf5xxa5djn5xgc3a.Result) (string, error) {
	encoded, err := encRoot1(v, "")
	if err != nil {
		return "", err
	}
	return devalue.Stringify(encoded)
}

// ParseRoot1 parses a devalue document and decodes it into a pkg_onzggl3sn52xizltf5xxa5djn5xgc3a.Result.
func ParseRoot1(s string) (pkg_onzggl3sn52xizltf5xxa5djn5xgc3a.Result, error) {
	var zero pkg_onzggl3sn52xizltf5xxa5djn5xgc3a.Result
	parsed, err := devalue.Parse(s, nil)
	if err != nil {
		return zero, err
	}
	return decRoot1(parsed, "")
}
