// Code generated by skgo. DO NOT EDIT.

package client

import (
	"context"
	"github.com/tylergannon/skgo"
	skgo21 "github.com/tylergannon/skgo/example/internal/skgo/links/onzggl3sn52xizltf5xxa5djn5xgc3a"
)

// Client uses the same enhanced Form endpoint as the browser.
type Client struct{ skgo.FormClient }

// Submit submits src/routes/optional/optional.remote.ts#submit once.
func (c Client) Submit(ctx context.Context, in skgo21.SkgoArg_submit) (skgo21.SkgoOut_submit, error) {
	return skgo.SubmitForm(ctx, c.FormClient, "83n4w1/submit", in, DecodeRoot0)
}
