// Code generated by skgo. DO NOT EDIT.
// The body throws. This load is implemented in Go, and skgo answers
// __data.json itself, so anything that renders in the browser is proof the
// Go handler replied rather than this module. Kit reads the export to learn
// that the route has server data; it never calls it.
const unimplemented = (): never => {
	throw new Error('skgo: implemented in Go');
};

export const load = (): { deployment: string } => unimplemented();
