// Code generated by skgo. DO NOT EDIT.

package site

// The functions this package declares, published under names the generated
// bindings package can spell. Each is the function itself and not a wrapper:
// skgo.Refresh finds a query by the code pointer of the function it names.
var (
	// Skgo_getSite is getSite, published as src/routes/site.remote.ts#getSite.
	Skgo_getSite = getSite
	// Skgo_layoutLoad is layoutLoad, published as the server load of src/routes/+layout.server.ts.
	Skgo_layoutLoad = layoutLoad
)
