// Code generated by skgo. DO NOT EDIT.

package site

import "github.com/tylergannon/skgo"

// SkgoRemotes returns the remote functions declared in this package.
func SkgoRemotes() []*skgo.Remote {
	return []*skgo.Remote{
		skgo.NewQueryNoArg("src/routes/site.remote.ts", "getSite", getSite),
	}
}

// SkgoLoads returns the server loads declared in this package.
func SkgoLoads() []*skgo.ServerLoad {
	return []*skgo.ServerLoad{
		skgo.NewLoad("src/routes/+layout.server.ts", layoutLoad),
	}
}

// SkgoEndpoints returns the server routes declared in this package.
func SkgoEndpoints() []*skgo.Endpoint {
	return []*skgo.Endpoint{}
}
