//go:build jsonschema

// Code generated by skgo. DO NOT EDIT.

package site

import (
	"encoding/json"

	"github.com/tylergannon/polytype"
)

// Stubs so the package compiles before polytype has run.
func (Site) Schema() json.RawMessage { panic("not implemented") }

var (
	_ = polytype.Declare(Site.Schema)
)
