// Code generated by polytype. DO NOT EDIT.

/**
 * Site describes the running application.
 */
export type Site = {
  /**
   * Name is the application's name.
   */
  "name": string;
  /**
   * Colocated says which directory the Go that answered lives in.
   */
  "colocated": string;
};
