// Code generated by skgo. DO NOT EDIT.

package account

import "github.com/tylergannon/skgo"

// SkgoRemotes returns the remote functions declared in this package.
func SkgoRemotes() []*skgo.Remote {
	return []*skgo.Remote{}
}

// SkgoLoads returns the server loads declared in this package.
func SkgoLoads() []*skgo.ServerLoad {
	return []*skgo.ServerLoad{
		skgo.NewLoad("src/routes/account/+layout.server.ts", layoutLoad),
		skgo.NewLoad("src/routes/account/+page.server.ts", pageLoad),
	}
}
