// Code generated by skgo. DO NOT EDIT.

package item

// The functions this package declares, published under names the generated
// bindings package can spell. Each is the function itself and not a wrapper:
// skgo.Refresh finds a query by the code pointer of the function it names.
var (
	// Skgo_getItem is getItem, published as src/routes/items/[id]/item.remote.ts#getItem.
	Skgo_getItem = getItem
)
