// Code generated by skgo. DO NOT EDIT.

package slug

import skgo "github.com/tylergannon/skgo"

import (
	hooks "github.com/tylergannon/skgo/example/web/src"
)

// RouteParams stores converted values. Only accessor reads record dependencies
// on the load invocation that constructed these params.
type RouteParams struct {
	event     *skgo.Event
	valueSlug string
}

func (p RouteParams) Slug() string { skgo.TrackLoadParam(p.event, "slug"); return p.valueSlug }

type RequestEvent = skgo.RequestEvent[RouteParams]

func SkgoRequestEvent(event *skgo.Event) RequestEvent {
	return RequestEvent{Event: event, Params: RouteParams{event: event,
		valueSlug: skgo.LoadParamValue[string](event, "slug"),
	}}
}

func SkgoParamMatchers() map[string]skgo.ParamMatcher {
	return map[string]skgo.ParamMatcher{
		"Order": func(value string) (any, bool) { return hooks.Order(value) },
	}
}
