// Code generated by skgo. DO NOT EDIT.

package slug

import (
	skgo "github.com/tylergannon/skgo"
	hooks "github.com/tylergannon/skgo/example/web/src"
)

// RouteParams stores converted values. Only accessor reads record dependencies
// on the load invocation that constructed these params.
type RouteParams struct {
	event     *skgo.Event
	valueSlug string
}

func (p RouteParams) Slug() string { skgo.TrackLoadParam(p.event, "slug"); return p.valueSlug }

type RequestEvent = skgo.RequestEvent[RouteParams]

func SkgoRequestEvent(event *skgo.Event) RequestEvent {
	return RequestEvent{Event: event, Params: RouteParams{event: event,
		valueSlug: skgo.LoadParamValue[string](event, "slug"),
	}}
}

func SkgoParamMatchers() map[string]skgo.ParamMatcher {
	return map[string]skgo.ParamMatcher{
		"Order": func(value string) (any, bool) { return hooks.Order(value) },
	}
}

// The functions this package declares, published under names the generated
// bindings package can spell. Each is the function itself and not a wrapper:
// skgo.Refresh finds a query by the code pointer of the function it names.
var (
	// Skgo_pageLoad is pageLoad, published as the server load of src/routes/account/reruns/[slug]/+page.server.ts.
	Skgo_pageLoad = pageLoad
)
