// Code generated by skgo. DO NOT EDIT.
import type { RequestEvent } from "@sveltejs/kit";

export const load = async (event: RequestEvent): Promise<{ revision: string }> => {
  throw new Error("skgo: implemented in Go");
};

// Kit reads these exports for action typing; Go answers every submission.
export const actions = {
  revise: async (_event: { request: Request }): Promise<{ message: string }> => {
    throw new Error("skgo: action implemented in Go");
  },
};
