// Code generated by skgo. DO NOT EDIT.

package godev

// The functions this package declares, published under names the generated
// bindings package can spell. Each is the function itself and not a wrapper:
// skgo.Refresh finds a query by the code pointer of the function it names.
var (
	// Skgo_getRevision is getRevision, published as src/routes/go-dev/go-dev.remote.ts#getRevision.
	Skgo_getRevision = getRevision
	// Skgo_pageLoad is pageLoad, published as the server load of src/routes/go-dev/+page.server.ts.
	Skgo_pageLoad = pageLoad
	Skgo_revise   = revise
)
