// Code generated by skgo. DO NOT EDIT.

package docs

import "github.com/tylergannon/skgo"

// SkgoRemotes returns the remote functions declared in this package.
func SkgoRemotes() []*skgo.Remote {
	return []*skgo.Remote{
		skgo.NewQuery("src/routes/docs/[...rest]/docs.remote.ts", "getPage", getPage),
	}
}
