// Code generated by skgo. DO NOT EDIT.

package docs

// The functions this package declares, published under names the generated
// bindings package can spell. Each is the function itself and not a wrapper:
// skgo.Refresh finds a query by the code pointer of the function it names.
var (
	// Skgo_getPage is getPage, published as src/routes/docs/[...rest]/docs.remote.ts#getPage.
	Skgo_getPage = getPage
)
