//go:build jsonschema

// Code generated by skgo. DO NOT EDIT.

package docs

import (
	"encoding/json"

	"github.com/tylergannon/polytype"
)

// Stubs so the package compiles before polytype has run.
func (Page) Schema() json.RawMessage { panic("not implemented") }

var (
	_ = polytype.Declare(Page.Schema)
)
