// Code generated by polytype. DO NOT EDIT.

/**
 * Page is one documentation page.
 */
export type Page = {
  /**
   * Path is the rest parameter as SvelteKit matched it.
   */
  "path": string;
  /**
   * Title is what the page shows.
   */
  "title": string;
  /**
   * Depth is how many segments deep the request went.
   */
  "depth": number;
};
