// Code generated by skgo. DO NOT EDIT.

package prices

import "github.com/tylergannon/skgo"

// SkgoRemotes returns the remote functions declared in this package.
func SkgoRemotes() []*skgo.Remote {
	return []*skgo.Remote{
		skgo.NewQuery("src/routes/prices/prices.remote.ts", "getListPrice", getListPrice),
		skgo.NewQuery("src/routes/prices/prices.remote.ts", "getSalePrice", getSalePrice),
	}
}
