// Code generated by polytype. DO NOT EDIT.

/**
 * Money is the Go side of the app's `Money` class. The junkyard app declared a `transport` codec so that both sides see a real `Money`, not a plain object.
 */
export type Money = {
  "cents": number;
  "currency": string;
};
