// Code generated by skgo. DO NOT EDIT.
import type { RequestEvent } from "@sveltejs/kit";
import type { Invoice } from "./types";

export const load = async (
  event: RequestEvent,
): Promise<{ asOf: string; invoices: Array<Invoice> }> => {
  throw new Error("skgo: implemented in Go");
};
