//go:build adapter_prerender_research

// Use adapter_load_research_overlay.json from the repository root to run this
// with the adapter_prerender_research tag in internal/gen. It uses that package's
// existing isolated application-fixture helpers without modifying the checkout.
package gen

import (
	"encoding/json"
	"os"
	"os/exec"
	"path/filepath"
	"regexp"
	"strings"
	"testing"
)

// Temporary research: prove a build-only adapter loader can replace throwing
// server loads without rewriting application files or Kit's implementation.
func TestResearchAdapterSuppliesBuildLoads(t *testing.T) {
	fixture, err := preparedProductionFixture()
	if err != nil {
		t.Fatal(err)
	}
	root, err := repoRoot()
	if err != nil {
		t.Fatal(err)
	}
	ui := filepath.Join(fixture.app, "ui")
	if err := frontendDependencies(root, filepath.Join(ui, "node_modules")); err != nil {
		t.Fatal(err)
	}
	if out, err := runGoGenerate(fixture.app); err != nil {
		t.Fatalf("generate: %v\n%s", err, out)
	}
	var registry struct {
		Loads []string `json:"loads"`
	}
	raw, err := os.ReadFile(filepath.Join(ui, "skgo.remotes.json"))
	if err != nil {
		t.Fatal(err)
	}
	if err := json.Unmarshal(raw, &registry); err != nil {
		t.Fatal(err)
	}
	if len(registry.Loads) != 7 {
		t.Fatalf("production fixture must declare seven loads, got %d", len(registry.Loads))
	}
	stubs := map[string]string{}
	buildVariants := map[string]string{}
	for _, module := range registry.Loads {
		path := filepath.Join(ui, filepath.FromSlash(module))
		raw, err := os.ReadFile(path)
		if err != nil {
			t.Fatal(err)
		}
		text := string(raw)
		start := strings.Index(text, "// Go answers this load")
		load := strings.Index(text, "export const load")
		if start < 0 || load < 0 {
			t.Fatalf("unexpected stub %s", module)
		}
		body := regexp.MustCompile(`=>\s*building`).FindStringIndex(text[load:])
		if body == nil {
			t.Fatalf("unexpected load %s: %s", module, text[load:])
		}
		text = text[:start] + text[load:load+body[0]] + "=> { throw new Error('skgo: implemented in Go'); };\n"
		text = regexp.MustCompile(`(?m)^import \{ (building|error, redirect) \} from [^\n]+\n`).ReplaceAllString(text, "")
		text = strings.ReplaceAll(text, "import('@sveltejs/kit').RequestEvent", "RequestEvent")
		text = strings.ReplaceAll(text, "import(\"@sveltejs/kit\").RequestEvent", "RequestEvent")
		text = "import type { RequestEvent } from '@sveltejs/kit';\n" + text
		for _, forbidden := range []string{"buildLoad", "platform", "building", "getRequestEvent", "@skgo/sveltekit-adapter/prerender"} {
			if strings.Contains(text, forbidden) {
				t.Fatalf("load source %s still contains %s", module, forbidden)
			}
		}
		if err := os.WriteFile(path, []byte(text), 0644); err != nil {
			t.Fatal(err)
		}
		stubs[path] = text
	}
	// For this boundary experiment the build config owns the old bridge modules.
	// A product implementation would construct these from Go's declaration
	// metadata, rather than keep a second copy of application source.
	if err := filepath.WalkDir(filepath.Join(ui, "src"), func(path string, entry os.DirEntry, err error) error {
		if err != nil {
			return err
		}
		if entry.IsDir() {
			return nil
		}
		if entry.Name() != "hooks.server.ts" && entry.Name() != "+server.ts" && !strings.HasSuffix(entry.Name(), ".remote.ts") {
			return nil
		}
		raw, err := os.ReadFile(path)
		if err != nil {
			return err
		}
		text := string(raw)
		module, err := filepath.Rel(ui, path)
		if err != nil {
			return err
		}
		module = filepath.ToSlash(module)
		if entry.Name() == "hooks.server.ts" {
			buildVariants[module] = text
			text = "// Code generated by skgo. DO NOT EDIT.\nexport {};\n"
		} else if entry.Name() == "+server.ts" {
			buildVariants[module] = text
			methods := regexp.MustCompile(`export const ([A-Z]+|fallback) = fromGo;`).FindAllStringSubmatch(text, -1)
			if len(methods) == 0 {
				t.Fatalf("endpoint %s has no method exports", path)
			}
			text = "// Code generated by skgo. DO NOT EDIT.\nimport type { RequestHandler } from '@sveltejs/kit';\n"
			for _, method := range methods {
				text += "export const " + method[1] + ": RequestHandler = () => { throw new Error('skgo: implemented in Go'); };\n"
			}
		} else if strings.Contains(text, "const prerenderFromGo") {
			buildVariants[module] = text
			start := strings.Index(text, "const prerenderFromGo")
			end := strings.Index(text[start:], "export const ")
			if end < 0 {
				t.Fatalf("no prerender export in %s", path)
			}
			text = text[:start] + text[start+end:]
			text = regexp.MustCompile(`\bgetRequestEvent\s*,\s*`).ReplaceAllString(text, "")
			text = regexp.MustCompile(`(?m)^import \{ remoteInputs[^\n]+\n`).ReplaceAllString(text, "")
			text = regexp.MustCompile(`prerenderFromGo\([^)]*\)`).ReplaceAllString(text, "unimplemented()")
			text = regexp.MustCompile(`(?s),\s*\{\s*inputs:.*?\}\s*\)`).ReplaceAllString(text, ")")
		} else {
			return nil
		}
		for _, forbidden := range []string{"prerenderFromGo", "fromGo", "platform", "getRequestEvent", "$skgoRemoteInputs", "building", "@skgo/sveltekit-adapter/prerender"} {
			if strings.Contains(text, forbidden) {
				t.Fatalf("runtime source %s still contains %s", path, forbidden)
			}
		}
		stubs[path] = text
		return os.WriteFile(path, []byte(text), 0644)
	}); err != nil {
		t.Fatal(err)
	}
	if len(buildVariants) != 8 {
		t.Fatalf("fixture needs one hook, three remote, and four endpoint build variants, got %d", len(buildVariants))
	}
	variantData, err := json.Marshal(buildVariants)
	if err != nil {
		t.Fatal(err)
	}
	const plugin = `
import { readFileSync } from 'node:fs';
import { resolve } from 'node:path';
function researchAdapter() {
 const adapter = skgo();
 let root;
 let loads;
 adapter.vite.plugins.pre.unshift({
  name: 'research-skgo-build-loads',
  apply: 'build',
  applyToEnvironment: environment => environment.name === 'ssr',
  configResolved(config) {
   root = config.root;
   loads = new Set(JSON.parse(readFileSync(resolve(root, 'skgo.remotes.json'), 'utf8')).loads);
  },
  load: { order: 'pre', handler(id) {
   const module = id.slice(root.length + 1);
   if (researchBuildVariants[module]) return researchBuildVariants[module];
   if (!loads.has(module)) return null;
   const source = module.replace(/\+(page|layout)\.server\.(ts|js)$/, '$1.server.go');
   return 'import { error, redirect } from "@sveltejs/kit";\n' +
    'export * from ' + JSON.stringify(id + '?skgo-original') + ';\n' +
    'export const load = async (event) => {\n' +
    ' const answer = await event.platform.skgoPrerenderLoad(' + JSON.stringify(module) + ', ' + JSON.stringify(source) + ', event);\n' +
    ' if (answer.redirect) redirect(answer.redirect.status, answer.redirect.location);\n' +
    ' if (answer.error) error(answer.error.status, answer.error.message);\n' +
    ' if (answer.data === undefined) throw new Error("skgo: prerender Go load returned no data");\n' +
    ' return answer.data;\n};\n';
  }}
 });
 return adapter;
}
`
	config := filepath.Join(ui, "vite.config.ts")
	raw, err = os.ReadFile(config)
	if err != nil {
		t.Fatal(err)
	}
	text := strings.Replace(string(raw), "adapter: skgo(),", "adapter: researchAdapter(),", 1) + "\nconst researchBuildVariants = " + string(variantData) + ";\n" + plugin
	if err := os.WriteFile(config, []byte(text), 0644); err != nil {
		t.Fatal(err)
	}
	readTree := func(directory string) map[string]string {
		files := map[string]string{}
		if err := filepath.WalkDir(directory, func(path string, entry os.DirEntry, err error) error {
			if err != nil {
				return err
			}
			if entry.IsDir() {
				return nil
			}
			raw, err := os.ReadFile(path)
			if err != nil {
				return err
			}
			name, err := filepath.Rel(directory, path)
			if err != nil {
				return err
			}
			files[name] = string(raw)
			return nil
		}); err != nil {
			t.Fatal(err)
		}
		return files
	}
	sourceBefore := readTree(filepath.Join(ui, "src"))
	build := exec.Command(filepath.Join(ui, "node_modules/.bin/vp"), "build")
	build.Dir = ui
	build.Env = append(os.Environ(), "ORIGIN=http://127.0.0.1:8080")
	output, err := build.CombinedOutput()
	if err != nil {
		t.Fatalf("real build with adapter-supplied loads: %v\n%s", err, output)
	}
	t.Logf("Kit build completed with %d throwing source loads and %d hook/remote/endpoint bridge modules supplied only by the build config", len(registry.Loads), len(buildVariants))
	for path, want := range stubs {
		raw, err := os.ReadFile(path)
		if err != nil || string(raw) != want {
			t.Fatalf("build changed source file %s: %v", path, err)
		}
	}
	sourceAfter := readTree(filepath.Join(ui, "src"))
	if len(sourceAfter) != len(sourceBefore) {
		t.Fatalf("build changed source tree size: %d -> %d", len(sourceBefore), len(sourceAfter))
	}
	for name, want := range sourceBefore {
		if got, ok := sourceAfter[name]; !ok || got != want {
			t.Fatalf("build changed source file %s", name)
		}
	}
	bridgeSymbols := []string{"skgoPrerenderLoad", "skgoPrerenderRemote", "skgoPrerenderEndpoint", "skgoRequestHandle"}
	serverOutput := readTree(filepath.Join(ui, ".svelte-kit/output/server"))
	// Kit removes non-dynamic prerender remote bodies after crawling in
	// build/remote.js. Their positive proof is the literal remote artifact and
	// rendered-result contracts below, not a callback in the final JS output.
	for _, symbol := range []string{"skgoPrerenderLoad", "skgoPrerenderEndpoint", "skgoRequestHandle"} {
		found := false
		for name, content := range serverOutput {
			if strings.HasSuffix(name, ".js") && strings.Contains(content, symbol) {
				found = true
			}
		}
		if !found {
			t.Fatalf("Kit build SSR output lacks expected bridge %s", symbol)
		}
	}
	for _, directory := range []string{"build/ssr", "build/client"} {
		for name, content := range readTree(filepath.Join(ui, directory)) {
			if !strings.HasSuffix(name, ".js") {
				continue
			}
			for _, symbol := range bridgeSymbols {
				if strings.Contains(content, symbol) {
					t.Fatalf("build bridge %s leaked into %s/%s", symbol, directory, name)
				}
			}
		}
	}
	contracts := exec.Command("go", "test", "-v", ".", "-run", "^(TestProductionPrerenderedEndpointsAndPages|TestProductionRedirectServing|TestSharedRendererDefaultFilter|TestProductionNoArgumentNullUsesArtifactMiss|TestProductionStoredError|TestProductionTransformFailure)$")
	contracts.Dir = fixture.app
	output, err = contracts.CombinedOutput()
	if err != nil {
		t.Fatalf("real handler contracts: %v\n%s", err, output)
	}
	for _, name := range []string{"TestProductionPrerenderedEndpointsAndPages", "TestProductionRedirectServing", "TestSharedRendererDefaultFilter", "TestProductionNoArgumentNullUsesArtifactMiss", "TestProductionStoredError", "TestProductionTransformFailure"} {
		if !strings.Contains(string(output), "=== RUN   "+name+"\n") || !strings.Contains(string(output), "--- PASS: "+name+" (") {
			t.Fatalf("contract %s did not execute and pass:\n%s", name, output)
		}
	}
	if strings.Contains(string(output), "--- SKIP:") {
		t.Fatalf("handler contracts skipped:\n%s", output)
	}
	t.Logf("real handler contracts:\n%s", output)
}
