// Package swiftgen projects Polytype's published type grammar into native Swift
// models and ordinary remote calls. It does not load source or own Kit identity.
package swiftgen

import (
	_ "embed"
	"fmt"
	"go/constant"
	"strconv"
	"strings"
	"unicode"

	tg "github.com/tylergannon/polytype/typegrammar"
)

//go:embed runtime.swift
var runtime string

type Call struct {
	Name, ID, Kind string
	Input, Output  int // Input -1 means no argument.
}
type Result struct {
	Source []byte
	Names  map[tg.Name]string
}
type objectDecl struct {
	name string
	node *tg.Object
}
type enumDecl struct {
	name string
	node *tg.Enum
}
type unionDecl struct {
	name string
	node *tg.Union
}
type emitter struct {
	defs         tg.Definitions
	names        map[tg.Name]string
	used         map[string]bool
	objects      map[*tg.Object]string
	enums        map[string]string
	unions       map[string]string
	extraObjects []objectDecl
	extraEnums   []enumDecl
	extraUnions  []unionDecl
	out          strings.Builder
}

func Generate(defs tg.Definitions, roots []tg.Type, calls []Call) (Result, error) {
	if err := defs.Validate(); err != nil {
		return Result{}, err
	}
	m := &emitter{defs: defs, names: map[tg.Name]string{}, used: map[string]bool{}, objects: map[*tg.Object]string{}, enums: map[string]string{}, unions: map[string]string{}}
	for _, name := range strings.Fields("String Bool Int Int8 Int16 Int32 Int64 UInt UInt8 UInt16 UInt32 UInt64 Float Double Any Self Error Sendable FixedWidthInteger BinaryInteger BinaryFloatingPoint Data NSNumber NSNull NativeAPI NativeModelError RemoteClient RemoteError RemoteRequest RemoteResponse RemoteTransport URLSessionTransport Set Array JSONSerialization _SKGoWire Foundation CoreFoundation CFGetTypeID CFBooleanGetTypeID SKGoNative") {
		m.used[name] = true
	}
	for _, def := range defs {
		m.names[def.Name] = m.allocate(def.Name.Name)
	}
	for _, def := range defs {
		name := m.names[def.Name]
		switch node := def.Type.(type) {
		case *tg.Object:
			m.objects[node] = name
		case *tg.Enum:
			m.enums[enumKey(node)] = name
		}
	}
	for _, def := range defs {
		if err := m.collect(def.Type, m.names[def.Name]); err != nil {
			return Result{}, fmt.Errorf("%s: %s: %w", def.Source, def.Name, err)
		}
	}
	for i, root := range roots {
		if err := m.collect(root, fmt.Sprintf("Root%d", i)); err != nil {
			return Result{}, err
		}
	}
	m.out.WriteString("// Code generated by skgo. DO NOT EDIT.\nimport Foundation\nimport CoreFoundation\n")
	if len(calls) != 0 {
		m.out.WriteString("import SKGoNative\n")
	}
	m.out.WriteString("\n" + runtime + "\n")
	for _, def := range defs {
		name := m.names[def.Name]
		switch node := def.Type.(type) {
		case *tg.Object:
			m.emitObject(name, node)
		case *tg.Enum:
			if m.enums[enumKey(node)] == name {
				if err := m.emitEnum(name, node); err != nil {
					return Result{}, fmt.Errorf("%s: %w", def.Source, err)
				}
			} else {
				fmt.Fprintf(&m.out, "public typealias %s = %s\n", ident(name), ident(m.enums[enumKey(node)]))
			}
			m.emitFunctions(name, node)
		default:
			fmt.Fprintf(&m.out, "public typealias %s = %s\n", ident(name), m.typeName(def.Type))
			m.emitFunctions(name, def.Type)
		}
	}
	for _, decl := range m.extraObjects {
		m.emitObject(decl.name, decl.node)
	}
	for _, decl := range m.extraEnums {
		if err := m.emitEnum(decl.name, decl.node); err != nil {
			return Result{}, err
		}
	}
	for _, decl := range m.extraUnions {
		m.emitUnion(decl.name, decl.node)
	}
	for i, root := range roots {
		m.emitFunctionsAs(fmt.Sprintf("Root_%d", i), root)
	}
	if err := m.emitCalls(roots, calls); err != nil {
		return Result{}, err
	}
	return Result{Source: []byte(m.out.String()), Names: m.names}, nil
}

func (m *emitter) allocate(hint string) string {
	hint = plain(hint)
	if hint == "" {
		hint = "Value"
	}
	name := hint
	for i := 2; m.used[name]; i++ {
		name = hint + strconv.Itoa(i)
	}
	m.used[name] = true
	return name
}
func plain(s string) string {
	var b strings.Builder
	for i, r := range s {
		if unicode.IsLetter(r) || r == '_' || unicode.IsDigit(r) && i > 0 {
			b.WriteRune(r)
		} else {
			b.WriteByte('_')
		}
	}
	return b.String()
}
func ident(s string) string {
	if strings.Contains(" associatedtype borrowing break case catch class consuming continue convenience copy default defer deinit didSet distributed do dynamic each else enum extension fallthrough false fileprivate final for func get guard if import in indirect infix init inout internal is isolated lazy let macro mutating nonisolated nonmutating open operator optional override package postfix precedencegroup prefix private protocol public repeat required rethrows return self Self set some static struct subscript super switch throw throws true try typealias unowned var weak where while willSet any as await async nil ", " "+s+" ") {
		return "`" + s + "`"
	}
	return s
}
func quote(s string) string {
	var b strings.Builder
	b.WriteByte('"')
	for _, r := range s {
		switch r {
		case '"':
			b.WriteString(`\"`)
		case '\\':
			b.WriteString(`\\`)
		case '\n':
			b.WriteString(`\n`)
		case '\r':
			b.WriteString(`\r`)
		case '\t':
			b.WriteString(`\t`)
		default:
			if r < 32 || r == 0x2028 || r == 0x2029 {
				fmt.Fprintf(&b, `\u{%x}`, r)
			} else {
				b.WriteRune(r)
			}
		}
	}
	b.WriteByte('"')
	return b.String()
}
func enumKey(e *tg.Enum) string {
	var b strings.Builder
	fmt.Fprintf(&b, "%s:%d:%s", e.GoType, e.Mode, e.Kind)
	for _, member := range e.Members {
		fmt.Fprintf(&b, ":%s=%s", member.Name, member.Value.ExactString())
	}
	return b.String()
}
func unionKey(u *tg.Union) string {
	var b strings.Builder
	fmt.Fprintf(&b, "%s:%s", u.Interface, u.Discriminator)
	for _, v := range u.Variants {
		fmt.Fprintf(&b, ":%s=%s", v.Implementation, v.Tag)
	}
	return b.String()
}

func (m *emitter) collect(t tg.Type, hint string) error {
	switch n := t.(type) {
	case *tg.Scalar:
		if scalar(n.Kind) == "" {
			return fmt.Errorf("unsupported scalar %s", n.Kind)
		}
	case *tg.Time:
	case *tg.Ref:
		if m.names[n.Target] == "" {
			return fmt.Errorf("unresolved reference %s", n.Target)
		}
	case *tg.Pointer:
		return m.collect(n.Element, hint+"Value")
	case *tg.Slice:
		return m.collect(n.Element, hint+"Element")
	case *tg.Array:
		return m.collect(n.Element, hint+"Element")
	case *tg.Enum:
		if n.Mode != tg.EnumNames && integer(n.Kind) {
			for _, member := range n.Members {
				number, ok := constant.Int64Val(member.Value)
				if !ok || number < -9007199254740991 || number > 9007199254740991 {
					return fmt.Errorf("%s.%s is outside the JavaScript integer domain", n.GoType, member.Name)
				}
			}
		}
		if m.enums[enumKey(n)] == "" {
			name := m.allocate(n.GoType.Name + "Enum")
			m.enums[enumKey(n)] = name
			m.extraEnums = append(m.extraEnums, enumDecl{name, n})
		}
	case *tg.Object:
		if m.objects[n] == "" {
			name := m.allocate(hint)
			m.objects[n] = name
			m.extraObjects = append(m.extraObjects, objectDecl{name, n})
		}
		for _, field := range n.Fields {
			childHint := m.objects[n] + "_" + field.GoName
			var err error
			switch value := field.Value.(type) {
			case *tg.Required:
				err = m.collect(value.Type, childHint)
			case *tg.Optional:
				err = m.collect(value.Type, childHint)
			case *tg.Nullable:
				err = m.collect(value.Type, childHint)
			case *tg.Union:
				err = m.collectUnion(value, childHint)
			case *tg.OptionalUnion:
				err = m.collectUnion(&value.Union, childHint)
			case *tg.UnionSlice:
				err = m.collectUnion(&value.Union, childHint)
			default:
				err = fmt.Errorf("unsupported field grammar %T", value)
			}
			if err != nil {
				return fmt.Errorf("%s: field %s: %w", field.Source, field.JSONName, err)
			}
		}
	default:
		return fmt.Errorf("unsupported type grammar %T", t)
	}
	return nil
}
func (m *emitter) collectUnion(u *tg.Union, hint string) error {
	if m.unions[unionKey(u)] != "" {
		return nil
	}
	for _, variant := range u.Variants {
		if m.names[variant.Implementation] == "" {
			return fmt.Errorf("unresolved union member %s", variant.Implementation)
		}
	}
	name := m.allocate(hint + "Value")
	m.unions[unionKey(u)] = name
	m.extraUnions = append(m.extraUnions, unionDecl{name, u})
	return nil
}
func scalar(kind tg.ScalarKind) string {
	switch kind {
	case tg.Bool:
		return "Bool"
	case tg.String:
		return "String"
	case tg.Int:
		return "Int"
	case tg.Int8:
		return "Int8"
	case tg.Int16:
		return "Int16"
	case tg.Int32:
		return "Int32"
	case tg.Int64:
		return "Int64"
	case tg.Uint:
		return "UInt"
	case tg.Uint8:
		return "UInt8"
	case tg.Uint16:
		return "UInt16"
	case tg.Uint32:
		return "UInt32"
	case tg.Uint64:
		return "UInt64"
	case tg.Float32:
		return "Float"
	case tg.Float64:
		return "Double"
	}
	return ""
}
func integer(kind tg.ScalarKind) bool {
	return kind != tg.Bool && kind != tg.String && kind != tg.Float32 && kind != tg.Float64
}
func (m *emitter) typeName(t tg.Type) string {
	switch n := t.(type) {
	case *tg.Scalar:
		return scalar(n.Kind)
	case *tg.Time:
		return "String"
	case *tg.Ref:
		return ident(m.names[n.Target])
	case *tg.Pointer:
		return m.typeName(n.Element)
	case *tg.Object:
		return ident(m.objects[n])
	case *tg.Enum:
		return ident(m.enums[enumKey(n)])
	case *tg.Slice:
		return "[" + m.typeName(n.Element) + "]"
	case *tg.Array:
		return "[" + m.typeName(n.Element) + "]"
	}
	panic("uncollected type")
}
func (m *emitter) expression(t tg.Type, value, depth string, encode bool) string {
	switch n := t.(type) {
	case *tg.Ref:
		return fmt.Sprintf("try _skgo%sType_%s(%s, %s)", verb(encode), m.names[n.Target], value, depth)
	case *tg.Object:
		return fmt.Sprintf("try _skgo%sType_%s(%s, %s)", verb(encode), m.objects[n], value, depth)
	case *tg.Pointer:
		return m.expression(n.Element, value, depth, encode)
	case *tg.Time:
		if encode {
			return value
		}
		return "try _SKGoWire.string(" + value + ")"
	case *tg.Scalar:
		if encode {
			if integer(n.Kind) {
				return "try _SKGoWire.encodeInteger(" + value + ")"
			}
			if n.Kind == tg.Float32 || n.Kind == tg.Float64 {
				return "try _SKGoWire.encodeNumber(" + value + ")"
			}
			return value
		}
		if integer(n.Kind) {
			return "try _SKGoWire.integer(" + value + ", as: " + scalar(n.Kind) + ".self)"
		}
		if n.Kind == tg.Float32 || n.Kind == tg.Float64 {
			return "try _SKGoWire.number(" + value + ", as: " + scalar(n.Kind) + ".self)"
		}
		if n.Kind == tg.Bool {
			return "try _SKGoWire.boolean(" + value + ")"
		}
		return "try _SKGoWire.string(" + value + ")"
	case *tg.Enum:
		rawKind := n.Kind
		if n.Mode == tg.EnumNames {
			rawKind = tg.String
		}
		if encode {
			return m.expression(&tg.Scalar{Kind: rawKind}, value+".rawValue", depth, true)
		}
		return "try _skgoDecodeEnum" + m.enums[enumKey(n)] + "(" + value + ")"
	case *tg.Slice:
		return m.arrayExpr(n.Element, value, depth, encode, -1)
	case *tg.Array:
		return m.arrayExpr(n.Element, value, depth, encode, n.Length)
	}
	panic("uncollected type")
}
func verb(encode bool) string {
	if encode {
		return "Encode"
	}
	return "Decode"
}
func (m *emitter) arrayExpr(element tg.Type, value, depth string, encode bool, length int64) string {
	count := ""
	if length >= 0 {
		count = fmt.Sprintf(", length: %d", length)
	}
	if encode {
		return "try _SKGoWire.encodeArray(" + value + count + ") { element in " + m.expression(element, "element", depth+" + 1", true) + " }"
	}
	return "try _SKGoWire.array(" + value + count + ").map { element in " + m.expression(element, "element", depth+" + 1", false) + " }"
}
func (m *emitter) emitFunctions(name string, t tg.Type) { m.emitFunctionsAs("Type_"+name, t) }
func (m *emitter) emitFunctionsAs(name string, t tg.Type) {
	fmt.Fprintf(&m.out, "\nfileprivate func _skgoEncode%s(_ value: %s, _ depth: Int) throws -> Any {\ntry _SKGoWire.depth(depth)\nreturn %s\n}\n", name, m.typeName(t), m.expression(t, "value", "depth", true))
	fmt.Fprintf(&m.out, "fileprivate func _skgoDecode%s(_ value: Any, _ depth: Int) throws -> %s {\ntry _SKGoWire.depth(depth)\nreturn %s\n}\n", name, m.typeName(t), m.expression(t, "value", "depth", false))
}
func fieldNames(fields []tg.Field) []string {
	used := map[string]bool{"self": true, "Self": true, "super": true, "init": true, "deinit": true}
	result := make([]string, len(fields))
	for i, f := range fields {
		name := plain(f.JSONName)
		if name == "" || name == "_" {
			name = "field"
		}
		base := name
		for j := 2; used[name]; j++ {
			name = base + strconv.Itoa(j)
		}
		used[name] = true
		result[i] = name
	}
	return result
}
func (m *emitter) fieldType(v tg.FieldValue) string {
	switch n := v.(type) {
	case *tg.Required:
		return m.typeName(n.Type)
	case *tg.Optional:
		return m.typeName(n.Type) + "?"
	case *tg.Nullable:
		return m.typeName(n.Type) + "?"
	case *tg.Union:
		return ident(m.unions[unionKey(n)])
	case *tg.OptionalUnion:
		return ident(m.unions[unionKey(&n.Union)]) + "?"
	case *tg.UnionSlice:
		return "[" + ident(m.unions[unionKey(&n.Union)]) + "]"
	}
	panic("uncollected field")
}
func (m *emitter) fieldExpression(v tg.FieldValue, value, depth string, encode bool) string {
	switch n := v.(type) {
	case *tg.Required:
		return m.expression(n.Type, value, depth, encode)
	case *tg.Optional:
		return m.expression(n.Type, value, depth, encode)
	case *tg.Nullable:
		return m.expression(n.Type, value, depth, encode)
	case *tg.Union:
		return fmt.Sprintf("try _skgo%sType_%s(%s, %s)", verb(encode), m.unions[unionKey(n)], value, depth)
	case *tg.OptionalUnion:
		return m.fieldExpression(&n.Union, value, depth, encode)
	case *tg.UnionSlice:
		call := m.fieldExpression(&n.Union, "element", depth+" + 1", encode)
		if encode {
			return "try " + value + ".map { element in " + call + " }"
		}
		return "try _SKGoWire.array(" + value + ").map { element in " + call + " }"
	}
	panic("uncollected field")
}
func optional(v tg.FieldValue) bool {
	switch v.(type) {
	case *tg.Optional, *tg.OptionalUnion:
		return true
	}
	return false
}
func nullable(v tg.FieldValue) bool { _, ok := v.(*tg.Nullable); return ok }
func (m *emitter) emitObject(name string, n *tg.Object) {
	fields := fieldNames(n.Fields)
	fmt.Fprintf(&m.out, "\npublic final class %s: Sendable {\n", ident(name))
	for i, f := range n.Fields {
		fmt.Fprintf(&m.out, "public let %s: %s\n", ident(fields[i]), m.fieldType(f.Value))
	}
	m.out.WriteString("public init(")
	for i, f := range n.Fields {
		if i > 0 {
			m.out.WriteString(", ")
		}
		fmt.Fprintf(&m.out, "%s: %s", ident(fields[i]), m.fieldType(f.Value))
		if optional(f.Value) {
			m.out.WriteString(" = nil")
		}
	}
	m.out.WriteString(") {\n")
	for _, f := range fields {
		fmt.Fprintf(&m.out, "self.%s = %s\n", ident(f), ident(f))
	}
	m.out.WriteString("}\n}\n")
	fmt.Fprintf(&m.out, "fileprivate func _skgoEncodeType_%s(_ value: %s, _ depth: Int) throws -> Any {\ntry _SKGoWire.depth(depth)\nvar object: [String: Any] = [:]\n", name, ident(name))
	for i, f := range n.Fields {
		val := "value." + ident(fields[i])
		key := quote(f.JSONName)
		if optional(f.Value) || nullable(f.Value) {
			fmt.Fprintf(&m.out, "if let child = %s { object[%s] = %s }", val, key, m.fieldExpression(f.Value, "child", "depth + 1", true))
			if nullable(f.Value) {
				fmt.Fprintf(&m.out, " else { object[%s] = NSNull() }", key)
			}
			m.out.WriteString("\n")
		} else {
			fmt.Fprintf(&m.out, "object[%s] = %s\n", key, m.fieldExpression(f.Value, val, "depth + 1", true))
		}
	}
	m.out.WriteString("return object\n}\n")
	fmt.Fprintf(&m.out, "fileprivate func _skgoDecodeType_%s(_ value: Any, _ depth: Int) throws -> %s {\ntry _SKGoWire.depth(depth)\nlet object = try _SKGoWire.object(value, keys: [", name, ident(name))
	for i, f := range n.Fields {
		if i > 0 {
			m.out.WriteString(",")
		}
		m.out.WriteString(quote(f.JSONName))
	}
	m.out.WriteString("])\n")
	for i, f := range n.Fields {
		raw := "try _SKGoWire.required(object, " + quote(f.JSONName) + ")"
		if optional(f.Value) {
			raw = "object[" + quote(f.JSONName) + "]"
		}
		expression := m.fieldExpression(f.Value, raw, "depth + 1", false)
		if optional(f.Value) || nullable(f.Value) {
			method := "optional"
			if nullable(f.Value) {
				method = "nullable"
			}
			expression = "try _SKGoWire." + method + "(" + raw + ") { child in " + m.fieldExpression(f.Value, "child", "depth + 1", false) + " }"
		}
		fmt.Fprintf(&m.out, "let field%d: %s = %s\n", i, m.fieldType(f.Value), expression)
	}
	fmt.Fprintf(&m.out, "return %s(", ident(name))
	for i := range n.Fields {
		if i > 0 {
			m.out.WriteString(",")
		}
		fmt.Fprintf(&m.out, "%s: field%d", ident(fields[i]), i)
	}
	m.out.WriteString(")\n}\n")
}
func (m *emitter) emitEnum(name string, n *tg.Enum) error {
	kind := n.Kind
	if n.Mode == tg.EnumNames {
		kind = tg.String
	}
	if kind == tg.Bool || kind == tg.Float32 || kind == tg.Float64 {
		return fmt.Errorf("unsupported enum scalar %s", kind)
	}
	fmt.Fprintf(&m.out, "\npublic enum %s: %s, Sendable {\n", ident(name), scalar(kind))
	values := map[string]string{}
	for _, member := range n.Members {
		value := quote(member.Name)
		if n.Mode != tg.EnumNames {
			if kind == tg.String {
				value = quote(constant.StringVal(member.Value))
			} else {
				number, ok := constant.Int64Val(member.Value)
				if !ok || number < -9007199254740991 || number > 9007199254740991 {
					return fmt.Errorf("%s.%s is outside the JavaScript integer domain", n.GoType, member.Name)
				}
				value = strconv.FormatInt(number, 10)
			}
		}
		if existing := values[value]; existing != "" {
			fmt.Fprintf(&m.out, "public static var %s: Self { .%s }\n", ident(member.Name), ident(existing))
		} else {
			values[value] = member.Name
			fmt.Fprintf(&m.out, "case %s = %s\n", ident(member.Name), value)
		}
	}
	m.out.WriteString("}\n")
	fmt.Fprintf(&m.out, "fileprivate func _skgoDecodeEnum%s(_ value: Any) throws -> %s {\nlet raw = %s\nguard let result = %s(rawValue: raw) else { throw NativeModelError.invalid(\"Unknown enum member\") }\nreturn result\n}\n", name, ident(name), m.expression(&tg.Scalar{Kind: kind}, "value", "0", false), ident(name))
	return nil
}
func (m *emitter) definition(name tg.Name) tg.Type {
	for _, d := range m.defs {
		if d.Name == name {
			return d.Type
		}
	}
	panic("missing definition")
}
func (m *emitter) variantHas(u *tg.Union, v tg.Variant) bool {
	t := m.definition(v.Implementation)
	for {
		switch n := t.(type) {
		case *tg.Ref:
			t = m.definition(n.Target)
		case *tg.Pointer:
			t = n.Element
		case *tg.Object:
			for _, f := range n.Fields {
				if f.JSONName == u.Discriminator {
					return true
				}
			}
			return false
		default:
			return false
		}
	}
}
func (m *emitter) emitUnion(name string, u *tg.Union) {
	fields := make([]tg.Field, len(u.Variants))
	for i, v := range u.Variants {
		fields[i].JSONName = v.Implementation.Name
	}
	cases := fieldNames(fields)
	fmt.Fprintf(&m.out, "\npublic indirect enum %s: Sendable {\n", ident(name))
	for i, v := range u.Variants {
		fmt.Fprintf(&m.out, "case %s(%s)\n", ident(cases[i]), ident(m.names[v.Implementation]))
	}
	m.out.WriteString("}\n")
	fmt.Fprintf(&m.out, "fileprivate func _skgoEncodeType_%s(_ value: %s, _ depth: Int) throws -> Any {\ntry _SKGoWire.depth(depth)\nswitch value {\n", name, ident(name))
	for i, v := range u.Variants {
		fmt.Fprintf(&m.out, "case .%s(let member):\nguard var object = try _skgoEncodeType_%s(member, depth + 1) as? [String: Any] else { throw NativeModelError.invalid(\"Expected union object\") }\n", ident(cases[i]), m.names[v.Implementation])
		fmt.Fprintf(&m.out, "if let tag = object[%s], (tag as? String) != %s { throw NativeModelError.invalid(\"Conflicting discriminator\") }\nobject[%s] = %s\nreturn object\n", quote(u.Discriminator), quote(v.Tag), quote(u.Discriminator), quote(v.Tag))
	}
	m.out.WriteString("}\n}\n")
	fmt.Fprintf(&m.out, "fileprivate func _skgoDecodeType_%s(_ value: Any, _ depth: Int) throws -> %s {\ntry _SKGoWire.depth(depth)\nguard var object = value as? [String: Any] else { throw NativeModelError.invalid(\"Expected union object\") }\nlet tag = try _SKGoWire.string(try _SKGoWire.required(object, %s))\nswitch tag {\n", name, ident(name), quote(u.Discriminator))
	for i, v := range u.Variants {
		fmt.Fprintf(&m.out, "case %s:\n", quote(v.Tag))
		if !m.variantHas(u, v) {
			fmt.Fprintf(&m.out, "object.removeValue(forKey: %s)\n", quote(u.Discriminator))
		}
		fmt.Fprintf(&m.out, "return .%s(try _skgoDecodeType_%s(object, depth + 1))\n", ident(cases[i]), m.names[v.Implementation])
	}
	m.out.WriteString("default: throw NativeModelError.invalid(\"Unknown union discriminator\")\n}\n}\n")
}
func (m *emitter) emitCalls(roots []tg.Type, calls []Call) error {
	if len(calls) == 0 {
		return nil
	}
	m.out.WriteString("\npublic struct NativeAPI: Sendable {\nprivate let core: RemoteClient\npublic init(core: RemoteClient) { self.core = core }\n")
	used := map[string]bool{"core": true, "init": true}
	for _, call := range calls {
		if call.Kind != "query" && call.Kind != "command" {
			return fmt.Errorf("%s: unsupported native remote kind %s", call.Name, call.Kind)
		}
		if call.Input < -1 || call.Input >= len(roots) || call.Output < 0 || call.Output >= len(roots) {
			return fmt.Errorf("%s: invalid native root index", call.Name)
		}
		if used[call.Name] {
			return fmt.Errorf("duplicate or reserved Swift call name %s", call.Name)
		}
		used[call.Name] = true
		fmt.Fprintf(&m.out, "/// Kit remote %s\npublic func %s(", call.ID, ident(call.Name))
		if call.Input >= 0 {
			fmt.Fprintf(&m.out, "_ argument: %s", m.typeName(roots[call.Input]))
		}
		fmt.Fprintf(&m.out, ") async throws -> %s {\n", m.typeName(roots[call.Output]))
		if call.Input >= 0 {
			fmt.Fprintf(&m.out, "let argument = try JSONSerialization.data(withJSONObject: _skgoEncodeRoot_%d(argument, 0), options: [.fragmentsAllowed])\n", call.Input)
		}
		arg := "nil"
		if call.Input >= 0 {
			arg = "argument"
		}
		fmt.Fprintf(&m.out, "guard let data = try await core.call(%s, kind: .%s, argument: %s) else { throw NativeModelError.invalid(\"Expected a result\") }\nreturn try _skgoDecodeRoot_%d(JSONSerialization.jsonObject(with: data, options: [.fragmentsAllowed]), 0)\n}\n", quote(call.ID), call.Kind, arg, call.Output)
	}
	m.out.WriteString("}\n")
	return nil
}
