// Code generated by skgo. DO NOT EDIT.

package account

// The functions this package declares, published under names the generated
// bindings package can spell. Each is the function itself and not a wrapper:
// skgo.Refresh finds a query by the code pointer of the function it names.
var (
	// Skgo_layoutLoad is layoutLoad, published as the server load of src/routes/account/+layout.server.ts.
	Skgo_layoutLoad = layoutLoad
	// Skgo_pageLoad is pageLoad, published as the server load of src/routes/account/+page.server.ts.
	Skgo_pageLoad = pageLoad
)
