// Code generated by skgo. DO NOT EDIT.

package app

import (
	context "context"
	skgo "github.com/tylergannon/skgo"
)

func LocalsFrom(ctx context.Context) *Locals { return skgo.RequestLocals[Locals](ctx) }
