// Code generated by skgo. DO NOT EDIT.

package profileeditor

import (
	skgo "github.com/tylergannon/skgo"
	appstate "github.com/tylergannon/skgo/example/internal/app"
	hooks "github.com/tylergannon/skgo/example/web/src"
)

// RouteParams stores converted values. Only accessor reads record dependencies
// on the load invocation that constructed these params.
type RouteParams struct {
	event        *skgo.Event
	valueProfile string
}

func (p RouteParams) Profile() string { skgo.TrackLoadParam(p.event, "profile"); return p.valueProfile }

type RequestEvent = skgo.RequestEvent[RouteParams, appstate.Locals]

func SkgoRequestEvent(event *skgo.Event) RequestEvent {
	return RequestEvent{Event: event, Locals: appstate.LocalsFrom(event.Request().Context()), Params: RouteParams{event: event,
		valueProfile: skgo.LoadParamValue[string](event, "profile"),
	}}
}

func SkgoParamMatchers() map[string]skgo.ParamMatcher {
	return map[string]skgo.ParamMatcher{
		"Order": func(value string) (any, bool) { return hooks.Order(value) },
	}
}

// The functions this package declares, published under names the generated
// bindings package can spell. Each is the function itself and not a wrapper:
// skgo.Refresh finds a query by the code pointer of the function it names.
var (
	// Skgo_pageLoad is pageLoad, published as the server load of src/routes/actions/profiles/[profile]/+page.server.ts.
	Skgo_pageLoad = pageLoad
	Skgo_save     = save
)
