// Code generated by skgo. DO NOT EDIT.
import type { RequestHandler } from "@sveltejs/kit";
// Every body throws. These handlers are implemented in Go.
// Every response is produced by the Go handler rather than
// this module. Kit reads the export names to learn which methods the route
// answers.
const unimplemented = (): never => {
  throw new Error("skgo: implemented in Go");
};

export const GET: RequestHandler = unimplemented;

export const POST: RequestHandler = unimplemented;

export const QUERY: RequestHandler = unimplemented;
