// Code generated by skgo. DO NOT EDIT.
// Every body throws. This route is implemented in Go, and skgo answers it
// itself, so any real response is proof the Go handler replied rather than
// this module. Kit reads the export names to learn which methods the route
// answers; it never calls them.
const unimplemented = (): never => {
	throw new Error('skgo: implemented in Go');
};

export const GET = (): never => unimplemented();

export const POST = (): never => unimplemented();

export const QUERY = (): never => unimplemented();
