// Code generated by skgo. DO NOT EDIT.

package todosapi

// The functions this package declares, published under names the generated
// bindings package can spell. Each is the function itself and not a wrapper:
// skgo.Refresh finds a query by the code pointer of the function it names.
var (
	// Skgo_list is list, published as GET /api/todos.
	Skgo_list = list
	// Skgo_add is add, published as POST /api/todos.
	Skgo_add = add
)
