// Code generated by skgo. DO NOT EDIT.
import { getRequestEvent, prerender } from '$app/server';

// Application bodies stay in Go. Runtime stubs throw; the prerender
// callback reaches Go only through the adapter's build bridge.
const unimplemented = (): never => {
	throw new Error('skgo: implemented in Go');
};

const prerenderFromGo = (module: string, name: string, arg: unknown): Promise<any> => {
	const event = getRequestEvent();
	const bridge = (event.platform as { skgoPrerenderRemote?: (module: string, name: string, arg: unknown, event: import('@sveltejs/kit').RequestEvent) => Promise<any> } | undefined)?.skgoPrerenderRemote;
	return bridge?.(module, name, arg, event) ?? unimplemented();
};

export const buildReceipt = prerender('unchecked', async (arg: string): Promise<string> => prerenderFromGo("src/routes/about/about.remote.ts", "buildReceipt", arg));
