// Code generated by skgo. DO NOT EDIT.
import { prerender } from "$app/server";

// Every body throws. These functions are implemented in Go, and skgo
// answers their endpoints itself, so anything that renders in the browser
// is proof the Go handler replied rather than this module.
const unimplemented = (): never => {
  throw new Error("skgo: implemented in Go");
};

export const buildReceipt = prerender("unchecked", async (_arg: string): Promise<string> =>
  unimplemented(),
);
