// Code generated by skgo. DO NOT EDIT.
import { query } from '$app/server';
import type { Input } from './types';

export type { Input };

// Every body throws. These functions are implemented in Go, and skgo
// answers their endpoints itself, so anything that renders in the browser
// is proof the Go handler replied rather than this module.
const unimplemented = (): never => {
	throw new Error('skgo: implemented in Go');
};

export const getBatch = query.batch('unchecked', (_args: Input[]): ((arg: Input, idx: number) => string) => unimplemented());

export const getDependent = query('unchecked', (_arg: string): string => unimplemented());

export const getHeld = query('unchecked', (_arg: Input): string => unimplemented());

export const getSeed = query('unchecked', (_arg: string): string => unimplemented());

export const getValue = query('unchecked', (_arg: Input): string => unimplemented());

export const watchValue = query.live('unchecked', (_arg: Input): AsyncIterable<string> => unimplemented());
