// Code generated by skgo. DO NOT EDIT.

package asyncssr

// The functions this package declares, published under names the generated
// bindings package can spell. Each is the function itself and not a wrapper:
// skgo.Refresh finds a query by the code pointer of the function it names.
var (
	// Skgo_getBatch is getBatch, published as src/routes/async-ssr/[mode]/[group]/probe.remote.ts#getBatch.
	Skgo_getBatch = getBatch
	// Skgo_getDependent is getDependent, published as src/routes/async-ssr/[mode]/[group]/probe.remote.ts#getDependent.
	Skgo_getDependent = getDependent
	// Skgo_getHeld is getHeld, published as src/routes/async-ssr/[mode]/[group]/probe.remote.ts#getHeld.
	Skgo_getHeld = getHeld
	// Skgo_getSeed is getSeed, published as src/routes/async-ssr/[mode]/[group]/probe.remote.ts#getSeed.
	Skgo_getSeed = getSeed
	// Skgo_getValue is getValue, published as src/routes/async-ssr/[mode]/[group]/probe.remote.ts#getValue.
	Skgo_getValue = getValue
	// Skgo_watchValue is watchValue, published as src/routes/async-ssr/[mode]/[group]/probe.remote.ts#watchValue.
	Skgo_watchValue = watchValue
)

type (
	// SkgoArg_getBatch is the type getBatch takes.
	SkgoArg_getBatch = Input
	// SkgoOut_watchValue is the type watchValue yields.
	SkgoOut_watchValue = string
)
