// Code generated by skgo. DO NOT EDIT.

package fatalapi

// The functions this package declares, published under names the generated
// bindings package can spell. Each is the function itself and not a wrapper:
// skgo.Refresh finds a query by the code pointer of the function it names.
var (
	// Skgo_fail is fail, published as GET /api/fatal.
	Skgo_fail = fail
)
