// Code generated by skgo. DO NOT EDIT.
//
// SvelteKit names a route directory after the URL it serves, so the tree
// below contains directories Go cannot spell in an import path. This file
// is a module boundary and nothing else: it stops the application module's
// `./...` from ever descending here. The packages themselves are imported
// through the generated link tree, and this module is never built.

module github.com/tylergannon/skgo/survey/web/src/routes
