// Code generated by skgo. DO NOT EDIT.
import { command, query } from '$app/server';
import type { None } from '../lib/skgo/skgo/types';
import type { Home, Session, SignInResult, Whoami } from './types';

export type { Home, None, Session, SignInResult, Whoami };

// Every body throws. These functions are implemented in Go, and skgo
// answers their endpoints itself, so anything that renders in the browser
// is proof the Go handler replied rather than this module.
const unimplemented = (): never => {
	throw new Error('skgo: implemented in Go');
};

export const getHome = query((): Home => unimplemented());

export const getSession = query((): Session => unimplemented());

export const recordVisit = command((): Session => unimplemented());

export const signIn = command('unchecked', (_arg: string): SignInResult => unimplemented());

export const signOut = command((): None => unimplemented());

export const whoami = query((): Whoami => unimplemented());
