// Code generated by skgo. DO NOT EDIT.

package routes

import "github.com/tylergannon/skgo"

// SkgoRemotes returns the remote functions declared in this package.
func SkgoRemotes() []*skgo.Remote {
	return []*skgo.Remote{
		skgo.NewQuery("src/routes/session.remote.ts", "getHome", getHome),
		skgo.NewQuery("src/routes/session.remote.ts", "getSession", getSession),
		skgo.NewCommand("src/routes/session.remote.ts", "recordVisit", recordVisit),
		skgo.NewCommand("src/routes/session.remote.ts", "signIn", signIn),
		skgo.NewCommand("src/routes/session.remote.ts", "signOut", signOut),
		skgo.NewQuery("src/routes/session.remote.ts", "whoami", whoami),
	}
}
