//go:build jsonschema

// Code generated by skgo. DO NOT EDIT.

package routes

import (
	"encoding/json"

	"github.com/tylergannon/polytype"
)

// Stubs so the package compiles before polytype has run.
func (Home) Schema() json.RawMessage         { panic("not implemented") }
func (Session) Schema() json.RawMessage      { panic("not implemented") }
func (SignInResult) Schema() json.RawMessage { panic("not implemented") }
func (Whoami) Schema() json.RawMessage       { panic("not implemented") }

var (
	_ = polytype.Declare(Home.Schema)
	_ = polytype.Declare(Session.Schema)
	_ = polytype.Declare(SignInResult.Schema)
	_ = polytype.Declare(Whoami.Schema)
)
