// Code generated by polytype. DO NOT EDIT.

/**
 * Home is the root page's data.
 */
export type Home = {
  "greeting": string;
  "messageCount": number;
};

/**
 * Session is what the layout shows: who the visitor is and how many times they have arrived.
 */
export type Session = {
  "user": string;
  "visits": number;
};

/**
 * SignInResult mirrors what the junkyard action returned through `form`.
 */
export type SignInResult = {
  "name": string;
  "error": string;
};

/**
 * Whoami is the payload of the /whoami page.
 */
export type Whoami = {
  "url": string;
  "clientAddress": string;
  "requestId": string;
  "user": string;
  "host": string;
};
