// Code generated by skgo. DO NOT EDIT.

package main

import (
	"log"
	"os"

	"github.com/tylergannon/skgo"
	generated "github.com/tylergannon/skgo/example/internal/skgo"
)

func main() {
	if err := skgo.RunPrerenderLoad(os.Stdin, os.Stdout, generated.Transport(), generated.Loads()...); err != nil {
		log.Fatal(err)
	}
}
