// Code generated by skgo. DO NOT EDIT.

package main

import (
	skgo "github.com/tylergannon/skgo"
	generated "github.com/tylergannon/skgo/example/internal/skgo"
	log "log"
)

func main() {
	if err := skgo.RunPrerenderService(generated.Transport(), generated.Loads(), generated.Remotes()); err != nil {
		log.Fatal(err)
	}
}
