// Code generated by skgo. DO NOT EDIT.
import type { RequestEvent } from "@sveltejs/kit";

export const load = async (
  event: RequestEvent,
): Promise<{ slug: string; filter: string; serial: number }> => {
  throw new Error("skgo: implemented in Go");
};
