// Code generated by skgo. DO NOT EDIT.
import type { RequestEvent } from "@sveltejs/kit";

export const load = async (
  event: RequestEvent,
): Promise<{ token: string; route: string; cookie: string }> => {
  throw new Error("skgo: implemented in Go");
};

// Kit reads these exports for action typing; Go answers every submission.
export const actions = {
  default: async (_event: { request: Request }): Promise<{ receipt: string }> => {
    throw new Error("skgo: action implemented in Go");
  },
};
