// Code generated by skgo. DO NOT EDIT.
import { building } from "$app/env";
import { error, redirect } from "@sveltejs/kit";
import type { Money } from "../../hooks";
import type { Profile } from "./types";

// Go answers this load at runtime. Kit calls it during prerendering,
// when the adapter's build-only Go process supplies its result.
const unimplemented = (route: string): never => {
  throw new Error("skgo: implemented in Go");
};

const buildLoad = async (
  module: string,
  source: string,
  event: import("@sveltejs/kit").RequestEvent,
): Promise<any> => {
  const bridge = (
    event.platform as
      | {
          skgoPrerenderLoad?: (
            module: string,
            source: string,
            event: import("@sveltejs/kit").RequestEvent,
          ) => Promise<any>;
        }
      | undefined
  )?.skgoPrerenderLoad;
  if (!bridge) throw new Error("skgo: prerender Go load bridge unavailable");
  const answer = await bridge(module, source, event);
  if (answer.redirect) redirect(answer.redirect.status, answer.redirect.location);
  if (answer.error) error(answer.error.status, answer.error.message);
  if (answer.data === undefined) throw new Error("skgo: prerender Go load returned no data");
  return answer.data;
};

export const load = async (
  event: import("@sveltejs/kit").RequestEvent,
): Promise<{ profile: Profile; actionCookie: string }> =>
  building
    ? buildLoad("src/routes/actions/+page.server.ts", "src/routes/actions/page.server.go", event)
    : unimplemented(event.url.pathname);

// Kit reads these exports for action typing; Go answers every submission.
export const actions = {
  archive: async (_event: { request: Request }): Promise<void> => {
    throw new Error("skgo: action implemented in Go");
  },
  forbidden: async (_event: { request: Request }): Promise<void> => {
    throw new Error("skgo: action implemented in Go");
  },
  inspect: async (_event: {
    request: Request;
  }): Promise<{ interests: Array<string>; submitter: string; encoding: string; price: Money }> => {
    throw new Error("skgo: action implemented in Go");
  },
  remember: async (_event: { request: Request }): Promise<{ receipt: string }> => {
    throw new Error("skgo: action implemented in Go");
  },
  remote: async (_event: { request: Request }): Promise<{ receipt: string }> => {
    throw new Error("skgo: action implemented in Go");
  },
  save: async (_event: {
    request: Request;
  }): Promise<
    | { receipt: string; price: Money }
    | import("@sveltejs/kit").ActionFailure<{
        name: string;
        email: string;
        biography: string;
        emailError: string;
      }>
  > => {
    throw new Error("skgo: action implemented in Go");
  },
  signIn: async (_event: { request: Request }): Promise<void> => {
    throw new Error("skgo: action implemented in Go");
  },
  unavailable: async (_event: { request: Request }): Promise<void> => {
    throw new Error("skgo: action implemented in Go");
  },
  upload: async (_event: {
    request: Request;
  }): Promise<{
    filename: string;
    bytes: number;
    sha256: string;
    interests: Array<string>;
    submitter: string;
    price: Money;
  }> => {
    throw new Error("skgo: action implemented in Go");
  },
};
