// Code generated by skgo. DO NOT EDIT.
import type { RequestEvent, ActionFailure } from "@sveltejs/kit";
import type { Money } from "../../hooks";
import type { Profile } from "./types";

export const load = async (
  event: RequestEvent,
): Promise<{ profile: Profile; actionCookie: string }> => {
  throw new Error("skgo: implemented in Go");
};

// Kit reads these exports for action typing; Go answers every submission.
export const actions = {
  archive: async (_event: { request: Request }): Promise<void> => {
    throw new Error("skgo: action implemented in Go");
  },
  forbidden: async (_event: { request: Request }): Promise<void> => {
    throw new Error("skgo: action implemented in Go");
  },
  inspect: async (_event: {
    request: Request;
  }): Promise<{ interests: Array<string>; submitter: string; encoding: string; price: Money }> => {
    throw new Error("skgo: action implemented in Go");
  },
  remember: async (_event: { request: Request }): Promise<{ receipt: string }> => {
    throw new Error("skgo: action implemented in Go");
  },
  remote: async (_event: { request: Request }): Promise<{ receipt: string }> => {
    throw new Error("skgo: action implemented in Go");
  },
  save: async (_event: {
    request: Request;
  }): Promise<
    | { receipt: string; price: Money }
    | ActionFailure<{ name: string; email: string; biography: string; emailError: string }>
  > => {
    throw new Error("skgo: action implemented in Go");
  },
  signIn: async (_event: { request: Request }): Promise<void> => {
    throw new Error("skgo: action implemented in Go");
  },
  unavailable: async (_event: { request: Request }): Promise<void> => {
    throw new Error("skgo: action implemented in Go");
  },
  upload: async (_event: {
    request: Request;
  }): Promise<{
    filename: string;
    bytes: number;
    sha256: string;
    interests: Array<string>;
    submitter: string;
    price: Money;
  }> => {
    throw new Error("skgo: action implemented in Go");
  },
};
