// Code generated by skgo. DO NOT EDIT.
import { form } from '$app/server';
import type { RemoteNote, RemoteReceipt } from './types';

export type { RemoteNote, RemoteReceipt };

// Every body throws. These functions are implemented in Go, and skgo
// answers their endpoints itself, so anything that renders in the browser
// is proof the Go handler replied rather than this module.
const unimplemented = (): never => {
	throw new Error('skgo: implemented in Go');
};

export const sendRemoteNote = form('unchecked', (_arg: RemoteNote): RemoteReceipt => unimplemented());
