// Code generated by polytype. DO NOT EDIT.

export type Profile = {
  "name": string;
  "email": string;
  "biography": string;
  "state": string;
};

export type RemoteNote = {
  "name": string;
};

export type RemoteReceipt = {
  "message": string;
};
