// Code generated by skgo. DO NOT EDIT.

package eventlayout

import (
	skgo "github.com/tylergannon/skgo"
	appstate "github.com/tylergannon/skgo/example/internal/app"
	hooks "github.com/tylergannon/skgo/example/web/src"
)

// LayoutParams stores this layout's local and participating-page values.
type LayoutParams struct {
	event        *skgo.Event
	valueItem    *string
	valueSection string
}

func (p LayoutParams) Item() *string { skgo.TrackLoadParam(p.event, "item"); return p.valueItem }
func (p LayoutParams) Section() string {
	skgo.TrackLoadParam(p.event, "section")
	return p.valueSection
}

type LayoutRequestEvent = skgo.RequestEvent[LayoutParams, appstate.Locals]

func SkgoLayoutRequestEvent(event *skgo.Event) LayoutRequestEvent {
	return LayoutRequestEvent{Event: event, Locals: appstate.LocalsFrom(event.Request().Context()), Params: skgoLayoutParams(event)}
}
func skgoLayoutParams(event *skgo.Event) LayoutParams {
	p := LayoutParams{event: event}
	p.valueItem = skgo.OptionalLoadParamValue[string](event, "item")
	p.valueSection = skgo.LoadParamValue[string](event, "section")

	return p
}
func SkgoParamMatchers() map[string]skgo.ParamMatcher {
	return map[string]skgo.ParamMatcher{
		"Order": func(value string) (any, bool) { return hooks.Order(value) },
	}
}

// The functions this package declares, published under names the generated
// bindings package can spell. Each is the function itself and not a wrapper:
// skgo.Refresh finds a query by the code pointer of the function it names.
var (
	// Skgo_layoutLoad is layoutLoad, published as the server load of src/routes/event-layout/[section]/+layout.server.ts.
	Skgo_layoutLoad = layoutLoad
)
