// Code generated by skgo. DO NOT EDIT.
import { building } from '$app/env';
import type { Money } from '../../../../hooks';
import type { Profile } from '../../types';

// The body throws. This load is implemented in Go, and skgo answers
// __data.json itself, so anything that renders in the browser is proof the
// Go handler replied rather than this module. Kit normally reads the export
// only to learn that the route has server data. Its prerenderer does call it,
// which is refused until Go loads can run during a build (#81).
const unimplemented = (route: string): never => {
	if (building) throw new Error('skgo: route ' + route + ' is prerendered, and its branch has a Go server load at ' + "src/routes/actions/options/no-client/page.server.go" + '; skgo cannot answer a load while kit prerenders (#81). Remove the prerender or move the load');
	throw new Error('skgo: implemented in Go');
};

export const load = (event: { url: URL }): { profile: Profile; actionCookie: string } => unimplemented(event.url.pathname);

// Kit reads these exports for action typing; Go answers every submission.
export const actions = {
	forbidden: async (_event: { request: Request }): Promise<void> => { throw new Error('skgo: action implemented in Go'); },
	save: async (_event: { request: Request }): Promise<{ receipt: string; price: Money } | import('@sveltejs/kit').ActionFailure<{ name: string; email: string; biography: string; emailError: string }>> => { throw new Error('skgo: action implemented in Go'); },
	unavailable: async (_event: { request: Request }): Promise<void> => { throw new Error('skgo: action implemented in Go'); },
};
