// Code generated by skgo. DO NOT EDIT.
import type { RequestEvent, ActionFailure } from "@sveltejs/kit";
import type { Money } from "../../../../hooks";
import type { Profile } from "../../types";

export const load = async (
  event: RequestEvent,
): Promise<{ profile: Profile; actionCookie: string }> => {
  throw new Error("skgo: implemented in Go");
};

// Kit reads these exports for action typing; Go answers every submission.
export const actions = {
  forbidden: async (_event: { request: Request }): Promise<void> => {
    throw new Error("skgo: action implemented in Go");
  },
  save: async (_event: {
    request: Request;
  }): Promise<
    | { receipt: string; price: Money }
    | ActionFailure<{ name: string; email: string; biography: string; emailError: string }>
  > => {
    throw new Error("skgo: action implemented in Go");
  },
  signIn: async (_event: { request: Request }): Promise<void> => {
    throw new Error("skgo: action implemented in Go");
  },
  unavailable: async (_event: { request: Request }): Promise<void> => {
    throw new Error("skgo: action implemented in Go");
  },
};
