// Code generated by skgo. DO NOT EDIT.

package command

import "github.com/tylergannon/skgo"

// SkgoRemotes returns the remote functions declared in this package.
func SkgoRemotes() []*skgo.Remote {
	return []*skgo.Remote{
		skgo.NewCommandNoArg("src/routes/error/command/command.remote.ts", "bumpTally", bumpTally),
		skgo.NewQueryNoArg("src/routes/error/command/command.remote.ts", "getTally", getTally),
	}
}

// SkgoLoads returns the server loads declared in this package.
func SkgoLoads() []*skgo.ServerLoad {
	return []*skgo.ServerLoad{}
}

// SkgoEndpoints returns the server routes declared in this package.
func SkgoEndpoints() []*skgo.Endpoint {
	return []*skgo.Endpoint{}
}
