// Code generated by skgo. DO NOT EDIT.

package command

// The functions this package declares, published under names the generated
// bindings package can spell. Each is the function itself and not a wrapper:
// skgo.Refresh finds a query by the code pointer of the function it names.
var (
	// Skgo_bumpTally is bumpTally, published as src/routes/error/command/command.remote.ts#bumpTally.
	Skgo_bumpTally = bumpTally
	// Skgo_getTally is getTally, published as src/routes/error/command/command.remote.ts#getTally.
	Skgo_getTally = getTally
)
