// Code generated by skgo. DO NOT EDIT.

package slow

import "github.com/tylergannon/skgo"

// SkgoRemotes returns the remote functions declared in this package.
func SkgoRemotes() []*skgo.Remote {
	return []*skgo.Remote{
		skgo.NewQuery("src/routes/slow/slow.remote.ts", "getSlowPart", getSlowPart),
	}
}
