// Code generated by skgo. DO NOT EDIT.

package item

import "github.com/tylergannon/skgo"

// SkgoRemotes returns the remote functions declared in this package.
func SkgoRemotes() []*skgo.Remote {
	return []*skgo.Remote{
		skgo.NewQuery("src/routes/items/[id]/item.remote.ts", "getItem", getItem),
	}
}
