// Code generated by polytype. DO NOT EDIT.

/**
 * Item is one thing in the catalogue.
 */
export type Item = {
  /**
   * ID is the value SvelteKit matched into the `[id]` segment.
   */
  "id": string;
  /**
   * Name is what the page shows.
   */
  "name": string;
  /**
   * Colocated says where the Go that answered lives, so the page can show that a bracketed directory really is the source of the answer.
   */
  "colocated": string;
};
