// Code generated by skgo. DO NOT EDIT.
import { command, query } from '$app/server';
import type { Ack, Banner, Note, Write } from './types';

export type { Ack, Banner, Note, Write };

// Every body throws. These functions are implemented in Go, and skgo
// answers their endpoints itself, so anything that renders in the browser
// is proof the Go handler replied rather than this module.
const unimplemented = (): never => {
	throw new Error('skgo: implemented in Go');
};

export const getBanner = query((): Banner => unimplemented());

export const getNote = query('unchecked', (_arg: string): Note => unimplemented());

export const writeNotes = command('unchecked', (_arg: Write): Ack => unimplemented());
