//go:build jsonschema

// Code generated by skgo. DO NOT EDIT.

package gate

import (
	"encoding/json"

	"github.com/tylergannon/polytype"
)

// Stubs so the package compiles before polytype has run.
func (Ack) Schema() json.RawMessage    { panic("not implemented") }
func (Banner) Schema() json.RawMessage { panic("not implemented") }
func (Note) Schema() json.RawMessage   { panic("not implemented") }
func (Write) Schema() json.RawMessage  { panic("not implemented") }

var (
	_ = polytype.Declare(Ack.Schema)
	_ = polytype.Declare(Banner.Schema)
	_ = polytype.Declare(Note.Schema)
	_ = polytype.Declare(Write.Schema)
)
