// Code generated by skgo. DO NOT EDIT.

package gate

import "github.com/tylergannon/skgo"

// SkgoRemotes returns the remote functions declared in this package.
func SkgoRemotes() []*skgo.Remote {
	return []*skgo.Remote{
		skgo.NewQueryNoArg("src/routes/todos/gate/gate.remote.ts", "getBanner", getBanner),
		skgo.NewQuery("src/routes/todos/gate/gate.remote.ts", "getNote", getNote),
		skgo.NewCommand("src/routes/todos/gate/gate.remote.ts", "writeNotes", writeNotes),
	}
}

// SkgoLoads returns the server loads declared in this package.
func SkgoLoads() []*skgo.ServerLoad {
	return []*skgo.ServerLoad{}
}

// SkgoEndpoints returns the server routes declared in this package.
func SkgoEndpoints() []*skgo.Endpoint {
	return []*skgo.Endpoint{}
}
