// Code generated by skgo. DO NOT EDIT.

package gate

// The functions this package declares, published under names the generated
// bindings package can spell. Each is the function itself and not a wrapper:
// skgo.Refresh finds a query by the code pointer of the function it names.
var (
	// Skgo_getBanner is getBanner, published as src/routes/todos/gate/gate.remote.ts#getBanner.
	Skgo_getBanner = getBanner
	// Skgo_getNote is getNote, published as src/routes/todos/gate/gate.remote.ts#getNote.
	Skgo_getNote = getNote
	// Skgo_writeNotes is writeNotes, published as src/routes/todos/gate/gate.remote.ts#writeNotes.
	Skgo_writeNotes = writeNotes
)
