// Code generated by polytype. DO NOT EDIT.

/**
 * Ack is what the command returns, so the page can show that it landed even when nothing else on the page moved.
 */
export type Ack = {
  /**
   * Wrote is how many values the command changed. It is always three, which is the point: everything was written, and what the page shows afterwards is a question about refreshes rather than about writes.
   */
  "wrote": number;
};

/**
 * Banner is the page's third panel, and a different query entirely — not another instance of getNote. A handler's limit is per query function, so the only thing that keeps the banner from being refreshed is that nothing named it.
 */
export type Banner = {
  /**
   * Text is what was last written to the banner.
   */
  "text": string;
};

/**
 * Note is one panel's text. Two instances of getNote are on the page, told apart only by their argument, which is the key kit's client caches under.
 */
export type Note = {
  /**
   * Name is which note this is: "left" or "right".
   */
  "name": string;
  /**
   * Text is what was last written to it.
   */
  "text": string;
};

/**
 * Write is the argument of the writeNotes command: everything the page changes in one go.
 */
export type Write = {
  /**
   * Left is the new text of the left note.
   */
  "left": string;
  /**
   * Right is the new text of the right note.
   */
  "right": string;
  /**
   * Banner is the new banner text.
   */
  "banner": string;
};
