// Code generated by skgo. DO NOT EDIT.

package requestfetchapi

// The functions this package declares, published under names the generated
// bindings package can spell. Each is the function itself and not a wrapper:
// skgo.Refresh finds a query by the code pointer of the function it names.
var (
	// Skgo_fact is fact, published as GET /api/request-fetch.
	Skgo_fact = fact
)
