// Code generated by skgo. DO NOT EDIT.

package skgo

import (
	"context"
	"fmt"
	"reflect"

	"github.com/tylergannon/skgo"

	skgotp0 "github.com/tylergannon/skgo/example/businesslogic"
	skgo1 "github.com/tylergannon/skgo/example/internal/skgo/links/onzggl3sn52xizlt"
	skgo2 "github.com/tylergannon/skgo/example/internal/skgo/links/onzggl3sn52xizltf4ug2ylsnnsxi2lom4us64dsnfrws3th"
	skgo3 "github.com/tylergannon/skgo/example/internal/skgo/links/onzggl3sn52xizltf52g6zdpom"
	skgo4 "github.com/tylergannon/skgo/example/internal/skgo/links/onzggl3sn52xizltf52g6zdpomxwoylumu"
	skgo5 "github.com/tylergannon/skgo/example/internal/skgo/links/onzggl3sn52xizltf52hs4dfmqwwizlqmvxgizlomnuwk4zplnqt2t3smrsxexjplnrd2t3smrsxexjplnuwo3tpojswixi"
	skgo6 "github.com/tylergannon/skgo/example/internal/skgo/links/onzggl3sn52xizltf52hs4dfmqwwy33bmqxvw3tvnvrgk4r5j5zgizlslu"
	skgo7 "github.com/tylergannon/skgo/example/internal/skgo/links/onzggl3sn52xizltf5qwe33voq"
	skgo8 "github.com/tylergannon/skgo/example/internal/skgo/links/onzggl3sn52xizltf5qwg5djn5xhg"
	skgo9 "github.com/tylergannon/skgo/example/internal/skgo/links/onzggl3sn52xizltf5qwg5djn5xhgl3dojxxg4zpojswgzljozsq"
	skgo10 "github.com/tylergannon/skgo/example/internal/skgo/links/onzggl3sn52xizltf5qwg5djn5xhgl3emvtgc5lmoq"
	skgo11 "github.com/tylergannon/skgo/example/internal/skgo/links/onzggl3sn52xizltf5qwg5djn5xhgl3emvtgc5lmoqxxgylwmvsa"
	skgo12 "github.com/tylergannon/skgo/example/internal/skgo/links/onzggl3sn52xizltf5qwg5djn5xhgl3pob2gs33oomxw43znmnwgszlooq"
	skgo13 "github.com/tylergannon/skgo/example/internal/skgo/links/onzggl3sn52xizltf5qwg5djn5xhgl3pob2gs33oomxw43znonzxe"
	skgo14 "github.com/tylergannon/skgo/example/internal/skgo/links/onzggl3sn52xizltf5qwg5djn5xhgl3qojxwm2lmmvzs6w3qojxwm2lmmvoq"
	skgo15 "github.com/tylergannon/skgo/example/internal/skgo/links/onzggl3sn52xizltf5qwg5djn5xhgl3tnftw4zlefvuw4"
	skgo16 "github.com/tylergannon/skgo/example/internal/skgo/links/onzggl3sn52xizltf5qwgy3povxhi"
	skgo17 "github.com/tylergannon/skgo/example/internal/skgo/links/onzggl3sn52xizltf5qwgy3povxhil3pojsgk4tt"
	skgo18 "github.com/tylergannon/skgo/example/internal/skgo/links/onzggl3sn52xizltf5qwgy3povxhil3smvzhk3ttf5nxg3dvm5oq"
	skgo19 "github.com/tylergannon/skgo/example/internal/skgo/links/onzggl3sn52xizltf5qwgy3povxhil3torqxizlnmvxhi"
	skgo20 "github.com/tylergannon/skgo/example/internal/skgo/links/onzggl3sn52xizltf5qxa2jpmzqxiylm"
	skgo21 "github.com/tylergannon/skgo/example/internal/skgo/links/onzggl3sn52xizltf5qxa2jpojsxa3dbpewwg33vnz2a"
	skgo22 "github.com/tylergannon/skgo/example/internal/skgo/links/onzggl3sn52xizltf5qxa2jpojsxa3dbpexvw23jnzsf2"
	skgo23 "github.com/tylergannon/skgo/example/internal/skgo/links/onzggl3sn52xizltf5qxa2jpojsxc5lfon2c2ztforrwq"
	skgo24 "github.com/tylergannon/skgo/example/internal/skgo/links/onzggl3sn52xizltf5qxa2jporxwi33t"
	skgo25 "github.com/tylergannon/skgo/example/internal/skgo/links/onzggl3sn52xizltf5qxg6lommwxg43sf5nw233emvos6w3hojxxk4c5"
	skgo26 "github.com/tylergannon/skgo/example/internal/skgo/links/onzggl3sn52xizltf5qxg6lommwxg43sf5rw63tuojxwyl23m5zg65lqlu"
	skgo27 "github.com/tylergannon/skgo/example/internal/skgo/links/onzggl3sn52xizltf5rgc5ddna"
	skgo28 "github.com/tylergannon/skgo/example/internal/skgo/links/onzggl3sn52xizltf5rw63tumfrxi"
	skgo29 "github.com/tylergannon/skgo/example/internal/skgo/links/onzggl3sn52xizltf5sg6y3tf5ns4lroojsxg5c5"
	skgo30 "github.com/tylergannon/skgo/example/internal/skgo/links/onzggl3sn52xizltf5sgk43unfxgc5djn5xhg"
	skgo31 "github.com/tylergannon/skgo/example/internal/skgo/links/onzggl3sn52xizltf5sw24dupe"
	skgo32 "github.com/tylergannon/skgo/example/internal/skgo/links/onzggl3sn52xizltf5sxe4tpoixwe33vnzsgc4tz"
	skgo33 "github.com/tylergannon/skgo/example/internal/skgo/links/onzggl3sn52xizltf5sxe4tpoixwg33nnvqw4za"
	skgo34 "github.com/tylergannon/skgo/example/internal/skgo/links/onzggl3sn52xizltf5sxe4tpoixwk6dqmvrxizle"
	skgo35 "github.com/tylergannon/skgo/example/internal/skgo/links/onzggl3sn52xizltf5sxe4tpoixxezlenfzgky3u"
	skgo36 "github.com/tylergannon/skgo/example/internal/skgo/links/onzggl3sn52xizltf5sxe4tpoixxk3tfpbygky3umvsa"
	skgo37 "github.com/tylergannon/skgo/example/internal/skgo/links/onzggl3sn52xizltf5tw6llemv3a"
	skgo38 "github.com/tylergannon/skgo/example/internal/skgo/links/onzggl3sn52xizltf5tw6llemv3c6zlomryg62looq"
	skgo39 "github.com/tylergannon/skgo/example/internal/skgo/links/onzggl3sn52xizltf5uw45tpnfrwk4y"
	skgo40 "github.com/tylergannon/skgo/example/internal/skgo/links/onzggl3sn52xizltf5uxizlnomxvw2lelu"
	skgo41 "github.com/tylergannon/skgo/example/internal/skgo/links/onzggl3sn52xizltf5wgs5tf"
	skgo42 "github.com/tylergannon/skgo/example/internal/skgo/links/onzggl3sn52xizltf5wwszdenrsxoylsmu"
	skgo43 "github.com/tylergannon/skgo/example/internal/skgo/links/onzggl3sn52xizltf5wwszdenrsxoylsmuxvw43movtv2"
	skgo44 "github.com/tylergannon/skgo/example/internal/skgo/links/onzggl3sn52xizltf5xxa5djn5xgc3a"
	skgo45 "github.com/tylergannon/skgo/example/internal/skgo/links/onzggl3sn52xizltf5yhezlsmvxgizlsf5nxg3dvm5oq"
	skgo46 "github.com/tylergannon/skgo/example/internal/skgo/links/onzggl3sn52xizltf5zgk4lvmvzxillgmv2gg2a"
	skgo47 "github.com/tylergannon/skgo/example/internal/skgo/links/onzggl3sn52xizltf5zwqylen53s6wzofyxhezltoroq"
	skgo48 "github.com/tylergannon/skgo/example/internal/skgo/links/onzggl3sn52xizltf5zxi4tfmfwq"
	skgoMatcher0 "github.com/tylergannon/skgo/example/web/src"
	skgo49 "github.com/tylergannon/skgo/example/web/src/lib"
)

// Matchers returns the app's route matchers, including routes without server loads.
func Matchers() map[string]skgo.ParamMatcher {
	return map[string]skgo.ParamMatcher{
		"Order": func(value string) (any, bool) { return skgoMatcher0.Order(value) },
	}
}

// remote_signIn answers src/lib/auth.remote.ts#signIn, a command.
//
// The argument is decoded by DecodeRoot0, generated by polytype for signIn's
// own parameter type: a shape it does not admit is a 400 naming the path,
// never a zero value.
// The result is encoded by EncodeRoot1, generated for its result type.
func remote_signIn(ctx context.Context, call skgo.Call) (any, error) {
	if err := skgo.RequireArgument(call); err != nil {
		return nil, err
	}
	in, err := DecodeRoot0(call.Arg)
	if err != nil {
		return nil, skgo.BadRequest(err)
	}
	out, err := skgo49.Skgo_signIn(ctx, in)
	if err != nil {
		return nil, err
	}
	return EncodeRoot1(out)
}

// requestedArg_signIn decodes one instance's argument for skgo.Requested, with the same
// decoder remote_signIn uses.
func requestedArg_signIn(arg any) (any, error) {
	in, err := DecodeRoot0(arg)
	if err != nil {
		return nil, skgo.BadRequest(err)
	}
	return in, nil
}

// remote_signOut answers src/lib/auth.remote.ts#signOut, a command.
//
// It takes no argument, so any argument at all is refused — kit's own
// validator for a function declared without one answers 400 too.
// The result is encoded by EncodeRoot1, generated for its result type.
func remote_signOut(ctx context.Context, call skgo.Call) (any, error) {
	if err := skgo.RefuseArgument(call); err != nil {
		return nil, err
	}
	out, err := skgo49.Skgo_signOut(ctx)
	if err != nil {
		return nil, err
	}
	return EncodeRoot1(out)
}

// remote_whoami answers src/lib/auth.remote.ts#whoami, a query.
//
// It takes no argument, so any argument at all is refused — kit's own
// validator for a function declared without one answers 400 too.
// The result is encoded by EncodeRoot1, generated for its result type.
func remote_whoami(ctx context.Context, call skgo.Call) (any, error) {
	if err := skgo.RefuseArgument(call); err != nil {
		return nil, err
	}
	out, err := skgo49.Skgo_whoami(ctx)
	if err != nil {
		return nil, err
	}
	return EncodeRoot1(out)
}

// remote_getPlans answers src/routes/(marketing)/pricing/pricing.remote.ts#getPlans, a query.
//
// It takes no argument, so any argument at all is refused — kit's own
// validator for a function declared without one answers 400 too.
// The result can reach a type the app transports, so it goes to devalue as
// itself and the transport hook's reducer puts it on the wire.
func remote_getPlans(ctx context.Context, call skgo.Call) (any, error) {
	if err := skgo.RefuseArgument(call); err != nil {
		return nil, err
	}
	out, err := skgo2.Skgo_getPlans(ctx)
	if err != nil {
		return nil, err
	}
	return call.Transported(out)
}

// remote_getSpotlight answers src/routes/(marketing)/pricing/pricing.remote.ts#getSpotlight, a query.
//
// It takes no argument, so any argument at all is refused — kit's own
// validator for a function declared without one answers 400 too.
// The result can reach a type the app transports, so it goes to devalue as
// itself and the transport hook's reducer puts it on the wire.
func remote_getSpotlight(ctx context.Context, call skgo.Call) (any, error) {
	if err := skgo.RefuseArgument(call); err != nil {
		return nil, err
	}
	out, err := skgo2.Skgo_getSpotlight(ctx)
	if err != nil {
		return nil, err
	}
	return call.Transported(out)
}

// remote_quoteFor answers src/routes/(marketing)/pricing/pricing.remote.ts#quoteFor, a command.
//
// The argument is decoded by DecodeRoot2, generated by polytype for quoteFor's
// own parameter type: a shape it does not admit is a 400 naming the path,
// never a zero value.
// The result is encoded by EncodeRoot3, generated for its result type.
func remote_quoteFor(ctx context.Context, call skgo.Call) (any, error) {
	if err := skgo.RequireArgument(call); err != nil {
		return nil, err
	}
	in, err := DecodeRoot2(call.Arg)
	if err != nil {
		return nil, skgo.BadRequest(err)
	}
	out, err := skgo2.Skgo_quoteFor(ctx, in)
	if err != nil {
		return nil, err
	}
	return EncodeRoot3(out)
}

// requestedArg_quoteFor decodes one instance's argument for skgo.Requested, with the same
// decoder remote_quoteFor uses.
func requestedArg_quoteFor(arg any) (any, error) {
	in, err := DecodeRoot2(arg)
	if err != nil {
		return nil, skgo.BadRequest(err)
	}
	return in, nil
}

// remote_buildReceipt answers src/routes/about/about.remote.ts#buildReceipt, a prerender.
//
// The argument is decoded by DecodeRoot0, generated by polytype for buildReceipt's
// own parameter type: a shape it does not admit is a 400 naming the path,
// never a zero value.
// The result is encoded by EncodeRoot0, generated for its result type.
func remote_buildReceipt(ctx context.Context, call skgo.Call) (any, error) {
	if err := skgo.RequireArgument(call); err != nil {
		return nil, err
	}
	in, err := DecodeRoot0(call.Arg)
	if err != nil {
		return nil, skgo.BadRequest(err)
	}
	out, err := skgo7.Skgo_buildReceipt(ctx, in)
	if err != nil {
		return nil, err
	}
	return EncodeRoot0(out)
}

// requestedArg_buildReceipt decodes one instance's argument for skgo.Requested, with the same
// decoder remote_buildReceipt uses.
func requestedArg_buildReceipt(arg any) (any, error) {
	in, err := DecodeRoot0(arg)
	if err != nil {
		return nil, skgo.BadRequest(err)
	}
	return in, nil
}

// remote_sendRemoteNote answers src/routes/actions/coexist.remote.ts#sendRemoteNote, a form.
//
// A form's submission is assigned onto the handler's own argument type:
// kit posts a form as binary form data, which can carry an uploaded File,
// and a File is not a value polytype describes.
// The result is encoded by EncodeRoot4, generated for its result type.
func remote_sendRemoteNote(ctx context.Context, call skgo.Call) (any, error) {
	var in skgo8.SkgoArg_sendRemoteNote
	if err := skgo.DecodeForm(call.Arg, &in); err != nil {
		return nil, err
	}
	out, err := skgo8.Skgo_sendRemoteNote(ctx, in)
	if err != nil {
		return nil, err
	}
	return EncodeRoot4(out)
}

// remote_getBatch answers src/routes/async-ssr/[mode]/[group]/probe.remote.ts#getBatch, a query.batch.
//
// The argument is decoded by DecodeRoot5, generated by polytype for getBatch's
// own parameter type: a shape it does not admit is a 400 naming the path,
// never a zero value.
// The result is encoded by EncodeRoot0, generated for its result type.
func remote_getBatch(ctx context.Context, calls []skgo.Call) ([]any, error) {
	in := make([]skgo25.SkgoArg_getBatch, len(calls))
	for i, call := range calls {
		if err := skgo.RequireArgument(call); err != nil {
			return nil, err
		}
		decoded, err := DecodeRoot5(call.Arg)
		if err != nil {
			return nil, skgo.BadRequest(err)
		}
		in[i] = decoded
	}
	outs, err := skgo25.Skgo_getBatch(ctx, in)
	if err != nil {
		return nil, err
	}
	if len(outs) != len(in) {
		return nil, fmt.Errorf("skgo: batch query getBatch was given %d arguments and answered %d results", len(in), len(outs))
	}
	res := make([]any, len(outs))
	for i, out := range outs {
		tree, err := EncodeRoot0(out)
		if err != nil {
			return nil, err
		}
		res[i] = tree
	}
	return res, nil
}

// requestedArg_getBatch decodes one instance's argument for skgo.Requested, with the same
// decoder remote_getBatch uses.
func requestedArg_getBatch(arg any) (any, error) {
	in, err := DecodeRoot5(arg)
	if err != nil {
		return nil, skgo.BadRequest(err)
	}
	return in, nil
}

// remote_getDependent answers src/routes/async-ssr/[mode]/[group]/probe.remote.ts#getDependent, a query.
//
// The argument is decoded by DecodeRoot0, generated by polytype for getDependent's
// own parameter type: a shape it does not admit is a 400 naming the path,
// never a zero value.
// The result is encoded by EncodeRoot0, generated for its result type.
func remote_getDependent(ctx context.Context, call skgo.Call) (any, error) {
	if err := skgo.RequireArgument(call); err != nil {
		return nil, err
	}
	in, err := DecodeRoot0(call.Arg)
	if err != nil {
		return nil, skgo.BadRequest(err)
	}
	out, err := skgo25.Skgo_getDependent(ctx, in)
	if err != nil {
		return nil, err
	}
	return EncodeRoot0(out)
}

// requestedArg_getDependent decodes one instance's argument for skgo.Requested, with the same
// decoder remote_getDependent uses.
func requestedArg_getDependent(arg any) (any, error) {
	in, err := DecodeRoot0(arg)
	if err != nil {
		return nil, skgo.BadRequest(err)
	}
	return in, nil
}

// remote_getHeld answers src/routes/async-ssr/[mode]/[group]/probe.remote.ts#getHeld, a query.
//
// The argument is decoded by DecodeRoot5, generated by polytype for getHeld's
// own parameter type: a shape it does not admit is a 400 naming the path,
// never a zero value.
// The result is encoded by EncodeRoot0, generated for its result type.
func remote_getHeld(ctx context.Context, call skgo.Call) (any, error) {
	if err := skgo.RequireArgument(call); err != nil {
		return nil, err
	}
	in, err := DecodeRoot5(call.Arg)
	if err != nil {
		return nil, skgo.BadRequest(err)
	}
	out, err := skgo25.Skgo_getHeld(ctx, in)
	if err != nil {
		return nil, err
	}
	return EncodeRoot0(out)
}

// requestedArg_getHeld decodes one instance's argument for skgo.Requested, with the same
// decoder remote_getHeld uses.
func requestedArg_getHeld(arg any) (any, error) {
	in, err := DecodeRoot5(arg)
	if err != nil {
		return nil, skgo.BadRequest(err)
	}
	return in, nil
}

// remote_getSeed answers src/routes/async-ssr/[mode]/[group]/probe.remote.ts#getSeed, a query.
//
// The argument is decoded by DecodeRoot0, generated by polytype for getSeed's
// own parameter type: a shape it does not admit is a 400 naming the path,
// never a zero value.
// The result is encoded by EncodeRoot0, generated for its result type.
func remote_getSeed(ctx context.Context, call skgo.Call) (any, error) {
	if err := skgo.RequireArgument(call); err != nil {
		return nil, err
	}
	in, err := DecodeRoot0(call.Arg)
	if err != nil {
		return nil, skgo.BadRequest(err)
	}
	out, err := skgo25.Skgo_getSeed(ctx, in)
	if err != nil {
		return nil, err
	}
	return EncodeRoot0(out)
}

// requestedArg_getSeed decodes one instance's argument for skgo.Requested, with the same
// decoder remote_getSeed uses.
func requestedArg_getSeed(arg any) (any, error) {
	in, err := DecodeRoot0(arg)
	if err != nil {
		return nil, skgo.BadRequest(err)
	}
	return in, nil
}

// remote_getValue answers src/routes/async-ssr/[mode]/[group]/probe.remote.ts#getValue, a query.
//
// The argument is decoded by DecodeRoot5, generated by polytype for getValue's
// own parameter type: a shape it does not admit is a 400 naming the path,
// never a zero value.
// The result is encoded by EncodeRoot0, generated for its result type.
func remote_getValue(ctx context.Context, call skgo.Call) (any, error) {
	if err := skgo.RequireArgument(call); err != nil {
		return nil, err
	}
	in, err := DecodeRoot5(call.Arg)
	if err != nil {
		return nil, skgo.BadRequest(err)
	}
	out, err := skgo25.Skgo_getValue(ctx, in)
	if err != nil {
		return nil, err
	}
	return EncodeRoot0(out)
}

// requestedArg_getValue decodes one instance's argument for skgo.Requested, with the same
// decoder remote_getValue uses.
func requestedArg_getValue(arg any) (any, error) {
	in, err := DecodeRoot5(arg)
	if err != nil {
		return nil, skgo.BadRequest(err)
	}
	return in, nil
}

// remote_watchValue answers src/routes/async-ssr/[mode]/[group]/probe.remote.ts#watchValue, a query.live.
//
// The argument is decoded by DecodeRoot5, generated by polytype for watchValue's
// own parameter type: a shape it does not admit is a 400 naming the path,
// never a zero value.
// The result is encoded by EncodeRoot0, generated for its result type.
func remote_watchValue(ctx context.Context, call skgo.Call, yield func(any) error) error {
	if err := skgo.RequireArgument(call); err != nil {
		return err
	}
	in, err := DecodeRoot5(call.Arg)
	if err != nil {
		return skgo.BadRequest(err)
	}
	return skgo25.Skgo_watchValue(ctx, in, func(out skgo25.SkgoOut_watchValue) error {
		tree, err := EncodeRoot0(out)
		if err != nil {
			return err
		}
		return yield(tree)
	})
}

// requestedArg_watchValue decodes one instance's argument for skgo.Requested, with the same
// decoder remote_watchValue uses.
func requestedArg_watchValue(arg any) (any, error) {
	in, err := DecodeRoot5(arg)
	if err != nil {
		return nil, skgo.BadRequest(err)
	}
	return in, nil
}

// remote_getQuotes answers src/routes/batch/quotes.remote.ts#getQuotes, a query.batch.
//
// The argument is decoded by DecodeRoot0, generated by polytype for getQuotes's
// own parameter type: a shape it does not admit is a 400 naming the path,
// never a zero value.
// The result is encoded by EncodeRoot6, generated for its result type.
func remote_getQuotes(ctx context.Context, calls []skgo.Call) ([]any, error) {
	in := make([]skgo27.SkgoArg_getQuotes, len(calls))
	for i, call := range calls {
		if err := skgo.RequireArgument(call); err != nil {
			return nil, err
		}
		decoded, err := DecodeRoot0(call.Arg)
		if err != nil {
			return nil, skgo.BadRequest(err)
		}
		in[i] = decoded
	}
	outs, err := skgo27.Skgo_getQuotes(ctx, in)
	if err != nil {
		return nil, err
	}
	if len(outs) != len(in) {
		return nil, fmt.Errorf("skgo: batch query getQuotes was given %d arguments and answered %d results", len(in), len(outs))
	}
	res := make([]any, len(outs))
	for i, out := range outs {
		tree, err := EncodeRoot6(out)
		if err != nil {
			return nil, err
		}
		res[i] = tree
	}
	return res, nil
}

// requestedArg_getQuotes decodes one instance's argument for skgo.Requested, with the same
// decoder remote_getQuotes uses.
func requestedArg_getQuotes(arg any) (any, error) {
	in, err := DecodeRoot0(arg)
	if err != nil {
		return nil, skgo.BadRequest(err)
	}
	return in, nil
}

// remote_getMessages answers src/routes/contact/contact.remote.ts#getMessages, a query.
//
// It takes no argument, so any argument at all is refused — kit's own
// validator for a function declared without one answers 400 too.
// The result is encoded by EncodeRoot7, generated for its result type.
func remote_getMessages(ctx context.Context, call skgo.Call) (any, error) {
	if err := skgo.RefuseArgument(call); err != nil {
		return nil, err
	}
	out, err := skgo28.Skgo_getMessages(ctx)
	if err != nil {
		return nil, err
	}
	return EncodeRoot7(out)
}

// remote_sendMessage answers src/routes/contact/contact.remote.ts#sendMessage, a form.
//
// A form's submission is assigned onto the handler's own argument type:
// kit posts a form as binary form data, which can carry an uploaded File,
// and a File is not a value polytype describes.
// The result is encoded by EncodeRoot8, generated for its result type.
func remote_sendMessage(ctx context.Context, call skgo.Call) (any, error) {
	var in skgo28.SkgoArg_sendMessage
	if err := skgo.DecodeForm(call.Arg, &in); err != nil {
		return nil, err
	}
	out, err := skgo28.Skgo_sendMessage(ctx, in)
	if err != nil {
		return nil, err
	}
	return EncodeRoot8(out)
}

// remote_getPage answers src/routes/docs/[...rest]/docs.remote.ts#getPage, a query.
//
// The argument is decoded by DecodeRoot0, generated by polytype for getPage's
// own parameter type: a shape it does not admit is a 400 naming the path,
// never a zero value.
// The result is encoded by EncodeRoot9, generated for its result type.
func remote_getPage(ctx context.Context, call skgo.Call) (any, error) {
	if err := skgo.RequireArgument(call); err != nil {
		return nil, err
	}
	in, err := DecodeRoot0(call.Arg)
	if err != nil {
		return nil, skgo.BadRequest(err)
	}
	out, err := skgo29.Skgo_getPage(ctx, in)
	if err != nil {
		return nil, err
	}
	return EncodeRoot9(out)
}

// requestedArg_getPage decodes one instance's argument for skgo.Requested, with the same
// decoder remote_getPage uses.
func requestedArg_getPage(arg any) (any, error) {
	in, err := DecodeRoot0(arg)
	if err != nil {
		return nil, skgo.BadRequest(err)
	}
	return in, nil
}

// remote_getKnownReport answers src/routes/empty/empty.remote.ts#getKnownReport, a query.
//
// It takes no argument, so any argument at all is refused — kit's own
// validator for a function declared without one answers 400 too.
// The result is encoded by EncodeRoot10, generated for its result type.
func remote_getKnownReport(ctx context.Context, call skgo.Call) (any, error) {
	if err := skgo.RefuseArgument(call); err != nil {
		return nil, err
	}
	out, err := skgo31.Skgo_getKnownReport(ctx)
	if err != nil {
		return nil, err
	}
	return EncodeRoot10(out)
}

// remote_getModels answers src/routes/empty/empty.remote.ts#getModels, a query.
//
// It takes no argument, so any argument at all is refused — kit's own
// validator for a function declared without one answers 400 too.
// The result is encoded by EncodeRoot11, generated for its result type.
func remote_getModels(ctx context.Context, call skgo.Call) (any, error) {
	if err := skgo.RefuseArgument(call); err != nil {
		return nil, err
	}
	out, err := skgo31.Skgo_getModels(ctx)
	if err != nil {
		return nil, err
	}
	return EncodeRoot11(out)
}

// remote_getReport answers src/routes/empty/empty.remote.ts#getReport, a query.
//
// It takes no argument, so any argument at all is refused — kit's own
// validator for a function declared without one answers 400 too.
// The result is encoded by EncodeRoot10, generated for its result type.
func remote_getReport(ctx context.Context, call skgo.Call) (any, error) {
	if err := skgo.RefuseArgument(call); err != nil {
		return nil, err
	}
	out, err := skgo31.Skgo_getReport(ctx)
	if err != nil {
		return nil, err
	}
	return EncodeRoot10(out)
}

// remote_reparse answers src/routes/empty/empty.remote.ts#reparse, a command.
//
// It takes no argument, so any argument at all is refused — kit's own
// validator for a function declared without one answers 400 too.
// The result is encoded by EncodeRoot10, generated for its result type.
func remote_reparse(ctx context.Context, call skgo.Call) (any, error) {
	if err := skgo.RefuseArgument(call); err != nil {
		return nil, err
	}
	out, err := skgo31.Skgo_reparse(ctx)
	if err != nil {
		return nil, err
	}
	return EncodeRoot10(out)
}

// remote_readSensor answers src/routes/error/boundary/boundary.remote.ts#readSensor, a query.
//
// It takes no argument, so any argument at all is refused — kit's own
// validator for a function declared without one answers 400 too.
// The result is encoded by EncodeRoot12, generated for its result type.
func remote_readSensor(ctx context.Context, call skgo.Call) (any, error) {
	if err := skgo.RefuseArgument(call); err != nil {
		return nil, err
	}
	out, err := skgo32.Skgo_readSensor(ctx)
	if err != nil {
		return nil, err
	}
	return EncodeRoot12(out)
}

// remote_bumpTally answers src/routes/error/command/command.remote.ts#bumpTally, a command.
//
// It takes no argument, so any argument at all is refused — kit's own
// validator for a function declared without one answers 400 too.
// The result is encoded by EncodeRoot13, generated for its result type.
func remote_bumpTally(ctx context.Context, call skgo.Call) (any, error) {
	if err := skgo.RefuseArgument(call); err != nil {
		return nil, err
	}
	out, err := skgo33.Skgo_bumpTally(ctx)
	if err != nil {
		return nil, err
	}
	return EncodeRoot13(out)
}

// remote_getTally answers src/routes/error/command/command.remote.ts#getTally, a query.
//
// It takes no argument, so any argument at all is refused — kit's own
// validator for a function declared without one answers 400 too.
// The result is encoded by EncodeRoot13, generated for its result type.
func remote_getTally(ctx context.Context, call skgo.Call) (any, error) {
	if err := skgo.RefuseArgument(call); err != nil {
		return nil, err
	}
	out, err := skgo33.Skgo_getTally(ctx)
	if err != nil {
		return nil, err
	}
	return EncodeRoot13(out)
}

// remote_whereTo answers src/routes/error/redirect/redirect.remote.ts#whereTo, a query.
//
// It takes no argument, so any argument at all is refused — kit's own
// validator for a function declared without one answers 400 too.
// The result is encoded by EncodeRoot14, generated for its result type.
func remote_whereTo(ctx context.Context, call skgo.Call) (any, error) {
	if err := skgo.RefuseArgument(call); err != nil {
		return nil, err
	}
	out, err := skgo35.Skgo_whereTo(ctx)
	if err != nil {
		return nil, err
	}
	return EncodeRoot14(out)
}

// remote_getRevision answers src/routes/go-dev/go-dev.remote.ts#getRevision, a query.
//
// It takes no argument, so any argument at all is refused — kit's own
// validator for a function declared without one answers 400 too.
// The result is encoded by EncodeRoot0, generated for its result type.
func remote_getRevision(ctx context.Context, call skgo.Call) (any, error) {
	if err := skgo.RefuseArgument(call); err != nil {
		return nil, err
	}
	out, err := skgo37.Skgo_getRevision(ctx)
	if err != nil {
		return nil, err
	}
	return EncodeRoot0(out)
}

// remote_getItem answers src/routes/items/[id]/item.remote.ts#getItem, a query.
//
// The argument is decoded by DecodeRoot0, generated by polytype for getItem's
// own parameter type: a shape it does not admit is a 400 naming the path,
// never a zero value.
// The result is encoded by EncodeRoot15, generated for its result type.
func remote_getItem(ctx context.Context, call skgo.Call) (any, error) {
	if err := skgo.RequireArgument(call); err != nil {
		return nil, err
	}
	in, err := DecodeRoot0(call.Arg)
	if err != nil {
		return nil, skgo.BadRequest(err)
	}
	out, err := skgo40.Skgo_getItem(ctx, in)
	if err != nil {
		return nil, err
	}
	return EncodeRoot15(out)
}

// requestedArg_getItem decodes one instance's argument for skgo.Requested, with the same
// decoder remote_getItem uses.
func requestedArg_getItem(arg any) (any, error) {
	in, err := DecodeRoot0(arg)
	if err != nil {
		return nil, skgo.BadRequest(err)
	}
	return in, nil
}

// remote_watchBoard answers src/routes/live/board.remote.ts#watchBoard, a query.live.
//
// It takes no argument, so any argument at all is refused — kit's own
// validator for a function declared without one answers 400 too.
// The result is encoded by EncodeRoot16, generated for its result type.
func remote_watchBoard(ctx context.Context, call skgo.Call, yield func(any) error) error {
	if err := skgo.RefuseArgument(call); err != nil {
		return err
	}
	return skgo41.Skgo_watchBoard(ctx, func(out skgo41.SkgoOut_watchBoard) error {
		tree, err := EncodeRoot16(out)
		if err != nil {
			return err
		}
		return yield(tree)
	})
}

// remote_submit answers src/routes/optional/optional.remote.ts#submit, a form.
//
// A form's submission is assigned onto the handler's own argument type:
// kit posts a form as binary form data, which can carry an uploaded File,
// and a File is not a value polytype describes.
// The result is encoded by EncodeRoot17, generated for its result type.
func remote_submit(ctx context.Context, call skgo.Call) (any, error) {
	var in skgo44.SkgoArg_submit
	if err := skgo.DecodeForm(call.Arg, &in); err != nil {
		return nil, err
	}
	out, err := skgo44.Skgo_submit(ctx, in)
	if err != nil {
		return nil, err
	}
	return EncodeRoot17(out)
}

// remote_getSite answers src/routes/site.remote.ts#getSite, a query.
//
// It takes no argument, so any argument at all is refused — kit's own
// validator for a function declared without one answers 400 too.
// The result is encoded by EncodeRoot18, generated for its result type.
func remote_getSite(ctx context.Context, call skgo.Call) (any, error) {
	if err := skgo.RefuseArgument(call); err != nil {
		return nil, err
	}
	out, err := skgo1.Skgo_getSite(ctx)
	if err != nil {
		return nil, err
	}
	return EncodeRoot18(out)
}

// remote_getBanner answers src/routes/todos/gate/gate.remote.ts#getBanner, a query.
//
// It takes no argument, so any argument at all is refused — kit's own
// validator for a function declared without one answers 400 too.
// The result is encoded by EncodeRoot19, generated for its result type.
func remote_getBanner(ctx context.Context, call skgo.Call) (any, error) {
	if err := skgo.RefuseArgument(call); err != nil {
		return nil, err
	}
	out, err := skgo4.Skgo_getBanner(ctx)
	if err != nil {
		return nil, err
	}
	return EncodeRoot19(out)
}

// remote_getNote answers src/routes/todos/gate/gate.remote.ts#getNote, a query.
//
// The argument is decoded by DecodeRoot0, generated by polytype for getNote's
// own parameter type: a shape it does not admit is a 400 naming the path,
// never a zero value.
// The result is encoded by EncodeRoot20, generated for its result type.
func remote_getNote(ctx context.Context, call skgo.Call) (any, error) {
	if err := skgo.RequireArgument(call); err != nil {
		return nil, err
	}
	in, err := DecodeRoot0(call.Arg)
	if err != nil {
		return nil, skgo.BadRequest(err)
	}
	out, err := skgo4.Skgo_getNote(ctx, in)
	if err != nil {
		return nil, err
	}
	return EncodeRoot20(out)
}

// requestedArg_getNote decodes one instance's argument for skgo.Requested, with the same
// decoder remote_getNote uses.
func requestedArg_getNote(arg any) (any, error) {
	in, err := DecodeRoot0(arg)
	if err != nil {
		return nil, skgo.BadRequest(err)
	}
	return in, nil
}

// remote_writeNotes answers src/routes/todos/gate/gate.remote.ts#writeNotes, a command.
//
// The argument is decoded by DecodeRoot21, generated by polytype for writeNotes's
// own parameter type: a shape it does not admit is a 400 naming the path,
// never a zero value.
// The result is encoded by EncodeRoot22, generated for its result type.
func remote_writeNotes(ctx context.Context, call skgo.Call) (any, error) {
	if err := skgo.RequireArgument(call); err != nil {
		return nil, err
	}
	in, err := DecodeRoot21(call.Arg)
	if err != nil {
		return nil, skgo.BadRequest(err)
	}
	out, err := skgo4.Skgo_writeNotes(ctx, in)
	if err != nil {
		return nil, err
	}
	return EncodeRoot22(out)
}

// requestedArg_writeNotes decodes one instance's argument for skgo.Requested, with the same
// decoder remote_writeNotes uses.
func requestedArg_writeNotes(arg any) (any, error) {
	in, err := DecodeRoot21(arg)
	if err != nil {
		return nil, skgo.BadRequest(err)
	}
	return in, nil
}

// remote_addTodo answers src/routes/todos/todos.remote.ts#addTodo, a command.
//
// The argument is decoded by DecodeRoot0, generated by polytype for addTodo's
// own parameter type: a shape it does not admit is a 400 naming the path,
// never a zero value.
// The result is encoded by EncodeRoot23, generated for its result type.
func remote_addTodo(ctx context.Context, call skgo.Call) (any, error) {
	if err := skgo.RequireArgument(call); err != nil {
		return nil, err
	}
	in, err := DecodeRoot0(call.Arg)
	if err != nil {
		return nil, skgo.BadRequest(err)
	}
	out, err := skgo3.Skgo_addTodo(ctx, in)
	if err != nil {
		return nil, err
	}
	return EncodeRoot23(out)
}

// requestedArg_addTodo decodes one instance's argument for skgo.Requested, with the same
// decoder remote_addTodo uses.
func requestedArg_addTodo(arg any) (any, error) {
	in, err := DecodeRoot0(arg)
	if err != nil {
		return nil, skgo.BadRequest(err)
	}
	return in, nil
}

// remote_getTodo answers src/routes/todos/todos.remote.ts#getTodo, a query.
//
// The argument is decoded by DecodeRoot0, generated by polytype for getTodo's
// own parameter type: a shape it does not admit is a 400 naming the path,
// never a zero value.
// The result is encoded by EncodeRoot23, generated for its result type.
func remote_getTodo(ctx context.Context, call skgo.Call) (any, error) {
	if err := skgo.RequireArgument(call); err != nil {
		return nil, err
	}
	in, err := DecodeRoot0(call.Arg)
	if err != nil {
		return nil, skgo.BadRequest(err)
	}
	out, err := skgo3.Skgo_getTodo(ctx, in)
	if err != nil {
		return nil, err
	}
	return EncodeRoot23(out)
}

// requestedArg_getTodo decodes one instance's argument for skgo.Requested, with the same
// decoder remote_getTodo uses.
func requestedArg_getTodo(arg any) (any, error) {
	in, err := DecodeRoot0(arg)
	if err != nil {
		return nil, skgo.BadRequest(err)
	}
	return in, nil
}

// remote_getTodos answers src/routes/todos/todos.remote.ts#getTodos, a query.
//
// It takes no argument, so any argument at all is refused — kit's own
// validator for a function declared without one answers 400 too.
// The result is encoded by EncodeRoot24, generated for its result type.
func remote_getTodos(ctx context.Context, call skgo.Call) (any, error) {
	if err := skgo.RefuseArgument(call); err != nil {
		return nil, err
	}
	out, err := skgo3.Skgo_getTodos(ctx)
	if err != nil {
		return nil, err
	}
	return EncodeRoot24(out)
}

// remote_renameTodo answers src/routes/todos/todos.remote.ts#renameTodo, a command.
//
// The argument is decoded by DecodeRoot25, generated by polytype for renameTodo's
// own parameter type: a shape it does not admit is a 400 naming the path,
// never a zero value.
// The result is encoded by EncodeRoot23, generated for its result type.
func remote_renameTodo(ctx context.Context, call skgo.Call) (any, error) {
	if err := skgo.RequireArgument(call); err != nil {
		return nil, err
	}
	in, err := DecodeRoot25(call.Arg)
	if err != nil {
		return nil, skgo.BadRequest(err)
	}
	out, err := skgo3.Skgo_renameTodo(ctx, in)
	if err != nil {
		return nil, err
	}
	return EncodeRoot23(out)
}

// requestedArg_renameTodo decodes one instance's argument for skgo.Requested, with the same
// decoder remote_renameTodo uses.
func requestedArg_renameTodo(arg any) (any, error) {
	in, err := DecodeRoot25(arg)
	if err != nil {
		return nil, skgo.BadRequest(err)
	}
	return in, nil
}

// remote_retitleTodo answers src/routes/todos/todos.remote.ts#retitleTodo, a command.
//
// The argument is decoded by DecodeRoot26, generated by polytype for retitleTodo's
// own parameter type: a shape it does not admit is a 400 naming the path,
// never a zero value.
// The result is encoded by EncodeRoot23, generated for its result type.
func remote_retitleTodo(ctx context.Context, call skgo.Call) (any, error) {
	if err := skgo.RequireArgument(call); err != nil {
		return nil, err
	}
	in, err := DecodeRoot26(call.Arg)
	if err != nil {
		return nil, skgo.BadRequest(err)
	}
	out, err := skgo3.Skgo_retitleTodo(ctx, in)
	if err != nil {
		return nil, err
	}
	return EncodeRoot23(out)
}

// requestedArg_retitleTodo decodes one instance's argument for skgo.Requested, with the same
// decoder remote_retitleTodo uses.
func requestedArg_retitleTodo(arg any) (any, error) {
	in, err := DecodeRoot26(arg)
	if err != nil {
		return nil, skgo.BadRequest(err)
	}
	return in, nil
}

// remote_watchCount answers src/routes/todos/todos.remote.ts#watchCount, a query.live.
//
// It takes no argument, so any argument at all is refused — kit's own
// validator for a function declared without one answers 400 too.
// The result is encoded by EncodeRoot27, generated for its result type.
func remote_watchCount(ctx context.Context, call skgo.Call, yield func(any) error) error {
	if err := skgo.RefuseArgument(call); err != nil {
		return err
	}
	return skgo3.Skgo_watchCount(ctx, func(out skgo3.SkgoOut_watchCount) error {
		tree, err := EncodeRoot27(out)
		if err != nil {
			return err
		}
		return yield(tree)
	})
}

// Remotes returns every remote function declared in the app, ready to hand
// to skgo.NewRemotes.
func Remotes() []*skgo.Remote {
	return []*skgo.Remote{
		skgo.NewRemote(skgo.RemoteSpec{
			Kind:      skgo.KindCommand,
			Module:    "src/lib/auth.remote.ts",
			Name:      "signIn",
			Fn:        skgo49.Skgo_signIn,
			Call:      remote_signIn,
			DecodeArg: requestedArg_signIn,
		}),
		skgo.NewRemote(skgo.RemoteSpec{
			Kind:   skgo.KindCommand,
			Module: "src/lib/auth.remote.ts",
			Name:   "signOut",
			Fn:     skgo49.Skgo_signOut,
			Call:   remote_signOut,
		}),
		skgo.NewRemote(skgo.RemoteSpec{
			Kind:   skgo.KindQuery,
			Module: "src/lib/auth.remote.ts",
			Name:   "whoami",
			Fn:     skgo49.Skgo_whoami,
			Call:   remote_whoami,
		}),
		skgo.NewRemote(skgo.RemoteSpec{
			Kind:   skgo.KindQuery,
			Module: "src/routes/(marketing)/pricing/pricing.remote.ts",
			Name:   "getPlans",
			Fn:     skgo2.Skgo_getPlans,
			Call:   remote_getPlans,
		}),
		skgo.NewRemote(skgo.RemoteSpec{
			Kind:   skgo.KindQuery,
			Module: "src/routes/(marketing)/pricing/pricing.remote.ts",
			Name:   "getSpotlight",
			Fn:     skgo2.Skgo_getSpotlight,
			Call:   remote_getSpotlight,
		}),
		skgo.NewRemote(skgo.RemoteSpec{
			Kind:      skgo.KindCommand,
			Module:    "src/routes/(marketing)/pricing/pricing.remote.ts",
			Name:      "quoteFor",
			Fn:        skgo2.Skgo_quoteFor,
			Call:      remote_quoteFor,
			DecodeArg: requestedArg_quoteFor,
		}),
		skgo.NewRemote(skgo.RemoteSpec{
			Kind:      skgo.KindPrerender,
			Module:    "src/routes/about/about.remote.ts",
			Name:      "buildReceipt",
			Fn:        skgo7.Skgo_buildReceipt,
			Call:      remote_buildReceipt,
			DecodeArg: requestedArg_buildReceipt,
		}),
		skgo.NewRemote(skgo.RemoteSpec{
			Kind:   skgo.KindForm,
			Module: "src/routes/actions/coexist.remote.ts",
			Name:   "sendRemoteNote",
			Fn:     skgo8.Skgo_sendRemoteNote,
			Call:   remote_sendRemoteNote,
		}),
		skgo.NewRemote(skgo.RemoteSpec{
			Kind:      skgo.KindBatch,
			Module:    "src/routes/async-ssr/[mode]/[group]/probe.remote.ts",
			Name:      "getBatch",
			Fn:        skgo25.Skgo_getBatch,
			Batch:     remote_getBatch,
			DecodeArg: requestedArg_getBatch,
		}),
		skgo.NewRemote(skgo.RemoteSpec{
			Kind:      skgo.KindQuery,
			Module:    "src/routes/async-ssr/[mode]/[group]/probe.remote.ts",
			Name:      "getDependent",
			Fn:        skgo25.Skgo_getDependent,
			Call:      remote_getDependent,
			DecodeArg: requestedArg_getDependent,
		}),
		skgo.NewRemote(skgo.RemoteSpec{
			Kind:      skgo.KindQuery,
			Module:    "src/routes/async-ssr/[mode]/[group]/probe.remote.ts",
			Name:      "getHeld",
			Fn:        skgo25.Skgo_getHeld,
			Call:      remote_getHeld,
			DecodeArg: requestedArg_getHeld,
		}),
		skgo.NewRemote(skgo.RemoteSpec{
			Kind:      skgo.KindQuery,
			Module:    "src/routes/async-ssr/[mode]/[group]/probe.remote.ts",
			Name:      "getSeed",
			Fn:        skgo25.Skgo_getSeed,
			Call:      remote_getSeed,
			DecodeArg: requestedArg_getSeed,
		}),
		skgo.NewRemote(skgo.RemoteSpec{
			Kind:      skgo.KindQuery,
			Module:    "src/routes/async-ssr/[mode]/[group]/probe.remote.ts",
			Name:      "getValue",
			Fn:        skgo25.Skgo_getValue,
			Call:      remote_getValue,
			DecodeArg: requestedArg_getValue,
		}),
		skgo.NewRemote(skgo.RemoteSpec{
			Kind:      skgo.KindLive,
			Module:    "src/routes/async-ssr/[mode]/[group]/probe.remote.ts",
			Name:      "watchValue",
			Fn:        skgo25.Skgo_watchValue,
			Live:      remote_watchValue,
			DecodeArg: requestedArg_watchValue,
		}),
		skgo.NewRemote(skgo.RemoteSpec{
			Kind:      skgo.KindBatch,
			Module:    "src/routes/batch/quotes.remote.ts",
			Name:      "getQuotes",
			Fn:        skgo27.Skgo_getQuotes,
			Batch:     remote_getQuotes,
			DecodeArg: requestedArg_getQuotes,
		}),
		skgo.NewRemote(skgo.RemoteSpec{
			Kind:   skgo.KindQuery,
			Module: "src/routes/contact/contact.remote.ts",
			Name:   "getMessages",
			Fn:     skgo28.Skgo_getMessages,
			Call:   remote_getMessages,
		}),
		skgo.NewRemote(skgo.RemoteSpec{
			Kind:   skgo.KindForm,
			Module: "src/routes/contact/contact.remote.ts",
			Name:   "sendMessage",
			Fn:     skgo28.Skgo_sendMessage,
			Call:   remote_sendMessage,
		}),
		skgo.NewRemote(skgo.RemoteSpec{
			Kind:      skgo.KindQuery,
			Module:    "src/routes/docs/[...rest]/docs.remote.ts",
			Name:      "getPage",
			Fn:        skgo29.Skgo_getPage,
			Call:      remote_getPage,
			DecodeArg: requestedArg_getPage,
		}),
		skgo.NewRemote(skgo.RemoteSpec{
			Kind:   skgo.KindQuery,
			Module: "src/routes/empty/empty.remote.ts",
			Name:   "getKnownReport",
			Fn:     skgo31.Skgo_getKnownReport,
			Call:   remote_getKnownReport,
		}),
		skgo.NewRemote(skgo.RemoteSpec{
			Kind:   skgo.KindQuery,
			Module: "src/routes/empty/empty.remote.ts",
			Name:   "getModels",
			Fn:     skgo31.Skgo_getModels,
			Call:   remote_getModels,
		}),
		skgo.NewRemote(skgo.RemoteSpec{
			Kind:   skgo.KindQuery,
			Module: "src/routes/empty/empty.remote.ts",
			Name:   "getReport",
			Fn:     skgo31.Skgo_getReport,
			Call:   remote_getReport,
		}),
		skgo.NewRemote(skgo.RemoteSpec{
			Kind:   skgo.KindCommand,
			Module: "src/routes/empty/empty.remote.ts",
			Name:   "reparse",
			Fn:     skgo31.Skgo_reparse,
			Call:   remote_reparse,
		}),
		skgo.NewRemote(skgo.RemoteSpec{
			Kind:   skgo.KindQuery,
			Module: "src/routes/error/boundary/boundary.remote.ts",
			Name:   "readSensor",
			Fn:     skgo32.Skgo_readSensor,
			Call:   remote_readSensor,
		}),
		skgo.NewRemote(skgo.RemoteSpec{
			Kind:   skgo.KindCommand,
			Module: "src/routes/error/command/command.remote.ts",
			Name:   "bumpTally",
			Fn:     skgo33.Skgo_bumpTally,
			Call:   remote_bumpTally,
		}),
		skgo.NewRemote(skgo.RemoteSpec{
			Kind:   skgo.KindQuery,
			Module: "src/routes/error/command/command.remote.ts",
			Name:   "getTally",
			Fn:     skgo33.Skgo_getTally,
			Call:   remote_getTally,
		}),
		skgo.NewRemote(skgo.RemoteSpec{
			Kind:   skgo.KindQuery,
			Module: "src/routes/error/redirect/redirect.remote.ts",
			Name:   "whereTo",
			Fn:     skgo35.Skgo_whereTo,
			Call:   remote_whereTo,
		}),
		skgo.NewRemote(skgo.RemoteSpec{
			Kind:   skgo.KindQuery,
			Module: "src/routes/go-dev/go-dev.remote.ts",
			Name:   "getRevision",
			Fn:     skgo37.Skgo_getRevision,
			Call:   remote_getRevision,
		}),
		skgo.NewRemote(skgo.RemoteSpec{
			Kind:      skgo.KindQuery,
			Module:    "src/routes/items/[id]/item.remote.ts",
			Name:      "getItem",
			Fn:        skgo40.Skgo_getItem,
			Call:      remote_getItem,
			DecodeArg: requestedArg_getItem,
		}),
		skgo.NewRemote(skgo.RemoteSpec{
			Kind:   skgo.KindLive,
			Module: "src/routes/live/board.remote.ts",
			Name:   "watchBoard",
			Fn:     skgo41.Skgo_watchBoard,
			Live:   remote_watchBoard,
		}),
		skgo.NewRemote(skgo.RemoteSpec{
			Kind:   skgo.KindForm,
			Module: "src/routes/optional/optional.remote.ts",
			Name:   "submit",
			Fn:     skgo44.Skgo_submit,
			Call:   remote_submit,
		}),
		skgo.NewRemote(skgo.RemoteSpec{
			Kind:   skgo.KindQuery,
			Module: "src/routes/site.remote.ts",
			Name:   "getSite",
			Fn:     skgo1.Skgo_getSite,
			Call:   remote_getSite,
		}),
		skgo.NewRemote(skgo.RemoteSpec{
			Kind:   skgo.KindQuery,
			Module: "src/routes/todos/gate/gate.remote.ts",
			Name:   "getBanner",
			Fn:     skgo4.Skgo_getBanner,
			Call:   remote_getBanner,
		}),
		skgo.NewRemote(skgo.RemoteSpec{
			Kind:      skgo.KindQuery,
			Module:    "src/routes/todos/gate/gate.remote.ts",
			Name:      "getNote",
			Fn:        skgo4.Skgo_getNote,
			Call:      remote_getNote,
			DecodeArg: requestedArg_getNote,
		}),
		skgo.NewRemote(skgo.RemoteSpec{
			Kind:      skgo.KindCommand,
			Module:    "src/routes/todos/gate/gate.remote.ts",
			Name:      "writeNotes",
			Fn:        skgo4.Skgo_writeNotes,
			Call:      remote_writeNotes,
			DecodeArg: requestedArg_writeNotes,
		}),
		skgo.NewRemote(skgo.RemoteSpec{
			Kind:      skgo.KindCommand,
			Module:    "src/routes/todos/todos.remote.ts",
			Name:      "addTodo",
			Fn:        skgo3.Skgo_addTodo,
			Call:      remote_addTodo,
			DecodeArg: requestedArg_addTodo,
		}),
		skgo.NewRemote(skgo.RemoteSpec{
			Kind:      skgo.KindQuery,
			Module:    "src/routes/todos/todos.remote.ts",
			Name:      "getTodo",
			Fn:        skgo3.Skgo_getTodo,
			Call:      remote_getTodo,
			DecodeArg: requestedArg_getTodo,
		}),
		skgo.NewRemote(skgo.RemoteSpec{
			Kind:   skgo.KindQuery,
			Module: "src/routes/todos/todos.remote.ts",
			Name:   "getTodos",
			Fn:     skgo3.Skgo_getTodos,
			Call:   remote_getTodos,
		}),
		skgo.NewRemote(skgo.RemoteSpec{
			Kind:      skgo.KindCommand,
			Module:    "src/routes/todos/todos.remote.ts",
			Name:      "renameTodo",
			Fn:        skgo3.Skgo_renameTodo,
			Call:      remote_renameTodo,
			DecodeArg: requestedArg_renameTodo,
		}),
		skgo.NewRemote(skgo.RemoteSpec{
			Kind:      skgo.KindCommand,
			Module:    "src/routes/todos/todos.remote.ts",
			Name:      "retitleTodo",
			Fn:        skgo3.Skgo_retitleTodo,
			Call:      remote_retitleTodo,
			DecodeArg: requestedArg_retitleTodo,
		}),
		skgo.NewRemote(skgo.RemoteSpec{
			Kind:   skgo.KindLive,
			Module: "src/routes/todos/todos.remote.ts",
			Name:   "watchCount",
			Fn:     skgo3.Skgo_watchCount,
			Live:   remote_watchCount,
		}),
	}
}

// load_marketing_pricing_page answers src/routes/(marketing)/pricing/+page.server.ts.
//
// A load's result is the one value no generated encoder produces: it may
// hold a skgo.Deferred, and `Promise<T>` is not a projection of any Go
// type, so the value is encoded where a promise can still be recognised.
func load_marketing_pricing_page(ctx context.Context) (any, error) {
	return skgo2.Skgo_pageLoad(skgo2.SkgoRequestEvent(skgo.EventFrom(ctx)))
}

// load_layout answers src/routes/+layout.server.ts.
//
// A load's result is the one value no generated encoder produces: it may
// hold a skgo.Deferred, and `Promise<T>` is not a projection of any Go
// type, so the value is encoded where a promise can still be recognised.
func load_layout(ctx context.Context) (any, error) {
	return skgo1.Skgo_layoutLoad(skgo1.SkgoRequestEvent(skgo.EventFrom(ctx)))
}

// load_about_page answers src/routes/about/+page.server.ts.
//
// A load's result is the one value no generated encoder produces: it may
// hold a skgo.Deferred, and `Promise<T>` is not a projection of any Go
// type, so the value is encoded where a promise can still be recognised.
func load_about_page(ctx context.Context) (any, error) {
	return skgo7.Skgo_pageLoad(skgo7.SkgoRequestEvent(skgo.EventFrom(ctx)))
}

// load_account_layout answers src/routes/account/+layout.server.ts.
//
// A load's result is the one value no generated encoder produces: it may
// hold a skgo.Deferred, and `Promise<T>` is not a projection of any Go
// type, so the value is encoded where a promise can still be recognised.
func load_account_layout(ctx context.Context) (any, error) {
	return skgo16.Skgo_layoutLoad(skgo16.SkgoRequestEvent(skgo.EventFrom(ctx)))
}

// load_account_page answers src/routes/account/+page.server.ts.
//
// A load's result is the one value no generated encoder produces: it may
// hold a skgo.Deferred, and `Promise<T>` is not a projection of any Go
// type, so the value is encoded where a promise can still be recognised.
func load_account_page(ctx context.Context) (any, error) {
	return skgo16.Skgo_pageLoad(skgo16.SkgoRequestEvent(skgo.EventFrom(ctx)))
}

// load_account_orders_page answers src/routes/account/orders/+page.server.ts.
//
// A load's result is the one value no generated encoder produces: it may
// hold a skgo.Deferred, and `Promise<T>` is not a projection of any Go
// type, so the value is encoded where a promise can still be recognised.
func load_account_orders_page(ctx context.Context) (any, error) {
	return skgo17.Skgo_pageLoad(skgo17.SkgoRequestEvent(skgo.EventFrom(ctx)))
}

// load_account_reruns_slug_page answers src/routes/account/reruns/[slug]/+page.server.ts.
//
// A load's result is the one value no generated encoder produces: it may
// hold a skgo.Deferred, and `Promise<T>` is not a projection of any Go
// type, so the value is encoded where a promise can still be recognised.
func load_account_reruns_slug_page(ctx context.Context) (any, error) {
	return skgo18.Skgo_pageLoad(skgo18.SkgoRequestEvent(skgo.EventFrom(ctx)))
}

// load_account_statement_page answers src/routes/account/statement/+page.server.ts.
//
// A load's result is the one value no generated encoder produces: it may
// hold a skgo.Deferred, and `Promise<T>` is not a projection of any Go
// type, so the value is encoded where a promise can still be recognised.
func load_account_statement_page(ctx context.Context) (any, error) {
	return skgo19.Skgo_pageLoad(skgo19.SkgoRequestEvent(skgo.EventFrom(ctx)))
}

// load_actions_page answers src/routes/actions/+page.server.ts.
//
// A load's result is the one value no generated encoder produces: it may
// hold a skgo.Deferred, and `Promise<T>` is not a projection of any Go
// type, so the value is encoded where a promise can still be recognised.
func load_actions_page(ctx context.Context) (any, error) {
	return skgo8.Skgo_pageLoad(skgo8.SkgoRequestEvent(skgo.EventFrom(ctx)))
}

// load_actions_cross_receive_page answers src/routes/actions/cross/receive/+page.server.ts.
//
// A load's result is the one value no generated encoder produces: it may
// hold a skgo.Deferred, and `Promise<T>` is not a projection of any Go
// type, so the value is encoded where a promise can still be recognised.
func load_actions_cross_receive_page(ctx context.Context) (any, error) {
	return skgo9.Skgo_pageLoad(skgo9.SkgoRequestEvent(skgo.EventFrom(ctx)))
}

// load_actions_default_saved_page answers src/routes/actions/default/saved/+page.server.ts.
//
// A load's result is the one value no generated encoder produces: it may
// hold a skgo.Deferred, and `Promise<T>` is not a projection of any Go
// type, so the value is encoded where a promise can still be recognised.
func load_actions_default_saved_page(ctx context.Context) (any, error) {
	return skgo11.Skgo_pageLoad(skgo11.SkgoRequestEvent(skgo.EventFrom(ctx)))
}

// load_actions_options_noclient_page answers src/routes/actions/options/no-client/+page.server.ts.
//
// A load's result is the one value no generated encoder produces: it may
// hold a skgo.Deferred, and `Promise<T>` is not a projection of any Go
// type, so the value is encoded where a promise can still be recognised.
func load_actions_options_noclient_page(ctx context.Context) (any, error) {
	return skgo12.Skgo_pageLoad(skgo12.SkgoRequestEvent(skgo.EventFrom(ctx)))
}

// load_actions_options_nossr_page answers src/routes/actions/options/no-ssr/+page.server.ts.
//
// A load's result is the one value no generated encoder produces: it may
// hold a skgo.Deferred, and `Promise<T>` is not a projection of any Go
// type, so the value is encoded where a promise can still be recognised.
func load_actions_options_nossr_page(ctx context.Context) (any, error) {
	return skgo13.Skgo_pageLoad(skgo13.SkgoRequestEvent(skgo.EventFrom(ctx)))
}

// load_actions_profiles_profile_page answers src/routes/actions/profiles/[profile]/+page.server.ts.
//
// A load's result is the one value no generated encoder produces: it may
// hold a skgo.Deferred, and `Promise<T>` is not a projection of any Go
// type, so the value is encoded where a promise can still be recognised.
func load_actions_profiles_profile_page(ctx context.Context) (any, error) {
	return skgo14.Skgo_pageLoad(skgo14.SkgoRequestEvent(skgo.EventFrom(ctx)))
}

// load_actions_signedin_page answers src/routes/actions/signed-in/+page.server.ts.
//
// A load's result is the one value no generated encoder produces: it may
// hold a skgo.Deferred, and `Promise<T>` is not a projection of any Go
// type, so the value is encoded where a promise can still be recognised.
func load_actions_signedin_page(ctx context.Context) (any, error) {
	return skgo15.Skgo_pageLoad(skgo15.SkgoRequestEvent(skgo.EventFrom(ctx)))
}

// load_destinations_page answers src/routes/destinations/+page.server.ts.
//
// A load's result is the one value no generated encoder produces: it may
// hold a skgo.Deferred, and `Promise<T>` is not a projection of any Go
// type, so the value is encoded where a promise can still be recognised.
func load_destinations_page(ctx context.Context) (any, error) {
	return skgo30.Skgo_pageLoad(skgo30.SkgoRequestEvent(skgo.EventFrom(ctx)))
}

// load_empty_page answers src/routes/empty/+page.server.ts.
//
// A load's result is the one value no generated encoder produces: it may
// hold a skgo.Deferred, and `Promise<T>` is not a projection of any Go
// type, so the value is encoded where a promise can still be recognised.
func load_empty_page(ctx context.Context) (any, error) {
	return skgo31.Skgo_pageLoad(skgo31.SkgoRequestEvent(skgo.EventFrom(ctx)))
}

// load_error_expected_page answers src/routes/error/expected/+page.server.ts.
//
// A load's result is the one value no generated encoder produces: it may
// hold a skgo.Deferred, and `Promise<T>` is not a projection of any Go
// type, so the value is encoded where a promise can still be recognised.
func load_error_expected_page(ctx context.Context) (any, error) {
	return skgo34.Skgo_pageLoad(skgo34.SkgoRequestEvent(skgo.EventFrom(ctx)))
}

// load_error_unexpected_page answers src/routes/error/unexpected/+page.server.ts.
//
// A load's result is the one value no generated encoder produces: it may
// hold a skgo.Deferred, and `Promise<T>` is not a projection of any Go
// type, so the value is encoded where a promise can still be recognised.
func load_error_unexpected_page(ctx context.Context) (any, error) {
	return skgo36.Skgo_pageLoad(skgo36.SkgoRequestEvent(skgo.EventFrom(ctx)))
}

// load_godev_page answers src/routes/go-dev/+page.server.ts.
//
// A load's result is the one value no generated encoder produces: it may
// hold a skgo.Deferred, and `Promise<T>` is not a projection of any Go
// type, so the value is encoded where a promise can still be recognised.
func load_godev_page(ctx context.Context) (any, error) {
	return skgo37.Skgo_pageLoad(skgo37.SkgoRequestEvent(skgo.EventFrom(ctx)))
}

// load_invoices_page answers src/routes/invoices/+page.server.ts.
//
// A load's result is the one value no generated encoder produces: it may
// hold a skgo.Deferred, and `Promise<T>` is not a projection of any Go
// type, so the value is encoded where a promise can still be recognised.
func load_invoices_page(ctx context.Context) (any, error) {
	return skgo39.Skgo_pageLoad(skgo39.SkgoRequestEvent(skgo.EventFrom(ctx)))
}

// load_middleware_page answers src/routes/middleware/+page.server.ts.
//
// A load's result is the one value no generated encoder produces: it may
// hold a skgo.Deferred, and `Promise<T>` is not a projection of any Go
// type, so the value is encoded where a promise can still be recognised.
func load_middleware_page(ctx context.Context) (any, error) {
	return skgo42.Skgo_pageLoad(skgo42.SkgoRequestEvent(skgo.EventFrom(ctx)))
}

// load_middleware_slug_page answers src/routes/middleware/[slug]/+page.server.ts.
//
// A load's result is the one value no generated encoder produces: it may
// hold a skgo.Deferred, and `Promise<T>` is not a projection of any Go
// type, so the value is encoded where a promise can still be recognised.
func load_middleware_slug_page(ctx context.Context) (any, error) {
	return skgo43.Skgo_pageLoad(skgo43.SkgoRequestEvent(skgo.EventFrom(ctx)))
}

// load_prerender_slug_page answers src/routes/prerender/[slug]/+page.server.ts.
//
// A load's result is the one value no generated encoder produces: it may
// hold a skgo.Deferred, and `Promise<T>` is not a projection of any Go
// type, so the value is encoded where a promise can still be recognised.
func load_prerender_slug_page(ctx context.Context) (any, error) {
	return skgo45.Skgo_load(skgo45.SkgoRequestEvent(skgo.EventFrom(ctx)))
}

// load_requestfetch_page answers src/routes/request-fetch/+page.server.ts.
//
// A load's result is the one value no generated encoder produces: it may
// hold a skgo.Deferred, and `Promise<T>` is not a projection of any Go
// type, so the value is encoded where a promise can still be recognised.
func load_requestfetch_page(ctx context.Context) (any, error) {
	return skgo46.Skgo_pageLoad(skgo46.SkgoRequestEvent(skgo.EventFrom(ctx)))
}

// load_stream_page answers src/routes/stream/+page.server.ts.
//
// A load's result is the one value no generated encoder produces: it may
// hold a skgo.Deferred, and `Promise<T>` is not a projection of any Go
// type, so the value is encoded where a promise can still be recognised.
func load_stream_page(ctx context.Context) (any, error) {
	return skgo48.Skgo_pageLoad(skgo48.SkgoRequestEvent(skgo.EventFrom(ctx)))
}

// load_typeddependencies_aOrder_bOrder_ignored_page answers src/routes/typed-dependencies/[a=Order]/[b=Order]/[ignored]/+page.server.ts.
//
// A load's result is the one value no generated encoder produces: it may
// hold a skgo.Deferred, and `Promise<T>` is not a projection of any Go
// type, so the value is encoded where a promise can still be recognised.
func load_typeddependencies_aOrder_bOrder_ignored_page(ctx context.Context) (any, error) {
	return skgo5.Skgo_load(skgo5.SkgoRequestEvent(skgo.EventFrom(ctx)))
}

// load_typedload_numberOrder_page answers src/routes/typed-load/[number=Order]/+page.server.ts.
//
// A load's result is the one value no generated encoder produces: it may
// hold a skgo.Deferred, and `Promise<T>` is not a projection of any Go
// type, so the value is encoded where a promise can still be recognised.
func load_typedload_numberOrder_page(ctx context.Context) (any, error) {
	return skgo6.Skgo_load(skgo6.SkgoRequestEvent(skgo.EventFrom(ctx)))
}

// Loads returns every server load declared in the app, ready to hand to
// skgo.NewLoads.
func Loads() []*skgo.ServerLoad {
	return []*skgo.ServerLoad{
		skgo.NewServerLoad(skgo.LoadSpec{Module: "src/routes/(marketing)/pricing/+page.server.ts", Run: load_marketing_pricing_page, Matchers: skgo2.SkgoParamMatchers()}),
		skgo.NewServerLoad(skgo.LoadSpec{Module: "src/routes/+layout.server.ts", Run: load_layout, Matchers: skgo1.SkgoParamMatchers()}),
		skgo.NewServerLoad(skgo.LoadSpec{Module: "src/routes/about/+page.server.ts", Run: load_about_page, Matchers: skgo7.SkgoParamMatchers()}),
		skgo.NewServerLoad(skgo.LoadSpec{Module: "src/routes/account/+layout.server.ts", Run: load_account_layout, Matchers: skgo16.SkgoParamMatchers()}),
		skgo.NewServerLoad(skgo.LoadSpec{Module: "src/routes/account/+page.server.ts", Run: load_account_page, Matchers: skgo16.SkgoParamMatchers()}),
		skgo.NewServerLoad(skgo.LoadSpec{Module: "src/routes/account/orders/+page.server.ts", Run: load_account_orders_page, Matchers: skgo17.SkgoParamMatchers()}),
		skgo.NewServerLoad(skgo.LoadSpec{Module: "src/routes/account/reruns/[slug]/+page.server.ts", Run: load_account_reruns_slug_page, Matchers: skgo18.SkgoParamMatchers()}),
		skgo.NewServerLoad(skgo.LoadSpec{Module: "src/routes/account/statement/+page.server.ts", Run: load_account_statement_page, Matchers: skgo19.SkgoParamMatchers()}),
		skgo.NewServerLoad(skgo.LoadSpec{Module: "src/routes/actions/+page.server.ts", Run: load_actions_page, Matchers: skgo8.SkgoParamMatchers()}),
		skgo.NewServerLoad(skgo.LoadSpec{Module: "src/routes/actions/cross/receive/+page.server.ts", Run: load_actions_cross_receive_page, Matchers: skgo9.SkgoParamMatchers()}),
		skgo.NewServerLoad(skgo.LoadSpec{Module: "src/routes/actions/default/saved/+page.server.ts", Run: load_actions_default_saved_page, Matchers: skgo11.SkgoParamMatchers()}),
		skgo.NewServerLoad(skgo.LoadSpec{Module: "src/routes/actions/options/no-client/+page.server.ts", Run: load_actions_options_noclient_page, Matchers: skgo12.SkgoParamMatchers()}),
		skgo.NewServerLoad(skgo.LoadSpec{Module: "src/routes/actions/options/no-ssr/+page.server.ts", Run: load_actions_options_nossr_page, Matchers: skgo13.SkgoParamMatchers()}),
		skgo.NewServerLoad(skgo.LoadSpec{Module: "src/routes/actions/profiles/[profile]/+page.server.ts", Run: load_actions_profiles_profile_page, Matchers: skgo14.SkgoParamMatchers()}),
		skgo.NewServerLoad(skgo.LoadSpec{Module: "src/routes/actions/signed-in/+page.server.ts", Run: load_actions_signedin_page, Matchers: skgo15.SkgoParamMatchers()}),
		skgo.NewServerLoad(skgo.LoadSpec{Module: "src/routes/destinations/+page.server.ts", Run: load_destinations_page, Matchers: skgo30.SkgoParamMatchers()}),
		skgo.NewServerLoad(skgo.LoadSpec{Module: "src/routes/empty/+page.server.ts", Run: load_empty_page, Matchers: skgo31.SkgoParamMatchers()}),
		skgo.NewServerLoad(skgo.LoadSpec{Module: "src/routes/error/expected/+page.server.ts", Run: load_error_expected_page, Matchers: skgo34.SkgoParamMatchers()}),
		skgo.NewServerLoad(skgo.LoadSpec{Module: "src/routes/error/unexpected/+page.server.ts", Run: load_error_unexpected_page, Matchers: skgo36.SkgoParamMatchers()}),
		skgo.NewServerLoad(skgo.LoadSpec{Module: "src/routes/go-dev/+page.server.ts", Run: load_godev_page, Matchers: skgo37.SkgoParamMatchers()}),
		skgo.NewServerLoad(skgo.LoadSpec{Module: "src/routes/invoices/+page.server.ts", Run: load_invoices_page, Matchers: skgo39.SkgoParamMatchers()}),
		skgo.NewServerLoad(skgo.LoadSpec{Module: "src/routes/middleware/+page.server.ts", Run: load_middleware_page, Matchers: skgo42.SkgoParamMatchers()}),
		skgo.NewServerLoad(skgo.LoadSpec{Module: "src/routes/middleware/[slug]/+page.server.ts", Run: load_middleware_slug_page, Matchers: skgo43.SkgoParamMatchers()}),
		skgo.NewServerLoad(skgo.LoadSpec{Module: "src/routes/prerender/[slug]/+page.server.ts", Run: load_prerender_slug_page, Matchers: skgo45.SkgoParamMatchers()}),
		skgo.NewServerLoad(skgo.LoadSpec{Module: "src/routes/request-fetch/+page.server.ts", Run: load_requestfetch_page, Matchers: skgo46.SkgoParamMatchers()}),
		skgo.NewServerLoad(skgo.LoadSpec{Module: "src/routes/stream/+page.server.ts", Run: load_stream_page, Matchers: skgo48.SkgoParamMatchers()}),
		skgo.NewServerLoad(skgo.LoadSpec{Module: "src/routes/typed-dependencies/[a=Order]/[b=Order]/[ignored]/+page.server.ts", Run: load_typeddependencies_aOrder_bOrder_ignored_page, Matchers: skgo5.SkgoParamMatchers()}),
		skgo.NewServerLoad(skgo.LoadSpec{Module: "src/routes/typed-load/[number=Order]/+page.server.ts", Run: load_typedload_numberOrder_page, Matchers: skgo6.SkgoParamMatchers()}),
	}
}

func action_actions_page_archive(ctx context.Context) (any, error) {
	return nil, skgo8.Skgo_archive(ctx)
}

func action_actions_page_forbidden(ctx context.Context) (any, error) {
	return nil, skgo8.Skgo_forbidden(ctx)
}

func action_actions_page_inspect(ctx context.Context) (any, error) { return skgo8.Skgo_inspect(ctx) }

func action_actions_page_remember(ctx context.Context) (any, error) { return skgo8.Skgo_remember(ctx) }

func action_actions_page_remote(ctx context.Context) (any, error) { return skgo8.Skgo_remote(ctx) }

func action_actions_page_save(ctx context.Context) (any, error) { return skgo8.Skgo_save(ctx) }

func action_actions_page_signIn(ctx context.Context) (any, error) { return nil, skgo8.Skgo_signIn(ctx) }

func action_actions_page_unavailable(ctx context.Context) (any, error) {
	return nil, skgo8.Skgo_unavailable(ctx)
}

func action_actions_page_upload(ctx context.Context) (any, error) { return skgo8.Skgo_upload(ctx) }

func action_actions_cross_receive_page_forbidden(ctx context.Context) (any, error) {
	return nil, skgo9.Skgo_forbidden(ctx)
}

func action_actions_cross_receive_page_save(ctx context.Context) (any, error) {
	return skgo9.Skgo_save(ctx)
}

func action_actions_cross_receive_page_signIn(ctx context.Context) (any, error) {
	return nil, skgo9.Skgo_signIn(ctx)
}

func action_actions_cross_receive_page_unavailable(ctx context.Context) (any, error) {
	return nil, skgo9.Skgo_unavailable(ctx)
}

func action_actions_default_page_default(ctx context.Context) (any, error) {
	return skgo10.Skgo_save(ctx)
}

func action_actions_options_noclient_page_forbidden(ctx context.Context) (any, error) {
	return nil, skgo12.Skgo_forbidden(ctx)
}

func action_actions_options_noclient_page_save(ctx context.Context) (any, error) {
	return skgo12.Skgo_save(ctx)
}

func action_actions_options_noclient_page_unavailable(ctx context.Context) (any, error) {
	return nil, skgo12.Skgo_unavailable(ctx)
}

func action_actions_options_nossr_page_forbidden(ctx context.Context) (any, error) {
	return nil, skgo13.Skgo_forbidden(ctx)
}

func action_actions_options_nossr_page_save(ctx context.Context) (any, error) {
	return skgo13.Skgo_save(ctx)
}

func action_actions_options_nossr_page_signIn(ctx context.Context) (any, error) {
	return nil, skgo13.Skgo_signIn(ctx)
}

func action_actions_options_nossr_page_unavailable(ctx context.Context) (any, error) {
	return nil, skgo13.Skgo_unavailable(ctx)
}

func action_actions_profiles_profile_page_save(ctx context.Context) (any, error) {
	return skgo14.Skgo_save(ctx)
}

func action_godev_page_revise(ctx context.Context) (any, error) { return skgo37.Skgo_revise(ctx) }

func action_middleware_page_default(ctx context.Context) (any, error) { return skgo42.Skgo_note(ctx) }

// Actions returns the Go handlers for classic page actions.
func Actions() []*skgo.PageAction {
	return []*skgo.PageAction{
		skgo.NewPageAction(skgo.ActionSpec{Module: "src/routes/actions/+page.server.ts", Name: "archive", Run: action_actions_page_archive}),
		skgo.NewPageAction(skgo.ActionSpec{Module: "src/routes/actions/+page.server.ts", Name: "forbidden", Run: action_actions_page_forbidden}),
		skgo.NewPageAction(skgo.ActionSpec{Module: "src/routes/actions/+page.server.ts", Name: "inspect", Run: action_actions_page_inspect}),
		skgo.NewPageAction(skgo.ActionSpec{Module: "src/routes/actions/+page.server.ts", Name: "remember", Run: action_actions_page_remember}),
		skgo.NewPageAction(skgo.ActionSpec{Module: "src/routes/actions/+page.server.ts", Name: "remote", Run: action_actions_page_remote}),
		skgo.NewPageAction(skgo.ActionSpec{Module: "src/routes/actions/+page.server.ts", Name: "save", Run: action_actions_page_save}),
		skgo.NewPageAction(skgo.ActionSpec{Module: "src/routes/actions/+page.server.ts", Name: "signIn", Run: action_actions_page_signIn}),
		skgo.NewPageAction(skgo.ActionSpec{Module: "src/routes/actions/+page.server.ts", Name: "unavailable", Run: action_actions_page_unavailable}),
		skgo.NewPageAction(skgo.ActionSpec{Module: "src/routes/actions/+page.server.ts", Name: "upload", Run: action_actions_page_upload}),
		skgo.NewPageAction(skgo.ActionSpec{Module: "src/routes/actions/cross/receive/+page.server.ts", Name: "forbidden", Run: action_actions_cross_receive_page_forbidden}),
		skgo.NewPageAction(skgo.ActionSpec{Module: "src/routes/actions/cross/receive/+page.server.ts", Name: "save", Run: action_actions_cross_receive_page_save}),
		skgo.NewPageAction(skgo.ActionSpec{Module: "src/routes/actions/cross/receive/+page.server.ts", Name: "signIn", Run: action_actions_cross_receive_page_signIn}),
		skgo.NewPageAction(skgo.ActionSpec{Module: "src/routes/actions/cross/receive/+page.server.ts", Name: "unavailable", Run: action_actions_cross_receive_page_unavailable}),
		skgo.NewPageAction(skgo.ActionSpec{Module: "src/routes/actions/default/+page.server.ts", Name: "default", Run: action_actions_default_page_default}),
		skgo.NewPageAction(skgo.ActionSpec{Module: "src/routes/actions/options/no-client/+page.server.ts", Name: "forbidden", Run: action_actions_options_noclient_page_forbidden}),
		skgo.NewPageAction(skgo.ActionSpec{Module: "src/routes/actions/options/no-client/+page.server.ts", Name: "save", Run: action_actions_options_noclient_page_save}),
		skgo.NewPageAction(skgo.ActionSpec{Module: "src/routes/actions/options/no-client/+page.server.ts", Name: "unavailable", Run: action_actions_options_noclient_page_unavailable}),
		skgo.NewPageAction(skgo.ActionSpec{Module: "src/routes/actions/options/no-ssr/+page.server.ts", Name: "forbidden", Run: action_actions_options_nossr_page_forbidden}),
		skgo.NewPageAction(skgo.ActionSpec{Module: "src/routes/actions/options/no-ssr/+page.server.ts", Name: "save", Run: action_actions_options_nossr_page_save}),
		skgo.NewPageAction(skgo.ActionSpec{Module: "src/routes/actions/options/no-ssr/+page.server.ts", Name: "signIn", Run: action_actions_options_nossr_page_signIn}),
		skgo.NewPageAction(skgo.ActionSpec{Module: "src/routes/actions/options/no-ssr/+page.server.ts", Name: "unavailable", Run: action_actions_options_nossr_page_unavailable}),
		skgo.NewPageAction(skgo.ActionSpec{Module: "src/routes/actions/profiles/[profile]/+page.server.ts", Name: "save", Run: action_actions_profiles_profile_page_save}),
		skgo.NewPageAction(skgo.ActionSpec{Module: "src/routes/go-dev/+page.server.ts", Name: "revise", Run: action_godev_page_revise}),
		skgo.NewPageAction(skgo.ActionSpec{Module: "src/routes/middleware/+page.server.ts", Name: "default", Run: action_middleware_page_default}),
	}
}

// Endpoints returns every server route declared in the app, ready to hand
// to skgo.NewEndpoints.
func Endpoints() []*skgo.Endpoint {
	return []*skgo.Endpoint{
		skgo.NewEndpoint("/actions", "POST", skgo8.Skgo_endpointPost),
		skgo.NewEndpoint("/actions/default", "GET", skgo10.Skgo_endpointGet),
		skgo.NewEndpoint("/api/fatal", "GET", skgo20.Skgo_fail),
		skgo.NewEndpoint("/api/replay-count", "GET", skgo21.Skgo_counts),
		skgo.NewEndpoint("/api/replay/[kind]", "GET", skgo22.Skgo_get),
		skgo.NewEndpoint("/api/replay/[kind]", "POST", skgo22.Skgo_post),
		skgo.NewEndpoint("/api/request-fetch", "GET", skgo23.Skgo_fact),
		skgo.NewEndpoint("/api/todos", "GET", skgo24.Skgo_list),
		skgo.NewEndpoint("/api/todos", "POST", skgo24.Skgo_add),
		skgo.NewEndpoint("/api/todos", "QUERY", skgo24.Skgo_search),
		skgo.NewEndpoint("/async-ssr/control/[group]", "GET", skgo26.Skgo_status),
		skgo.NewEndpoint("/async-ssr/control/[group]", "POST", skgo26.Skgo_release),
		skgo.NewEndpoint("/go-dev/endpoint", "GET", skgo38.Skgo_get),
		skgo.NewEndpoint("/shadow/[...rest]", "GET", skgo47.Skgo_get),
	}
}

// Transport is the app's `transport` hook: the Go half of the encode/decode
// pairs src/hooks.ts declares. Hand it to skgo.RemoteConfig.Transport and
// skgo.LoadConfig.Transport.
//
// Each key must be spelled the same here and in src/hooks.ts: it is what the
// value travels under, and a client with no decoder for it cannot read the
// response at all.
func Transport() skgo.Transport {
	return skgo.Transport{
		"Money": {
			Type:   reflect.TypeFor[skgotp0.Money](),
			Encode: func(v any) (any, error) { return EncodeMoney(v.(skgotp0.Money)) },
			Decode: func(raw any) (any, error) { return DecodeMoney(raw) },
		},
	}
}
